Repository openstack-k8s-operators/ci-framework, pull requests merged in 2023-06, with the labels that each got.

#231 Use OPERATOR_NAMESPACE in operator installation
  ci_framework/roles/edpm_prepare/tasks/main.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#223 Retry `make_crc_storage` task
  ci_framework/plugins/modules/generate_make_tasks.py
  ci_framework/roles/edpm_prepare/tasks/main.yml
Labels: approved

#233 Add some more people to OWNERS
  OWNERS
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#184 Run commands before and after kuttl run
  ci/playbooks/kuttl/e2e-kuttl.yml
  ci/playbooks/kuttl/run-kuttl-tests.yml
  scenarios/centos-9/kuttl.yml
  zuul.d/kuttl.yaml
Labels: approved, lgtm

#239 Use zuul clonned dataplane-operator code for edpm deploy
  scenarios/centos-9/edpm_ci.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#237 Fix minor issues in sudoers setup doc
  docs/source/Quickstart/01_requirements.md
Labels: approved, lgtm

#236 Do not run workflow on issues
  .github/workflows/require-checklist.yaml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#232 Move log collection in post-run zuul step
  ci/playbooks/e2e-collect-logs.yml
  ci/playbooks/edpm/run.yml
  deploy-edpm.yml
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
Labels: approved

#238 add collection of Openstack CR instances.
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#242 Collect meta operator related logs
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#240 Installing oc as part of ci_setup
  ci_framework/roles/ci_setup/README.md
  ci_framework/roles/ci_setup/defaults/main.yml
  ci_framework/roles/ci_setup/meta/main.yml
  ci_framework/roles/ci_setup/molecule/default/converge.yml
  ci_framework/roles/ci_setup/tasks/packages.yml
  ci_framework/roles/ci_setup/vars/main.yml
Labels: approved, lgtm

#243 Update/correct example for role
  ci_framework/roles/discover_latest_image/README.md
Labels: approved, lgtm

#244 Change kuttl job to use 'base-simple-crc' as parent job
  zuul.d/kuttl.yaml
Labels: approved, lgtm

#201 Use base-simple-crc as a parent for EDPM jobs
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_prepare/README.md
  ci_framework/roles/edpm_prepare/tasks/main.yml
  scenarios/centos-9/edpm_ci.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#247 Fix minor doc issues in non-virt deployment
  docs/source/Quickstart/04_non-virt.md
Labels: approved, lgtm

#248 Add baremetal-operator in required project & sort
  zuul.d/edpm.yaml
Labels: approved, lgtm

#246 Consolidate a bit ansible code
  ci_framework/roles/artifacts/tasks/cleanup.yml
  ci_framework/roles/artifacts/tasks/main.yml
  ci_framework/roles/artifacts/tasks/packages.yml
  ci_framework/roles/build_openstack_packages/tasks/install_dlrn.yml
  ci_framework/roles/ci_setup/tasks/packages.yml
  ci_framework/roles/copy_container/tasks/cron.yml
  ci_framework/roles/copy_container/tasks/main.yml
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_prepare/tasks/cleanup.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/install_ca/tasks/main.yml
  ci_framework/roles/install_yamls/tasks/main.yml
  ci_framework/roles/libvirt_manager/tasks/main.yml
  ci_framework/roles/libvirt_manager/tasks/packages.yml
  ci_framework/roles/local_env_vm/tasks/main.yml
  ci_framework/roles/openshift_login/tasks/cleanup.yml
  ci_framework/roles/openshift_setup/tasks/cleanup.yml
  ci_framework/roles/operator_build/tasks/main.yml
  ci_framework/roles/pkg_build/tasks/cleanup.yml
  ci_framework/roles/pkg_build/tasks/main.yml
  ci_framework/roles/registry_deploy/tasks/main.yml
  ci_framework/roles/rhol_crc/tasks/dependencies.yml
  ci_framework/roles/rhol_crc/tasks/main.yml
  ci_framework/roles/run_hook/tasks/cleanup.yml
  ci_framework/roles/test_deps/tasks/main.yml
  docs/source/Usage/01_usage.md
Labels: approved, lgtm

#250 Pass proper namespace while collecting pods info
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#252 Fix pod log collection
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#245 Remove crc bits from cifmw-base-crc-openstack and rename it
  zuul.d/edpm.yaml
Labels: approved, lgtm

#254 Use lower case directory name for doc tree
  docs/source/cookbooks/01_comingsoon.md
  docs/source/development/01_contributing.md
  docs/source/development/02_molecule.md
  docs/source/index.rst
  docs/source/internals/01_structure.md
  docs/source/internals/02_testing.md
  docs/source/quickstart/01_requirements.md
  docs/source/quickstart/02_nested_virt.md
  docs/source/quickstart/03_psi.md
  docs/source/quickstart/04_non-virt.md
  docs/source/quickstart/99_FAQ.md
  docs/source/roles/artifacts.md
  docs/source/roles/build_openstack_packages.md
  docs/source/roles/ci_setup.md
  docs/source/roles/discover_latest_image.md
  docs/source/roles/edpm_deploy.md
  docs/source/roles/edpm_deploy_baremetal.md
  docs/source/roles/edpm_prepare.md
  docs/source/roles/install_ca.md
  docs/source/roles/install_yamls.md
  docs/source/roles/libvirt_manager.md
  docs/source/roles/local_env_vm.md
  docs/source/roles/openshift_login.md
  docs/source/roles/openshift_setup.md
  docs/source/roles/operator_build.md
  docs/source/roles/operator_deploy.md
  docs/source/roles/pkg_build.md
  docs/source/roles/registry_deploy.md
  docs/source/roles/repo_setup.md
  docs/source/roles/rhol_crc.md
  docs/source/roles/run_hook.md
  docs/source/roles/test_deps.md
  docs/source/usage/01_usage.md
  docs/source/usage/02_own_ci.md
  scripts/create_role_molecule
Labels: approved, lgtm

#253 Actually enable tags in ansible
  ci_framework/playbooks/01-bootstrap.yml
  ci_framework/playbooks/02-infra.yml
  ci_framework/playbooks/03-build-packages.yml
  ci_framework/playbooks/04-build-containers.yml
  ci_framework/playbooks/05-build-operators.yml
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/playbooks/99-logs.yml
  ci_framework/playbooks/hooks.yml
  ci_framework/roles/build_openstack_packages/tasks/main.yml
  ci_framework/roles/ci_setup/tasks/cleanup.yml
  ci_framework/roles/ci_setup/tasks/main.yml
  ci_framework/roles/copy_container/tasks/main.yml
  ci_framework/roles/libvirt_manager/tasks/main.yml
  ci_framework/roles/openshift_login/tasks/login.yml
  ci_framework/roles/repo_setup/tasks/main.yml
  ci_framework/roles/rhol_crc/tasks/main.yml
Labels: approved, lgtm

#255 Start contribution guidelines
  docs/source/development/01_guidelines.md
Labels: approved, lgtm

#258 Improve documentation related to tags
  docs/source/usage/01_usage.md
Labels: approved, lgtm

#260 Fixing typo in copy containers
  ci_framework/roles/copy_container/tasks/main.yml
Labels: approved, lgtm

#257 Convert -nobuild job to -tagged-nobuild
  ci/playbooks/e2e-run.yml
  ci/templates/projects.yaml
  ci_framework/playbooks/01-bootstrap.yml
  ci_framework/roles/artifacts/tasks/cluster_info.yml
  zuul.d/end-to-end.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#264 Add a var in operator_build role to disable tls verify
  ci_framework/roles/operator_build/README.md
  ci_framework/roles/operator_build/defaults/main.yml
  ci_framework/roles/operator_build/tasks/build.yml
  scenarios/centos-9/content_provider.yml
Labels: approved, lgtm

#266 Add support to skip registry login
  ci_framework/roles/openshift_setup/README.md
  ci_framework/roles/openshift_setup/defaults/main.yml
  ci_framework/roles/openshift_setup/tasks/main.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#265 Cookbook receipt: speed up daily use
  docs/source/cookbooks/01_comingsoon.md
  docs/source/cookbooks/speed-up-dev.md
Labels: approved, lgtm

#251 Add playbook to validate podified deployment
  ci_framework/hooks/playbooks/validate_podified_deployment.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#268 Move repeated e2e job content in a base job
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#267 Explain cifmw_extras
  docs/source/usage/02_own_ci.md
Labels: documentation, approved, lgtm

#269 Document existing hooks
  ci_framework/hooks/playbooks/README.md
  docs/source/usage/available-hooks.md
Labels: documentation, approved, lgtm

#273 Don't build the storage-bundle separately
  ci_framework/roles/operator_build/README.md
  ci_framework/roles/operator_build/defaults/main.yml
  ci_framework/roles/operator_build/molecule/default/validate_outputs.yml
  ci_framework/roles/operator_build/tasks/build.yml
  scenarios/centos-9/ci-build.yml
  scenarios/centos-9/content_provider.yml
Labels: approved, lgtm

#278 Use local registry for local bundles in catalog build
  ci_framework/roles/operator_build/tasks/build.yml
Labels: approved, lgtm

#276 Remove dependency on discover_latest_image
  ci_framework/roles/libvirt_manager/meta/main.yml
Labels: approved, lgtm

#279 Run make_crc_attach_default_interface in kuttl tests
  ci/playbooks/kuttl/e2e-kuttl.yml
Labels: approved, lgtm

#281 Replacing existing note about PR with explicit version requirement
  ci_framework/plugins/README.md
  ci_framework/plugins/action/ci_make.py
Labels: approved, lgtm

#241 Removed the legacy global edpm_env
  ci_framework/hooks/playbooks/ceph-deploy.yml
  ci_framework/plugins/modules/generate_make_tasks.py
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/install_yamls/molecule/default/converge.yml
  ci_framework/roles/install_yamls/tasks/main.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_edpm_compute.yml
Labels: approved, lgtm

#283 ansible-requirements include
  scripts/setup_env
  scripts/setup_molecule
Labels: approved, lgtm

#277 Adds cifmw_extras to kuttl-run playbook
  ci/playbooks/e2e-run.yml
  ci/playbooks/edpm/run.yml
  ci/playbooks/edpm_baremetal_deployment/run.yml
  ci/playbooks/kuttl/run.yml
Labels: approved, lgtm

#288 Added new contributor as reviewer
  OWNERS
Labels: approved, lgtm

#284 Adjusting ci_make for community.general > 6.5.0
  ci_framework/plugins/action/ci_make.py
  requirements.yml
Labels: approved, lgtm

#289 [Nested] more working defaults
  ci/playbooks/dev-workflow.yml
  ci_framework/roles/local_env_vm/README.md
  ci_framework/roles/local_env_vm/defaults/main.yml
  docs/source/quickstart/99_FAQ.md
Labels: approved, lgtm

#292 Fix cifmw_edpm_deploy_baremetal_common_env vars
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#286 pass ansible_cfg to content provider run playbook
  ci/playbooks/content_provider/run.yml
Labels: approved, lgtm

#205 Openshift setup role managing registry permissions
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/openshift_setup/tasks/main.yml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#296 Setting defaults for command key of the returned dict
  ci_framework/plugins/action/ci_make.py
Labels: approved, lgtm

#294 Added documentation examples install_yamls environment and default vars.
  CONTRIBUTING.md
Labels: approved, lgtm

#297 Negative testing for ci_make
  ci_framework/tests/integration/targets/make/tasks/main.yml
Labels: approved, lgtm

#176 Add edpm build images role
  ci/playbooks/edpm_build_images/edpm_image_builder.yml
  ci/playbooks/edpm_build_images/run.yml
  ci/templates/projects.yaml
  ci_framework/roles/edpm_build_images/README.md
  ci_framework/roles/edpm_build_images/defaults/main.yml
  ci_framework/roles/edpm_build_images/meta/main.yml
  ci_framework/roles/edpm_build_images/molecule/default/converge.yml
  ci_framework/roles/edpm_build_images/molecule/default/molecule.yml
  ci_framework/roles/edpm_build_images/molecule/default/prepare.yml
  ci_framework/roles/edpm_build_images/tasks/install.yml
  ci_framework/roles/edpm_build_images/tasks/main.yml
  ci_framework/roles/edpm_build_images/tasks/package.yml
  ci_framework/roles/edpm_build_images/tasks/run.yml
  docs/source/roles/edpm_build_images.md
  zuul.d/edpm_build_images.yaml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Feature

#304 Ensure we're having cifmw_path parameter
  ci_framework/playbooks/99-logs.yml
Labels: approved, lgtm

#301 Pass KUBECONFIG to all make targets using cifmw_install_yamls_environment
  ci_framework/hooks/playbooks/ceph-deploy.yml
  ci_framework/hooks/playbooks/disable_os_marketplace.yml
  ci_framework/hooks/playbooks/rabbitmq_tuning.yml
  ci_framework/hooks/playbooks/restart_nova_scheduler.yml
  ci_framework/hooks/playbooks/validate_podified_deployment.yml
  ci_framework/playbooks/01-bootstrap.yml
  ci_framework/playbooks/02-infra.yml
  ci_framework/playbooks/03-build-packages.yml
  ci_framework/playbooks/04-build-containers.yml
  ci_framework/playbooks/05-build-operators.yml
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/playbooks/99-logs.yml
  ci_framework/roles/ci_setup/tasks/directories.yml
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/install_yamls/tasks/main.yml
  ci_framework/roles/openshift_login/molecule/default/converge.yml
  ci_framework/roles/openshift_login/molecule/default/prepare.yml
  ci_framework/roles/openshift_login/tasks/main.yml
  ci_framework/roles/run_hook/tasks/playbook.yml
Labels: approved, lgtm

#302 Ensuring log dir is only queries for selinux info if it exists
  ci/playbooks/collect-logs.yml
Labels: approved, lgtm

#305 Protect 99-logs and subsequent artifacts role
  ci_framework/playbooks/99-logs.yml
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#295 Get the pods names with all information
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#308 Grab CRC VM logs from its disk image
  ci_framework/roles/artifacts/tasks/crc.yml
  ci_framework/roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#315 Temporary disable the "admin_setup" step
  deploy-edpm.yml
Labels: approved, lgtm

#313 Improve trigger for CRC log gathering
  ci_framework/roles/artifacts/tasks/crc.yml
  ci_framework/roles/artifacts/tasks/main.yml
  ci_framework/roles/rhol_crc/tasks/find_crc.yml
  ci_framework/roles/rhol_crc/tasks/main.yml
Labels: approved

#161 Adds ansible role for claiming and unclaiming clusters through hive
  ci_framework/roles/hive/README.md
  ci_framework/roles/hive/defaults/main.yml
  ci_framework/roles/hive/molecule/default/converge.yml
  ci_framework/roles/hive/molecule/default/molecule.yml
  ci_framework/roles/hive/molecule/default/prepare.yml
  ci_framework/roles/hive/tasks/main.yml
  ci_framework/roles/hive/tasks/oc_apply.yml
  ci_framework/roles/hive/tasks/oc_delete.yml
  ci_framework/roles/hive/tasks/openstack_claim_cluster.yml
  ci_framework/roles/hive/tasks/openstack_unclaim_cluster.yml
  ci_framework/roles/hive/templates/claim.yml.j2
  docs/source/roles/hive.md
  docs/source/usage/01_usage.md
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, do-not-merge/contains-merge-commits, Feature

#318 Ensure libguestfs is installed when gathering CRC VM logs
  ci_framework/roles/artifacts/tasks/crc.yml
  ci_framework/roles/artifacts/vars/main.yml
Labels: approved, lgtm

#316 Remove install_yamls operator repositories from artifacts
  ci_framework/roles/artifacts/tasks/cleanup.yml
  ci_framework/roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#314 Increase CRC memory
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#275 Adding a new role - openshift_provisioner_node
  ci_framework/playbooks/02-infra.yml
  ci_framework/roles/openshift_provisioner_node/README.md
  ci_framework/roles/openshift_provisioner_node/defaults/main.yml
  ci_framework/roles/openshift_provisioner_node/files/add_bridge_port.sh
  ci_framework/roles/openshift_provisioner_node/meta/main.yml
  ci_framework/roles/openshift_provisioner_node/molecule/defaults/converge.yml
  ci_framework/roles/openshift_provisioner_node/molecule/defaults/molecule.yml
  ci_framework/roles/openshift_provisioner_node/molecule/defaults/prepare.yml
  ci_framework/roles/openshift_provisioner_node/tasks/add_bridges.yml
  ci_framework/roles/openshift_provisioner_node/tasks/add_user.yml
  ci_framework/roles/openshift_provisioner_node/tasks/add_virtual_network.yml
  ci_framework/roles/openshift_provisioner_node/tasks/cleanup.yml
  ci_framework/roles/openshift_provisioner_node/tasks/cleanup_virtual_network.yml
  ci_framework/roles/openshift_provisioner_node/tasks/install_packages.yml
  ci_framework/roles/openshift_provisioner_node/tasks/main.yml
  ci_framework/roles/openshift_provisioner_node/templates/virt_net.xml.j2
  ci_framework/roles/openshift_provisioner_node/vars/main.yml
  docs/source/roles/openshift_provisioner_node.md
  docs/source/usage/01_usage.md
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Feature

#290 Add support for TLS verification skipping in Podman logins.
  ci_framework/roles/openshift_setup/README.md
  ci_framework/roles/openshift_setup/defaults/main.yml
  ci_framework/roles/openshift_setup/tasks/main.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#287 Moving documentation build script into separate file
  .gitignore
  Makefile
  ci/playbooks/collect-logs.yml
  docs/doc-requirements.txt
  docs/source/Makefile
  docs/source/build-docs.sh
Labels: approved, lgtm

#306 Remove operator namespace workaround
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: approved, lgtm

#220 Add polarion role
  ci_framework/roles/polarion/README.md
  ci_framework/roles/polarion/defaults/main.yml
  ci_framework/roles/polarion/meta/main.yml
  ci_framework/roles/polarion/molecule/default/converge.yml
  ci_framework/roles/polarion/molecule/default/molecule.yml
  ci_framework/roles/polarion/tasks/cleanup.yml
  ci_framework/roles/polarion/tasks/main.yml
  ci_framework/roles/polarion/vars/main.yml
  docs/source/roles/polarion.md
  zuul.d/molecule.yaml
Labels: approved, lgtm, Feature

#312 Add edpm and ipa build images content provider check job
  ci/playbooks/edpm_build_images/edpm_build_images_content_provider.yaml
  ci/playbooks/edpm_build_images/edpm_build_images_content_provider_run.yaml
  ci/templates/projects.yaml
  scenarios/centos-9/edpm_build_images_content_provider.yml
  zuul.d/edpm_build_images_content_provider.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#322 Add ci_script action plugin
  Makefile
  ci_framework/plugins/action/ci_script.py
  ci_framework/tests/integration/targets/script/tasks/main.yml
Labels: approved, lgtm

#216 Create tempest role
  ci/playbooks/collect-logs.yml
  ci_framework/playbooks/08-run-tests.yml
  ci_framework/plugins/README.md
  ci_framework/plugins/modules/tempest_list_allowed.py
  ci_framework/plugins/modules/tempest_list_skipped.py
  ci_framework/roles/tempest/README.md
  ci_framework/roles/tempest/defaults/main.yml
  ci_framework/roles/tempest/files/list_allowed.yml
  ci_framework/roles/tempest/files/list_skipped.yml
  ci_framework/roles/tempest/meta/main.yml
  ci_framework/roles/tempest/molecule/default/converge.yml
  ci_framework/roles/tempest/molecule/default/molecule.yml
  ci_framework/roles/tempest/molecule/default/prepare.yml
  ci_framework/roles/tempest/tasks/configure-tempest.yml
  ci_framework/roles/tempest/tasks/main.yml
  ci_framework/roles/tempest/tasks/tempest-tests.yml
  ci_framework/roles/tempest/templates/clouds.yaml.j2
  ci_framework/tests/sanity/ignore.txt
  deploy-edpm.yml
  docs/source/roles/tempest.md
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Feature

#326 Add ci-framework in required-projects list for content-provider-build-images-base job
  zuul.d/edpm_build_images_content_provider.yaml
Labels: approved, lgtm

#310 Retry getting k8s resource
  ci_framework/roles/edpm_prepare/tasks/main.yml
  deploy-edpm.yml
Labels: approved, lgtm

#330 Set cifmw_run_tests to false by default and run tempest on e2e jobs
  deploy-edpm.yml
  scenarios/centos-9/ci.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#282 Module level docs for ci_make
  ci_framework/plugins/action/ci_make.py
Labels: approved, lgtm

#262 Add section to the FAQ doc - control plane debug
  docs/source/quickstart/99_FAQ.md
Labels: documentation, approved, lgtm

#328 Dynamically retrieve base module name
  ci_framework/roles/operator_build/tasks/build.yml
Labels: approved, lgtm

#303 Openshift login/additional molecule tests
  ci_framework/roles/openshift_login/molecule/default/cleanup.yml
  ci_framework/roles/openshift_login/molecule/default/converge.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_kubeconfig/cleanup.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_kubeconfig/converge.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_kubeconfig/molecule.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_kubeconfig/prepare.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_no_kubeconfig/cleanup.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_no_kubeconfig/converge.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_no_kubeconfig/molecule.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_no_kubeconfig/prepare.yml
  ci_framework/roles/openshift_login/molecule/login_token_based/cleanup.yml
  ci_framework/roles/openshift_login/molecule/login_token_based/converge.yml
  ci_framework/roles/openshift_login/molecule/login_token_based/molecule.yml
  ci_framework/roles/openshift_login/molecule/login_token_based/prepare.yml
  ci_framework/roles/openshift_login/tasks/try_login.yml
Labels: approved, lgtm

#334 Add improved common validation for openshift_login molecule tests
  ci_framework/roles/openshift_login/molecule/default/converge.yml
  ci_framework/roles/openshift_login/molecule/default/validate_login_facts.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_kubeconfig/converge.yml
  ci_framework/roles/openshift_login/molecule/login_pwd_no_kubeconfig/converge.yml
  ci_framework/roles/openshift_login/molecule/login_token_based/converge.yml
Labels: approved, lgtm

#317 os_net_setup: rely on openshift_login context
  ci_framework/playbooks/07-admin-setup.yml
  ci_framework/roles/os_net_setup/README.md
  ci_framework/roles/os_net_setup/defaults/main.yml
  ci_framework/roles/os_net_setup/tasks/main.yml
Labels: approved, lgtm

#321 Adds edpm/baremetal periodic jobs
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_periodic.yml
  zuul.d/edpm.yaml
  zuul.d/edpm_periodic.yaml
Labels: approved, lgtm

#336 Inject a README file in generated logs
  ci/playbooks/collect-logs.yml
  ci/playbooks/files/important-logs.html
Labels: approved, lgtm

#331 Parse images file without beautifulsoup4
  ci_framework/plugins/README.md
  ci_framework/plugins/action/discover_latest_image.py
  ci_framework/roles/discover_latest_image/README.md
  ci_framework/roles/discover_latest_image/defaults/main.yml
  ci_framework/roles/discover_latest_image/molecule/default/converge.yml
  ci_framework/roles/discover_latest_image/tasks/main.yml
  ci_framework/roles/libvirt_manager/defaults/main.yml
  ci_framework/roles/local_env_vm/tasks/main.yml
  docs/source/quickstart/03_psi.md
  requirements.txt
Labels: approved, lgtm

#338 Add collect container stats
  ci/playbooks/collect-logs.yml
  ci/playbooks/e2e-prepare.yml
  docs/source/usage/01_usage.md
  scripts/get-stats.sh
Labels: approved, lgtm

#339 Patch CSV for ansible runner image
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/roles/edpm_deploy_baremetal/defaults/main.yml
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
  ci_framework/roles/edpm_prepare/defaults/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: approved, lgtm

#337 Fix quickstart doc typo
  docs/source/quickstart/01_requirements.md
Labels: approved, lgtm

#342 Improve a bit the README.html for logs
  ci/playbooks/files/important-logs.html
Labels: approved, lgtm

#335 Set DEPLOY_DIR var in BM jobs
  ci_framework/roles/install_yamls/defaults/main.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: approved, lgtm

#343 Collect logs for BMO and ironic
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#344 Inject pod namespace in tree
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#345 Removed uneeded KUBECONFIG env var from documentation
  docs/source/quickstart/04_non-virt.md
Labels: approved, lgtm
