Repository openstack-k8s-operators/ci-framework, pull requests merged in 2023-12, with the labels that each got.

#872 Modify and consolidate documentation
  CONTRIBUTING.md
  containerfiles/README.md
  docs/source/architecture/00_general_facts.md
  docs/source/architecture/01_lightweight.md
  docs/source/cookbooks/zuul-job-nodeset.md
  docs/source/development/02_molecule.md
  docs/source/quickstart/01_requirements.md
  docs/source/quickstart/02_prepare_env.md
  docs/source/quickstart/03_deploy_infra.md
  docs/source/quickstart/04_consume_infra.md
  docs/source/quickstart/05_clean_infra.md
  docs/source/quickstart/99_FAQ.md
  docs/source/reproducers/01-considerations.md
  docs/source/reproducers/02-layout.md
  docs/source/reproducers/03-zuul.md
  docs/source/usage/01_usage.md
  docs/source/usage/02_own_ci.md
  docs/source/usage/03_testing.md
Labels: approved, lgtm

#876 Remove local_env capability
  Makefile
  ci/playbooks/dev-workflow.yml
  ci/templates/projects.yaml
  ci_framework/roles/local_env_vm/README.md
  ci_framework/roles/local_env_vm/defaults/main.yml
  ci_framework/roles/local_env_vm/files/firstboot.sh
  ci_framework/roles/local_env_vm/meta/main.yml
  ci_framework/roles/local_env_vm/molecule/default/converge.yml
  ci_framework/roles/local_env_vm/molecule/default/molecule.yml
  ci_framework/roles/local_env_vm/tasks/main.yml
  dev-local-env.yml
  scenarios/centos-9/local-env.yml
  scripts/tests/test_create_role_molecule.py
  zuul.d/end-to-end.yaml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#853 Fix: Hybrid environment tagged network connectivity
  ci_framework/roles/devscripts/files/tag_vnet.sh
  ci_framework/roles/devscripts/tasks/sub_tasks/_521_gather.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_523_attach.yml
Labels: approved, lgtm

#866 Reduce the ammout of output of env_op_images
  ci_framework/roles/env_op_images/tasks/main.yml
Labels: approved, lgtm

#870 Adds config_nm false for data plane adoption standalone node
  zuul.d/adoption.yaml
Labels: approved, lgtm

#891 Temporarly pin ansible-core
  ansible-requirements.txt
Labels: approved, lgtm

#887 Point to the correct target to use
  Makefile
  zuul.d/base.yaml
Labels: approved, lgtm

#894 Add `rebtoor` (Roberto Alfieri) to reviewers
  OWNERS
Labels: approved, lgtm

#890 Fix the path for cifmw_openshift_kubeconfig
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#897 fix: correctly print the excluded tests, if any
  ci_framework/roles/tempest/tasks/tempest-tests.yml
Labels: approved, lgtm

#836 Fix MTU computing for EDPM in multinode
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#885 Reduce the controller nodeset
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
  zuul.d/kuttl_multinode.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#895 Fixing Ansible unsafe and unicode string usages
  ci_framework/plugins/action/ci_kustomize.py
  ci_framework/plugins/action/ci_make.py
  ci_framework/plugins/action/ci_script.py
  ci_framework/plugins/action/discover_latest_image.py
Labels: approved, lgtm

#902 Remove extra-verbose debugging
  ci_framework/roles/libvirt_manager/tasks/attach_interface.yml
Labels: approved, lgtm

#910 set owner and permissions for libvirt config files
  ci/playbooks/collect-logs.yml
Labels: approved, lgtm

#911 Revert "Try to be smarter with zuul jobs"
  zuul.d/edpm_multinode.yaml
Labels: approved

#899 Allow to create blank VMs
  ci_framework/roles/libvirt_manager/README.md
  ci_framework/roles/libvirt_manager/defaults/main.yml
  ci_framework/roles/libvirt_manager/molecule/deploy_layout/converge.yml
  ci_framework/roles/libvirt_manager/tasks/create_vms.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_layout.yml
  ci_framework/roles/libvirt_manager/tasks/get_image.yml
  ci_framework/roles/libvirt_manager/tasks/reserve_ip.yml
  ci_framework/roles/libvirt_manager/tasks/start_manage_vms.yml
  ci_framework/roles/libvirt_manager/vars/main.yml
  ci_framework/roles/reproducer/molecule/crc_layout/converge.yml
  ci_framework/roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#892 Revert "Temporarly pin ansible-core"
  ansible-requirements.txt
  ci_framework/roles/ci_nmstate/molecule/default/converge.yml
  ci_framework/roles/ci_nmstate/tasks/nmstate_unmanaged_provision_node.yml
Labels: approved, lgtm

#900 Remove individual network settings
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
  ci_framework/roles/hci_prepare/tasks/phase1.yml
Labels: approved, lgtm

#903 Update default value for the layout config
  ci_framework/roles/libvirt_manager/defaults/main.yml
Labels: approved, lgtm

#919 Fix the typo in create_new_role target help message
  Makefile
Labels: approved, lgtm

#920 Fix `new_role` target in the `CONTRIBUTING` file
  CONTRIBUTING.md
Labels: approved, lgtm

#907 [edpm_deploy]Install dataplane services
  ci_framework/roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#921 Add go.mod for files: match in data plane adoption job for meta operator
  zuul.d/adoption.yaml
Labels: approved, lgtm

#773 [cifmw_cephadm] Enable the usage of custom `haproxy` and `keepalived` container images
  ci_framework/roles/cifmw_cephadm/tasks/cephadm_config_set.yml
Labels: approved, lgtm

#925 Use AEE v1beta1
  ci_framework/tests/integration/targets/make/files/get_makefiles_env/expected_variables_values.yml
  ci_framework/tests/integration/targets/make/files/get_makefiles_env/makefiles/Makefile
Labels: approved, lgtm

#923 Enable documentation build for python libs
  .gitignore
  .readthedocs.yaml
  .spellcheck.yml
  Makefile
  ci_framework/plugins/module_utils/net_map/exceptions.py
  ci_framework/plugins/module_utils/net_map/ip_pools.py
  ci_framework/plugins/module_utils/net_map/networking_definition.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_all.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_group_template.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_instance.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_network.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_ranges.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_mapping_ip_pools.py
  ci_framework/tests/unit/module_utils/test_utils/net_map_stub_data.py
  docs/dictionary/en-custom.txt
  docs/source/Makefile
  docs/source/build-docs.sh
  docs/source/conf.py
  docs/source/index.rst
  docs/source/module_utils/.gitignore
  docs/source/usage/03_testing.md
  scripts/prepare_doc_build_env.sh
Labels: approved, lgtm

#927 Add RTD badge on doc
  README.md
Labels: approved, lgtm

#850 Install cert-manager from ci-framework cert-manager role
  ci_framework/playbooks/02-infra.yml
  scenarios/centos-9/ceph_backends.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#620 Refine the openshift variables to not dump to openshift_login only
  ci_framework/playbooks/01-bootstrap.yml
Labels: approved, lgtm

#928 Install python3-pip package in e2e-prepare.yml
  ci/playbooks/e2e-prepare.yml
Labels: approved, lgtm

#929 Allow to NOT have molecule job for selected role
  CONTRIBUTING.md
  ci_framework/roles/copy_container/molecule/default/converge.yml
  ci_framework/roles/copy_container/molecule/default/molecule.yml
  ci_framework/roles/os_net_setup/README.md
  ci_framework/roles/os_net_setup/molecule/default/converge.yml
  ci_framework/roles/os_net_setup/molecule/default/molecule.yml
  ci_framework/roles/polarion/README.md
  ci_framework/roles/polarion/molecule/default/converge.yml
  ci_framework/roles/polarion/molecule/default/molecule.yml
  scripts/create_role_molecule.py
  scripts/tests/test_create_role_molecule.py
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#932 Add the owner group in GroupTemplateDefinition
  ci_framework/plugins/module_utils/net_map/networking_definition.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_group_template.py
Labels: approved, lgtm

#844 Add iDRAC role to control Dell baremetal osp compute nodes
  ci_framework/roles/idrac_configuration/README.md
  ci_framework/roles/idrac_configuration/defaults/main.yml
  ci_framework/roles/idrac_configuration/meta/main.yml
  ci_framework/roles/idrac_configuration/molecule/default/converge.yml
  ci_framework/roles/idrac_configuration/molecule/default/molecule.yml
  ci_framework/roles/idrac_configuration/tasks/check_bios.yml
  ci_framework/roles/idrac_configuration/tasks/clear_job_inventory.yml
  ci_framework/roles/idrac_configuration/tasks/clear_pending_configuration.yml
  ci_framework/roles/idrac_configuration/tasks/configure_bios.yml
  ci_framework/roles/idrac_configuration/tasks/healthcheck.yml
  ci_framework/roles/idrac_configuration/tasks/main.yml
  ci_framework/roles/idrac_configuration/tasks/power_action.yml
  ci_framework/roles/idrac_configuration/tasks/query.yml
  ci_framework/roles/idrac_configuration/tasks/racreset.yml
  ci_framework/roles/idrac_configuration/tasks/retrieve_idrac_jobs.yml
  ci_framework/roles/idrac_configuration/tasks/wait_for_running_jobs.yml
  ci_framework/roles/idrac_configuration/vars/main.yml
  docs/dictionary/en-custom.txt
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#931 Add gateway field to the Networking Definition parsing logic
  ci_framework/plugins/module_utils/net_map/networking_definition.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_instance.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_network.py
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack.yml
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only.yml
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid.yml
Labels: approved, lgtm

#933 Add Networking Environment Definition types
  ci_framework/plugins/module_utils/net_map/networking_env_definitions.py
Labels: approved, lgtm

#938 Add jq package the reproducer role to be installed in controller-0
  ci_framework/roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#804 Add switch config role from ansible NFV
  ci_framework/hooks/playbooks/switch_config.yml
  ci_framework/roles/switch_config/README.md
  ci_framework/roles/switch_config/defaults/main.yml
  ci_framework/roles/switch_config/molecule/default/converge.yml
  ci_framework/roles/switch_config/molecule/default/molecule.yml
  ci_framework/roles/switch_config/tasks/ios_config.yml
  ci_framework/roles/switch_config/tasks/junos_config.yml
  ci_framework/roles/switch_config/tasks/main.yml
  ci_framework/roles/switch_config/tasks/onyx_config.yml
  docs/dictionary/en-custom.txt
  requirements.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, ok-to-test

#936 Patch BM nodeset to update all packages during bootstrap phase
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#948 Fix the kinit command syntax in dlrn promote role
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm

#935 Use proper periodic repos in periodic jobs
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#951 Add missing `become: true`
  reproducer.yml
Labels: approved, lgtm

#949 Ensure we clean ssh config entries
  ci_framework/roles/libvirt_manager/tasks/clean_layout.yml
Labels: approved, lgtm

#944 Initialise NodeSet /spec/env
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#868 Add support for openstack-must-gather container building
  ci_framework/roles/os_must_gather/README.md
  ci_framework/roles/os_must_gather/defaults/main.yml
  ci_framework/roles/os_must_gather/tasks/build_openstack-must-gather_image.yml
  ci_framework/roles/os_must_gather/tasks/main.yml
  zuul.d/base.yaml
Labels: approved, lgtm

#939 Support reusing of deployed OCP cluster.
  ci_framework/roles/devscripts/tasks/00_pre_check.yml
  ci_framework/roles/devscripts/tasks/main.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/53_add_bmh.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_add_node.yml
Labels: approved, lgtm

#852 Add edpm_sshd_allowed_ranges variable
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#947 [ci_kustomize]Allow loading non local files
  ci_framework/plugins/action/ci_kustomize.py
Labels: approved, lgtm

#940 Manage ssh key as secrets
  ci/config/molecule.yaml
  ci_framework/roles/manage_secrets/README.md
  ci_framework/roles/manage_secrets/defaults/main.yml
  ci_framework/roles/manage_secrets/molecule/dataplane_ssh/cleanup.yml
  ci_framework/roles/manage_secrets/molecule/dataplane_ssh/converge.yml
  ci_framework/roles/manage_secrets/molecule/dataplane_ssh/molecule.yml
  ci_framework/roles/manage_secrets/molecule/dataplane_ssh/prepare.yml
  ci_framework/roles/manage_secrets/molecule/nova_migration/cleanup.yml
  ci_framework/roles/manage_secrets/molecule/nova_migration/converge.yml
  ci_framework/roles/manage_secrets/molecule/nova_migration/molecule.yml
  ci_framework/roles/manage_secrets/molecule/nova_migration/prepare.yml
  ci_framework/roles/manage_secrets/tasks/dataplane_ssh.yml
  ci_framework/roles/manage_secrets/tasks/nova_migration.yml
  docs/dictionary/en-custom.txt
  zuul.d/molecule.yaml
Labels: approved, lgtm

#946 Revert "Patch BM nodeset to update all packages during bootstrap phase"
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#962 Skip manila tempest test
  ci_framework/roles/tempest/files/list_skipped.yml
Labels: approved, lgtm

#965 [networking_mapping] Add DNS field to the networking definition.
  ci_framework/plugins/module_utils/net_map/networking_definition.py
  ci_framework/tests/unit/module_utils/net_map/test_networking_definitions_network.py
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack.yml
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only.yml
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid.yml
Labels: approved, lgtm

#964 [edpm_deploy]Fix a bug when cifmw_edpm_deploy_env is undefined
  ci_framework/roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#967 [networking_mapping] Add search-domain to the network definition
  plugins/module_utils/net_map/networking_definition.py
  tests/unit/module_utils/net_map/test_networking_definitions_network.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack.yml
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only.yml
  tests/unit/module_utils/test_files/networking-definition-valid.yml
Labels: approved, lgtm

#934 Add `ci_netconfig` role
  ci/config/molecule.yaml
  docs/dictionary/en-custom.txt
  roles/ci_netconfig/README.md
  roles/ci_netconfig/defaults/main.yml
  roles/ci_netconfig/meta/main.yml
  roles/ci_netconfig/molecule/default/converge.yml
  roles/ci_netconfig/molecule/default/molecule.yml
  roles/ci_netconfig/molecule/default/prepare.yml
  roles/ci_netconfig/tasks/cleanup.yml
  roles/ci_netconfig/tasks/main.yml
  roles/ci_netconfig/templates/netconfig.yml.j2
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#937 Module utils/ansible encoding
  plugins/action/ci_kustomize.py
  plugins/action/ci_make.py
  plugins/action/ci_script.py
  plugins/action/discover_latest_image.py
  plugins/module_utils/encoding/__init__.py
  plugins/module_utils/encoding/ansible_encoding.py
Labels: approved, lgtm

#955 Updating hosts so that the task runs on both controller and primary nodes
  ci/playbooks/dump_zuul_data.yml
  ci/playbooks/e2e-prepare.yml
Labels: approved, lgtm

#968 Allow jobs to set tempest container name
  roles/tempest/README.md
  roles/tempest/defaults/main.yml
  scenarios/centos-9/ceph_backends.yml
  scenarios/centos-9/edpm_periodic.yml
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#970 Reconfig molecule tests include files
  ci/templates/molecule.yaml.j2
  scripts/create_role_molecule.py
  scripts/tests/test_create_role_molecule.py
  zuul.d/molecule.yaml
Labels: approved, lgtm

#957 Remove molecule dir from sw role
  roles/switch_config/molecule/default/converge.yml
  roles/switch_config/molecule/default/molecule.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, needs-ok-to-test

#963 Ensure inventory supports multi-hypervisor
  ansible.cfg
  roles/libvirt_manager/tasks/clean_layout.yml
  roles/libvirt_manager/templates/all-inventory.yml.j2
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#966 Revert "Skip manila tempest test"
  roles/tempest/files/list_skipped.yml
Labels: approved, lgtm

#922 Add ci_local_storage role
  ci/config/molecule.yaml
  docs/dictionary/en-custom.txt
  roles/ci_local_storage/README.md
  roles/ci_local_storage/defaults/main.yml
  roles/ci_local_storage/meta/main.yml
  roles/ci_local_storage/molecule/default/converge.yml
  roles/ci_local_storage/molecule/default/molecule.yml
  roles/ci_local_storage/molecule/default/prepare.yml
  roles/ci_local_storage/tasks/cleanup.yml
  roles/ci_local_storage/tasks/main.yml
  roles/ci_local_storage/tasks/worker_node_dirs.yml
  roles/ci_local_storage/templates/storage.yaml.j2
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#843 Gather additional namespaces when must-gather is executed
  roles/os_must_gather/README.md
  roles/os_must_gather/defaults/main.yml
  roles/os_must_gather/tasks/main.yml
Labels: approved, lgtm

#973 Add defaults for dashboard container image params
  roles/cifmw_cephadm/defaults/main.yml
Labels: approved, lgtm, ok-to-test

#977 [libvirt_manager] Rely on `community.crypto.openssh_keypair` for temporary keypair generation
  requirements.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
Labels: approved, lgtm

#979 Move Roberto to approver
  OWNERS
Labels: approved, lgtm

#978 Add new cifwm base job for ci-bootstrap layout
  zuul.d/base.yaml
Labels: approved, lgtm

#980 Remove references to requirements files deleted
  ci/templates/molecule.yaml.j2
  roles/reproducer/tasks/configure_controller.yml
  scripts/tests/test_create_role_molecule.py
  zuul.d/molecule.yaml
Labels: approved, lgtm

#446 Add zuul based ironic tempest tests
  hooks/playbooks/control_plane_ironic.yml
  roles/tempest/files/list_allowed.yml
  roles/tempest/files/list_skipped.yml
  scenarios/centos-9/ironic.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#982 Run crc cleanup only when crc binary exists
  roles/rhol_crc/tasks/cleanup.yml
Labels: approved, lgtm

#882 Set default network vals on the base job
  zuul.d/adoption.yaml
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
  zuul.d/kuttl_multinode.yaml
  zuul.d/tempest_multinode.yaml
Labels: approved, lgtm

#960 Add simple mapping of networks
  plugins/module_utils/net_map/networking_env_definitions.py
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/net_map/test_networking_definitions_all.py
  tests/unit/module_utils/net_map/test_networking_mapper.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-networks-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-networks-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-networks-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools.yml
  tests/unit/module_utils/test_files/networking-definition-valid-network-template.yml
  tests/unit/module_utils/test_files/networking-definition-valid-networks-out.json
  tests/unit/module_utils/test_files/networking-definition-valid.yml
  tests/unit/module_utils/test_utils/net_map_stub_data.py
Labels: approved, lgtm

#985 Add playbooks and job definition for ci-bootstrap jobs
  ci/playbooks/crc/reconfigure-kubelet.yml
  ci/playbooks/multinode-customizations.yml
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#987 [networking_mapper] Fix default handling of skip NM flag.
  plugins/module_utils/net_map/networking_definition.py
  tests/unit/module_utils/net_map/test_networking_definitions_all.py
  tests/unit/module_utils/net_map/test_networking_definitions_group_template.py
  tests/unit/module_utils/net_map/test_networking_definitions_instance.py
Labels: approved, lgtm

#851 [networking_mapping] Add instances mapping logic
  plugins/module_utils/net_map/networking_env_definitions.py
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/net_map/test_networking_definitions_all.py
  tests/unit/module_utils/net_map/test_networking_mapper.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack.yml
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only.yml
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools.yml
  tests/unit/module_utils/test_files/networking-definition-valid-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid.yml
  tests/unit/module_utils/test_utils/net_map_stub_data.py
Labels: approved, lgtm

#990 Install gcc for dlrn reporting
  roles/dlrn_report/tasks/install.yml
Labels: approved, lgtm

#986 [manage_secrets] Implement OSP secrets management
  roles/manage_secrets/README.md
  roles/manage_secrets/defaults/main.yml
  roles/manage_secrets/molecule/osp_secrets/cleanup.yml
  roles/manage_secrets/molecule/osp_secrets/converge.yml
  roles/manage_secrets/molecule/osp_secrets/molecule.yml
  roles/manage_secrets/molecule/osp_secrets/prepare.yml
  roles/manage_secrets/tasks/osp_secrets.yml
  roles/manage_secrets/templates/osp_secrets.yml.j2
Labels: approved, lgtm

#981 Add retry & delay while creating dirs on worker node
  roles/ci_local_storage/tasks/worker_node_dirs.yml
Labels: approved, lgtm
