Repository openstack-k8s-operators/ci-framework, pull requests merged in 2023-07, with the labels that each got.

#346 Deploy metallb for DNS in baremetal job
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
  ci_framework/roles/install_yamls/defaults/main.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: lgtm

#324 Add support for passing custom uefi image
  ci_framework/roles/edpm_deploy_baremetal/README.md
  ci_framework/roles/edpm_deploy_baremetal/defaults/main.yml
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#350 Set proper image element files based on distro
  ci_framework/roles/edpm_build_images/tasks/run.yml
Labels: approved, lgtm

#352 Fix job/role content after make role_molecule
  ci/templates/projects.yaml
  docs/source/roles/edpm_build_images.md
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#356 Drop quote from delorean.repo.md5 content
  ci_framework/roles/repo_setup/tasks/artifacts.yml
Labels: approved, lgtm

#358 Add a new tag we can then filter on
  ci/playbooks/edpm_build_images/edpm_image_builder.yml
  ci/playbooks/edpm_build_images/run.yml
Labels: approved, lgtm

#360 Remove openstack_ci_bootstrap as it will not used now.
  ci_framework/roles/openstack_ci_bootstrap/README.md
  ci_framework/roles/openstack_ci_bootstrap/defaults/main.yml
  ci_framework/roles/openstack_ci_bootstrap/meta/main.yml
  ci_framework/roles/openstack_ci_bootstrap/molecule/default/converge.yml
  ci_framework/roles/openstack_ci_bootstrap/molecule/default/molecule.yml
  ci_framework/roles/openstack_ci_bootstrap/molecule/default/prepare.yml
  ci_framework/roles/openstack_ci_bootstrap/tasks/cleanup.yml
  ci_framework/roles/openstack_ci_bootstrap/tasks/create_instance.yml
  ci_framework/roles/openstack_ci_bootstrap/tasks/main.yml
  ci_framework/roles/openstack_ci_bootstrap/tasks/network_setup.yml
  ci_framework/roles/openstack_ci_bootstrap/vars/main.yml
  docs/source/roles/openstack_ci_bootstrap.md
Labels: approved, lgtm

#319 Role to set meta operators env variables
  ci_framework/roles/edpm_prepare/README.md
  ci_framework/roles/edpm_prepare/defaults/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/set_openstack_containers/README.md
  ci_framework/roles/set_openstack_containers/defaults/main.yml
  ci_framework/roles/set_openstack_containers/meta/main.yml
  ci_framework/roles/set_openstack_containers/molecule/default/converge.yml
  ci_framework/roles/set_openstack_containers/molecule/default/molecule.yml
  ci_framework/roles/set_openstack_containers/molecule/default/prepare.yml
  ci_framework/roles/set_openstack_containers/tasks/main.yml
  ci_framework/roles/set_openstack_containers/templates/update_env_vars.sh.j2
  docs/source/roles/set_openstack_containers.md
  scripts/create_role_molecule
  zuul.d/molecule-base.yaml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Feature

#355 Udpate openstack_containers in periodic lines
  scenarios/centos-9/edpm_periodic.yml
  zuul.d/edpm_periodic.yaml
Labels: approved, lgtm

#347 edpm_build_images periodic job
  ci/playbooks/edpm_build_images/edpm_image_builder.yml
  ci_framework/roles/edpm_build_images/README.md
  ci_framework/roles/edpm_build_images/defaults/main.yml
  ci_framework/roles/edpm_build_images/tasks/main.yml
  ci_framework/roles/edpm_build_images/tasks/post.yaml
  zuul.d/edpm_build_images.yaml
  zuul.d/edpm_periodic.yaml
Labels: approved, lgtm

#364 Iterate over containers_overrides keys not items
  ci_framework/roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm

#366 Drop `Patch CSV for ansible runner image` task
  ci_framework/roles/edpm_prepare/defaults/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
Labels: approved, lgtm

#368 Add simple tox target for testing from Prow CI
  Makefile
  test-requirements.txt
Labels: approved, lgtm

#363 Enable Network isolation in baremetal job
  ci/playbooks/edpm_baremetal_deployment/run.yml
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
  docs/source/usage/01_usage.md
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  zuul.d/edpm.yaml
Labels: lgtm

#367 Reload generated environment
  ci_framework/roles/artifacts/tasks/cluster_info.yml
Labels: approved, lgtm

#365 Create EDPM vm when deploy_edpm is set to true
  ci_framework/playbooks/06-deploy-edpm.yml
Labels: approved, lgtm

#375 Use edpm-builder-image rpm for periodic jobs
  ci_framework/roles/edpm_build_images/tasks/package.yml
  zuul.d/edpm_build_images.yaml
Labels: approved, lgtm

#373 Ignore computes deployment when cifmw_use_libvirt is false
  ci_framework/playbooks/06-deploy-edpm.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved

#340 Porting create_role_molecule script to Python
  Makefile
  ci/config/molecule.yaml
  ci/templates/molecule.yaml
  ci/templates/molecule.yaml.j2
  docs/source/development/02_molecule.md
  scripts/__init__.py
  scripts/create_role_molecule
  scripts/create_role_molecule.py
  scripts/tests/test_create_role_molecule.py
  tox.ini
Labels: enhancement, approved, lgtm

#371 Provide a way to add certs with in the image
  ci_framework/roles/edpm_build_images/README.md
  ci_framework/roles/edpm_build_images/defaults/main.yml
  ci_framework/roles/edpm_build_images/tasks/add_cert.yml
  ci_framework/roles/edpm_build_images/tasks/main.yml
Labels: approved, lgtm

#374 Add galera based podified job
  ci/templates/projects.yaml
  zuul.d/edpm.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#370 Gather logs from standalone CRC over network
  ci_framework/roles/artifacts/README.md
  ci_framework/roles/artifacts/defaults/main.yml
  ci_framework/roles/artifacts/tasks/crc.yml
  ci_framework/roles/artifacts/tasks/main.yml
  ci_framework/roles/artifacts/vars/main.yml
Labels: approved, lgtm

#377 Fixing incosistencies an removing unused flags
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/roles/edpm_prepare/README.md
  ci_framework/roles/edpm_prepare/defaults/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  docs/source/usage/01_usage.md
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#378 Some cleaning in ansible
  ci_framework/roles/ci_setup/tasks/directories.yml
  ci_framework/roles/edpm_build_images/README.md
  ci_framework/roles/edpm_build_images/defaults/main.yml
  ci_framework/roles/install_yamls/tasks/main.yml
Labels: approved, lgtm

#372 Use set_openstack_containers role to patch baremetal operator
  ci_framework/roles/edpm_deploy_baremetal/README.md
  ci_framework/roles/edpm_deploy_baremetal/defaults/main.yml
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
  ci_framework/roles/set_openstack_containers/tasks/main.yml
  ci_framework/roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm

#359 Add os_must_gather role
  ci_framework/playbooks/99-logs.yml
  ci_framework/roles/artifacts/tasks/cluster_info.yml
  ci_framework/roles/artifacts/tasks/main.yml
  ci_framework/roles/os_must_gather/README.md
  ci_framework/roles/os_must_gather/defaults/main.yml
  ci_framework/roles/os_must_gather/meta/main.yml
  ci_framework/roles/os_must_gather/molecule/default/converge.yml
  ci_framework/roles/os_must_gather/molecule/default/molecule.yml
  ci_framework/roles/os_must_gather/molecule/default/prepare.yml
  ci_framework/roles/os_must_gather/tasks/main.yml
  docs/source/roles/os_must_gather.md
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Feature

#332 Improvement to tempest role
  ci_framework/playbooks/08-run-tests.yml
  ci_framework/roles/tempest/README.md
  ci_framework/roles/tempest/defaults/main.yml
  ci_framework/roles/tempest/tasks/main.yml
  zuul.d/end-to-end.yaml
Labels: enhancement, approved, lgtm

#380 PoC for ci_script implementation
  ci_framework/roles/copy_container/tasks/main.yml
Labels: approved, lgtm

#384 Build ansibleee runner image in ci-framework base job
  ci/playbooks/build_runner_image.yml
  ci/playbooks/e2e-prepare.yml
  ci/playbooks/edpm/run.yml
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#387 Ensure we export needed environment in the script
  ci_framework/roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm

#388 Adding chdir option to the ci_script module
  ci_framework/plugins/action/ci_script.py
  ci_framework/tests/integration/targets/script/tasks/main.yml
Labels: approved

#389 Ensure we pass needed environment in edpm_deploy
  ci_framework/roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#391 Added missing namespaces in os_must_gather role
  ci_framework/roles/os_must_gather/tasks/main.yml
Labels: approved, lgtm

#390 Store edpm-ansible scenario file in artifacts directory.
  ci/playbooks/build_runner_image.yml
  ci/playbooks/edpm/run.yml
Labels: approved, lgtm

#382 Added detailed usage doc for set_openstack_containers role
  ci_framework/roles/set_openstack_containers/README.md
Labels: approved, lgtm

#394 Correct some details on the log gathering
  ci/playbooks/e2e-collect-logs.yml
  ci_framework/roles/artifacts/tasks/crc.yml
Labels: approved, lgtm

#369 Ensure we're running the hook against localhost only
  ci_framework/roles/run_hook/README.md
  ci_framework/roles/run_hook/tasks/playbook.yml
  scenarios/centos-9/ci.yml
Labels: approved, lgtm

#398 Set default value for registry_login_enabled
  ci/playbooks/e2e-prepare.yml
Labels: approved, lgtm

#383 Enabling tempest role to use variables to allowed and skipped tests
  ci_framework/roles/tempest/README.md
  ci_framework/roles/tempest/tasks/tempest-tests.yml
Labels: approved, lgtm

#397 Remove dependency to community.libvirt from artifacts role
  ci_framework/roles/artifacts/tasks/crc.yml
  ci_framework/roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#400 Correct ci_script call
  ci_framework/roles/copy_container/tasks/main.yml
Labels: approved, lgtm

#392 Use ci_script instead of shell in edpm_deploy role
  ci_framework/roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#396 Add script and makefile entry for cleaning up local virtualized environment
  Makefile
  docs/source/quickstart/02_nested_virt.md
  scripts/local_env_vm_cleanup.sh
Labels: approved, lgtm, ok-to-test

#405 Be explicit with ssh key permissions
  ci_framework/roles/local_env_vm/tasks/main.yml
Labels: approved, lgtm, ok-to-test

#406 Set qemu permissions on home directory
  ci_framework/roles/local_env_vm/tasks/main.yml
Labels: approved, lgtm, ok-to-test

#256 Create build_containers role
  ci_framework/roles/build_containers/README.md
  ci_framework/roles/build_containers/defaults/main.yml
  ci_framework/roles/build_containers/meta/main.yml
  ci_framework/roles/build_containers/molecule/default/converge.yml
  ci_framework/roles/build_containers/molecule/default/molecule.yml
  ci_framework/roles/build_containers/molecule/default/prepare.yml
  ci_framework/roles/build_containers/tasks/install.yml
  ci_framework/roles/build_containers/tasks/main.yml
  ci_framework/roles/build_containers/templates/build_containers.sh.j2
  docs/source/roles/build_containers.md
Labels: approved, lgtm, Feature

#411 Add new reviewer member
  OWNERS
Labels: approved, lgtm

#409 Set edpm-ansible.yml var file if file exists
  ci/playbooks/edpm/run.yml
Labels: approved, lgtm

#410 Rename cifmw_repo_setup_opts to cifmw_repo_setup_additional_repos
  ci_framework/roles/repo_setup/README.md
  ci_framework/roles/repo_setup/defaults/main.yml
  ci_framework/roles/repo_setup/tasks/configure.yml
  ci_framework/roles/test_deps/tasks/main.yml
Labels: approved, lgtm

#401 Fix generation of zuul projects.yaml
  ci/config/molecule.yaml
  scripts/create_role_molecule.py
  scripts/tests/test_create_role_molecule.py
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#412 Add some irrelevant files
  zuul.d/content_provider.yaml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#413 Set edpm-ansible.yml var file for bm jobs
  ci/playbooks/edpm_baremetal_deployment/run.yml
Labels: approved, lgtm

#408 Get spellcheck workflow
  .github/workflows/pyspell.yml
  .spellcheck.yml
  CONTRIBUTING.md
  README.md
  ci_framework/roles/libvirt_manager/README.md
  ci_framework/roles/openshift_login/README.md
  ci_framework/roles/polarion/README.md
  ci_framework/roles/run_hook/README.md
  docs/dictionary/en-custom.txt
  docs/source/internals/02_testing.md
Labels: approved, lgtm

#416 Skip zuul jobs for update in .github directory
  zuul.d/content_provider.yaml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#415 Add some more doc about pySpelling installation
  .spellcheck.yml
  docs/dictionary/en-custom.txt
  docs/source/internals/02_testing.md
Labels: approved, lgtm

#285 Added tcib base job
  ci/playbooks/tcib/run.yml
  ci/playbooks/tcib/tcib.yml
  ci/templates/projects.yaml
  ci_framework/roles/build_containers/defaults/main.yml
  ci_framework/roles/build_containers/molecule/default/converge.yml
  ci_framework/roles/build_containers/molecule/default/prepare.yml
  ci_framework/roles/build_containers/tasks/cleanup.yml
  ci_framework/roles/build_containers/tasks/main.yml
  ci_framework/roles/copy_container/files/copy-quay/utils.go
  ci_framework/roles/repo_setup/defaults/main.yml
  scenarios/centos-9/tcib.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
  zuul.d/tcib.yaml
Labels: approved, lgtm, ok-to-test, Feature

#418 Fixed the spellcheck for newly added roles
  ci_framework/roles/cifmw_ceph_spec/README.md
  ci_framework/roles/cifmw_cephadm/README.md
  ci_framework/roles/cifmw_create_admin/README.md
  docs/dictionary/en-custom.txt
Labels: approved, lgtm
