Repository openstack-k8s-operators/ci-framework, pull requests merged in 2023-11, with the labels that each got.

#748 Ensure we don't add network port multiple times
  ci_framework/roles/libvirt_manager/tasks/attach_interface.yml
Labels: approved, lgtm

#749 Allow to reserve/fix IPs for VM managed by libvirt_manager
  ci_framework/roles/libvirt_manager/tasks/create_vms.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_layout.yml
  ci_framework/roles/libvirt_manager/tasks/reserve_ip.yml
Labels: approved, lgtm

#759 Fix dataplane repo-setup injection to not overwrite bootstrap
  ci_framework/roles/deploy_va_tmp/tasks/deploy-dataplane.yml
Labels: lgtm

#757 Update default preset to openshift
  ci/config/molecule.yaml
  ci_framework/roles/rhol_crc/molecule/add_crc_creds/cleanup.yml
  ci_framework/roles/rhol_crc/molecule/add_crc_creds/converge.yml
  ci_framework/roles/rhol_crc/molecule/add_crc_creds/prepare.yml
  ci_framework/roles/rhol_crc/molecule/default/cleanup.yml
  ci_framework/roles/rhol_crc/molecule/default/converge.yml
  ci_framework/roles/rhol_crc/molecule/default/prepare.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/cleanup.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/converge.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/prepare.yml
  ci_framework/roles/rhol_crc/vars/main.yml
  zuul.d/molecule.yaml
Labels: approved, lgtm

#764 Ignore operator related images
  ci_framework/roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm

#752 Support hybrid test environment
  ci_framework/roles/devscripts/tasks/03_install.yml
  ci_framework/roles/devscripts/tasks/04_post.yml
  ci_framework/roles/devscripts/tasks/cleanup.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/31_repo.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/32_params.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/42_networking.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/43_add_bmh.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_421_gather.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_422_create.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_423_attach.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_424_firewall.yml
Labels: approved, lgtm

#769 Optimize a bit Ansible configuration for SSH
  ansible.cfg
Labels: approved, lgtm

#776 Drop current tags from install_ca role
  ci_framework/roles/install_ca/tasks/main.yml
Labels: approved, lgtm

#756 Correct Layout reproducer
  ci_framework/roles/reproducer/tasks/main.yml
  ci_framework/roles/rhol_crc/tasks/binary.yml
  ci_framework/roles/rhol_crc/tasks/undefine.yml
  docs/source/reproducers/01-considerations.md
  scenarios/reproducers/3-nodes.yml
Labels: approved, lgtm

#771 Install tcib from RPM
  ci/playbooks/tcib/tcib.yml
  ci_framework/roles/build_containers/README.md
  ci_framework/roles/build_containers/defaults/main.yml
  ci_framework/roles/build_containers/molecule/default/converge.yml
  ci_framework/roles/build_containers/tasks/install.yml
Labels: approved, lgtm

#714 Introduce cifmw_cephadm_ceph_spec_fqdn
  ci_framework/roles/cifmw_cephadm/README.md
  ci_framework/roles/cifmw_cephadm/defaults/main.yml
  ci_framework/roles/cifmw_cephadm/tasks/rgw.yml
  ci_framework/roles/hci_prepare/templates/dpservice-nova-custom-ceph.yml.j2
Labels: approved, lgtm

#766 Allow overlay support in devscripts role
  ci_framework/roles/devscripts/README.md
  ci_framework/roles/devscripts/defaults/main.yml
  ci_framework/roles/devscripts/tasks/04_overlays.yml
  ci_framework/roles/devscripts/tasks/05_post.yml
  ci_framework/roles/devscripts/tasks/main.yml
Labels: approved, lgtm

#767 Support custom XML and multiple base image for overlays
  ci_framework/roles/libvirt_manager/tasks/attach_interface.yml
  ci_framework/roles/libvirt_manager/tasks/clean_layout.yml
  ci_framework/roles/libvirt_manager/tasks/create_vms.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_layout.yml
  ci_framework/roles/libvirt_manager/tasks/reserve_ip.yml
  ci_framework/roles/libvirt_manager/templates/domain.xml.j2
  ci_framework/roles/libvirt_manager/vars/main.yml
Labels: approved, lgtm

#754 Import compute hook update in dev-preview2
  ci/playbooks/collect-logs.yml
  ci/playbooks/content_provider/run.yml
  ci/playbooks/dev-workflow.yml
  ci/playbooks/dump_zuul_data.yml
  ci/playbooks/dump_zuul_vars.yml
  ci/playbooks/e2e-run.yml
  ci/playbooks/edpm/run.yml
  ci/playbooks/edpm_baremetal_deployment/run.yml
  ci/playbooks/edpm_build_images/edpm_build_images_content_provider_run.yaml
  ci/playbooks/edpm_build_images/edpm_image_builder.yml
  ci/playbooks/edpm_build_images/run.yml
  ci/playbooks/kuttl/run.yml
  ci/playbooks/multinode-customizations.yml
  ci/playbooks/tcib/run.yml
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
  ci_framework/playbooks/01-bootstrap.yml
  zuul.d/adoption.yaml
  zuul.d/base.yaml
  zuul.d/edpm_build_images.yaml
  zuul.d/edpm_build_images_content_provider.yaml
  zuul.d/end-to-end.yaml
  zuul.d/kuttl.yaml
  zuul.d/kuttl_multinode.yaml
  zuul.d/tcib.yaml
Labels: approved, lgtm

#779 Refactor reproducer role
  ci_framework/roles/reproducer/tasks/ci_data.yml
  ci_framework/roles/reproducer/tasks/ci_job.yml
  ci_framework/roles/reproducer/tasks/cleanup.yml
  ci_framework/roles/reproducer/tasks/libvirt_layout.yml
  ci_framework/roles/reproducer/tasks/main.yml
  ci_framework/roles/reproducer/tasks/push_code.yml
Labels: approved, lgtm

#780 Allow auth file to be null
  ci_framework/roles/build_containers/README.md
  ci_framework/roles/build_containers/tasks/main.yml
  ci_framework/roles/build_containers/templates/build_containers.sh.j2
Labels: approved, lgtm, ok-to-test

#775 Add data-plane adoption job to ci-framework PRs
  ci/templates/projects.yaml
  zuul.d/adoption.yaml
  zuul.d/project-templates.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#768 Avoid warning the user about oc not found
  ci_framework/roles/ci_setup/README.md
  ci_framework/roles/ci_setup/defaults/main.yml
  ci_framework/roles/ci_setup/tasks/packages.yml
  ci_framework/roles/ci_setup/vars/main.yml
Labels: approved, lgtm

#778 Run must gather in adoption job if tests fail
  zuul.d/adoption.yaml
Labels: approved, lgtm

#783 Append `-` in the container prefix name
  ci_framework/roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm

#787 Fix kuttl playbook order
  ci/playbooks/kuttl/e2e-kuttl.yml
Labels: approved, lgtm

#785 Configure insecure registry on EDPM nodes
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#784 Better service management for libvirt components
  ci_framework/roles/libvirt_manager/tasks/virsh_checks.yml
Labels: approved, lgtm

#788 Fix kuttl playbook order
  ci/playbooks/kuttl/e2e-kuttl.yml
Labels: approved

#789 Add tempest.api.network.admin.test_dhcp_agent_scheduler test to skip …
  ci_framework/roles/tempest/files/list_skipped.yml
Labels: approved, lgtm

#790 Add tempest.api.network.admin.test_dhcp_agent_scheduler test to skip …
  ci_framework/roles/tempest/files/list_skipped.yml
Labels: approved, lgtm

#770 Fix: address failures occurring during attach interface.
  ci_framework/roles/devscripts/tasks/04_overlays.yml
  ci_framework/roles/devscripts/tasks/05_post.yml
  ci_framework/roles/devscripts/tasks/cleanup.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/51_set_facts.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/52_networking.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/53_add_bmh.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_521_gather.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_522_create.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_523_attach.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/_524_firewall.yml
  ci_framework/roles/libvirt_manager/README.md
  ci_framework/roles/libvirt_manager/defaults/main.yml
  ci_framework/roles/libvirt_manager/tasks/attach_interface.yml
  ci_framework/roles/libvirt_manager/tasks/create_networks.yml
  ci_framework/roles/libvirt_manager/tasks/reserve_ip.yml
Labels: approved, lgtm

#793 Fix Baremetal EDPM logging
  ci_framework/roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm

#786 Fix libvirt_manager and reproducer roles
  ci_framework/roles/libvirt_manager/README.md
  ci_framework/roles/libvirt_manager/defaults/main.yml
  ci_framework/roles/libvirt_manager/molecule/default/converge.yml
  ci_framework/roles/libvirt_manager/molecule/default/prepare.yml
  ci_framework/roles/libvirt_manager/molecule/deploy_layout/converge.yml
  ci_framework/roles/libvirt_manager/molecule/deploy_layout/molecule.yml
  ci_framework/roles/libvirt_manager/molecule/deploy_layout/prepare.yml
  ci_framework/roles/libvirt_manager/molecule/extra_computes/molecule.yml
  ci_framework/roles/libvirt_manager/molecule/extra_computes/prepare.yml
  ci_framework/roles/libvirt_manager/tasks/create_vms.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_layout.yml
  ci_framework/roles/libvirt_manager/tasks/get_image.yml
  ci_framework/roles/libvirt_manager/tasks/main.yml
  ci_framework/roles/libvirt_manager/templates/all-inventory.yml.j2
  ci_framework/roles/libvirt_manager/templates/ci-network-data.yml.j2
  ci_framework/roles/libvirt_manager/templates/domain.xml.j2
  ci_framework/roles/libvirt_manager/templates/inventory.yml.j2
  ci_framework/roles/libvirt_manager/templates/network-data.yml.j2
  ci_framework/roles/reproducer/tasks/libvirt_layout.yml
  ci_framework/roles/reproducer/tasks/main.yml
  scenarios/reproducers/3-nodes.yml
Labels: approved, lgtm

#781 Pass debug and create by default to tempestconf
  ci_framework/roles/tempest/vars/main.yml
Labels: approved, lgtm

#782 Remove virt-net default only when requested
  ci_framework/roles/devscripts/README.md
  ci_framework/roles/devscripts/defaults/main.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/13_network.yml
Labels: approved, lgtm

#794 Doc hypervisor type fixes
  docs/source/quickstart/02_nested_virt.md
  docs/source/quickstart/03_psi.md
  docs/source/quickstart/99_FAQ.md
Labels: approved, lgtm, ok-to-test

#792 Use kustomize add operation for setting insecure registry
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
  zuul.d/tcib.yaml
Labels: approved, lgtm

#795 Get actual test for reproducer role
  ci/config/molecule.yaml
  ci_framework/roles/libvirt_manager/tasks/create_vms.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_layout.yml
  ci_framework/roles/reproducer/molecule/crc_layout/converge.yml
  ci_framework/roles/reproducer/molecule/crc_layout/molecule.yml
  ci_framework/roles/reproducer/molecule/crc_layout/prepare.yml
  ci_framework/roles/reproducer/tasks/libvirt_layout.yml
  ci_framework/roles/reproducer/tasks/main.yml
  reproducer.yml
  zuul.d/molecule.yaml
Labels: approved, lgtm

#797 Remove the namespace in the NMstate resources as is cluster wide
  ci_framework/roles/ci_nmstate/defaults/main.yml
Labels: approved, lgtm

#798 Fix the SSH proxy hostname used in the localhost controller
  ci_framework/roles/libvirt_manager/tasks/create_vms.yml
Labels: approved, lgtm

#796 Integrate devscripts layout support in reproducer role
  ci_framework/roles/ci_setup/README.md
  ci_framework/roles/ci_setup/defaults/main.yml
  ci_framework/roles/ci_setup/tasks/epel.yml
  ci_framework/roles/libvirt_manager/templates/all-inventory.yml.j2
  ci_framework/roles/reproducer/README.md
  ci_framework/roles/reproducer/defaults/main.yml
  ci_framework/roles/reproducer/files/pre-ci-play.yml
  ci_framework/roles/reproducer/tasks/ci_job.yml
  ci_framework/roles/reproducer/tasks/configure_controller.yml
  ci_framework/roles/reproducer/tasks/configure_crc.yml
  ci_framework/roles/reproducer/tasks/crc_layout.yml
  ci_framework/roles/reproducer/tasks/devscripts_layout.yml
  ci_framework/roles/reproducer/tasks/devscripts_post.yml
  ci_framework/roles/reproducer/tasks/libvirt_layout.yml
  ci_framework/roles/reproducer/tasks/main.yml
  ci_framework/roles/reproducer/tasks/push_code.yml
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  reproducer.yml
Labels: approved, lgtm

#800 Avoid copying repositories generated by repo-setup
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#805 Rename NTP variable
  ci_framework/tests/integration/targets/make/files/get_makefiles_env/expected_variables_values.yml
  ci_framework/tests/integration/targets/make/files/get_makefiles_env/makefiles/Makefile
  ci_framework/tests/integration/targets/make/files/get_makefiles_env/makefiles/subdir/Makefile
  docs/source/quickstart/99_FAQ.md
Labels: approved, lgtm

#801 Do not code any NIC related data in domain XML
  ci_framework/roles/libvirt_manager/molecule/deploy_layout/converge.yml
  ci_framework/roles/libvirt_manager/tasks/attach_interface.yml
  ci_framework/roles/libvirt_manager/tasks/create_vms.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_layout.yml
  ci_framework/roles/libvirt_manager/tasks/net_to_vms.yml
  ci_framework/roles/libvirt_manager/tasks/reserve_ip.yml
  ci_framework/roles/libvirt_manager/templates/domain.xml.j2
  ci_framework/roles/libvirt_manager/templates/network-data.yml.j2
  ci_framework/roles/reproducer/defaults/main.yml
  ci_framework/roles/reproducer/molecule/crc_layout/converge.yml
  ci_framework/roles/reproducer/tasks/configure_crc.yml
  scenarios/reproducers/3-nodes.yml
Labels: approved, lgtm

#806 Validated Architecture concept integration
  ci_framework/roles/ci_setup/vars/main.yml
  ci_framework/roles/ci_setup/vars/redhat.yml
  ci_framework/roles/libvirt_manager/templates/inventory.yml.j2
  ci_framework/roles/reproducer/tasks/configure_controller.yml
  ci_framework/roles/reproducer/tasks/devscripts_layout.yml
  ci_framework/roles/reproducer/tasks/devscripts_post.yml
  ci_framework/roles/reproducer/tasks/main.yml
  reproducer-clean.yml
  reproducer.yml
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved, lgtm

#810 Expose a userfriendly container env
  Makefile
  containerfiles/Containerfile.tests
  containerfiles/README.md
  docs/dictionary/en-custom.txt
Labels: approved, lgtm

#813 docs: modify containerfiles readme
  containerfiles/README.md
  docs/dictionary/en-custom.txt
Labels: approved, lgtm

#812 Allow to inject DNF configuration tweaks
  ci_framework/roles/reproducer/README.md
  ci_framework/roles/reproducer/defaults/main.yml
  ci_framework/roles/reproducer/tasks/configure_controller.yml
  reproducer.yml
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved, lgtm

#811 Remove useless parameter
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved

#807 Fix small nits in run_ansible_test
  scripts/run_ansible_test
Labels: approved, lgtm

#817 [set_openstack_containers] Also update env for dataplane operator
  ci_framework/roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm

#819 Add a note about the home directory in container
  containerfiles/README.md
  docs/dictionary/en-custom.txt
Labels: approved, lgtm

#814 Add repo-setup service in hci edpm job
  ci_framework/roles/hci_prepare/tasks/phase1.yml
Labels: approved, lgtm

#818 New role: manage_secrets
  ci_framework/roles/manage_secrets/README.md
  ci_framework/roles/manage_secrets/defaults/main.yml
  ci_framework/roles/manage_secrets/files/.gitkeep
  ci_framework/roles/manage_secrets/handlers/main.yml
  ci_framework/roles/manage_secrets/meta/main.yml
  ci_framework/roles/manage_secrets/molecule/ci_token/cleanup.yml
  ci_framework/roles/manage_secrets/molecule/ci_token/converge.yml
  ci_framework/roles/manage_secrets/molecule/ci_token/molecule.yml
  ci_framework/roles/manage_secrets/molecule/ci_token/prepare.yml
  ci_framework/roles/manage_secrets/molecule/kube/cleanup.yml
  ci_framework/roles/manage_secrets/molecule/kube/converge.yml
  ci_framework/roles/manage_secrets/molecule/kube/molecule.yml
  ci_framework/roles/manage_secrets/molecule/kube/prepare.yml
  ci_framework/roles/manage_secrets/molecule/pull_secret/cleanup.yml
  ci_framework/roles/manage_secrets/molecule/pull_secret/converge.yml
  ci_framework/roles/manage_secrets/molecule/pull_secret/molecule.yml
  ci_framework/roles/manage_secrets/molecule/pull_secret/prepare.yml
  ci_framework/roles/manage_secrets/tasks/_push_secret.yml
  ci_framework/roles/manage_secrets/tasks/ci_token.yml
  ci_framework/roles/manage_secrets/tasks/cleanup.yml
  ci_framework/roles/manage_secrets/tasks/kube.yml
  ci_framework/roles/manage_secrets/tasks/main.yml
  ci_framework/roles/manage_secrets/tasks/pull_secret.yml
  ci_framework/roles/manage_secrets/vars/main.yml
  docs/dictionary/en-custom.txt
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#823 Remove install_yamls installation method for CRC
  ci_framework/roles/rhol_crc/README.md
  ci_framework/roles/rhol_crc/defaults/main.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/cleanup.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/converge.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/molecule.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/prepare.yml
  ci_framework/roles/rhol_crc/tasks/install_yamls.yml
  ci_framework/roles/rhol_crc/tasks/main.yml
Labels: approved, lgtm

#826 Revert "Remove install_yamls installation method for CRC"
  ci_framework/roles/rhol_crc/README.md
  ci_framework/roles/rhol_crc/defaults/main.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/cleanup.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/converge.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/molecule.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/prepare.yml
  ci_framework/roles/rhol_crc/tasks/install_yamls.yml
  ci_framework/roles/rhol_crc/tasks/main.yml
Labels: approved, lgtm

#831 Disable cloud-init override of NM DNS
  ci/playbooks/multinode-customizations.yml
Labels: approved, lgtm

#830 Correct how we detect nested virtualization layout
  ci_framework/roles/artifacts/tasks/edpm.yml
  zuul.d/base.yaml
Labels: approved, lgtm

#825 Add task to include a component-based repo
  ci_framework/roles/repo_setup/README.md
  ci_framework/roles/repo_setup/defaults/main.yml
  ci_framework/roles/repo_setup/molecule/default/converge.yml
  ci_framework/roles/repo_setup/tasks/component_repo.yml
  ci_framework/roles/repo_setup/tasks/main.yml
Labels: approved, lgtm

#824 Use admonition and reformat some content
  CONTRIBUTING.md
  containerfiles/README.md
  docs/source/cookbooks/zuul-job-nodeset.md
  docs/source/development/01_guidelines.md
  docs/source/index.rst
  docs/source/quickstart/01_requirements.md
  docs/source/quickstart/03_deploy_infra.md
  docs/source/quickstart/04_consume_infra.md
  docs/source/quickstart/05_clean_infra.md
  docs/source/quickstart/99_FAQ.md
  docs/source/usage/01_usage.md
Labels: approved, lgtm

#828 Removed patch to dev-scripts source
  ci_framework/roles/devscripts/README.md
  ci_framework/roles/devscripts/tasks/sub_tasks/31_repo.yml
Labels: approved, lgtm

#833 Ensure some configurations are always set
  ci_framework/roles/reproducer/tasks/ci_job.yml
  ci_framework/roles/reproducer/tasks/configure_controller.yml
  ci_framework/roles/reproducer/tasks/push_code.yml
Labels: approved, lgtm

#820 Add cert-manager role
  ci/config/molecule.yaml
  ci_framework/roles/cert_manager/README.md
  ci_framework/roles/cert_manager/defaults/main.yml
  ci_framework/roles/cert_manager/meta/main.yml
  ci_framework/roles/cert_manager/molecule/default/converge.yml
  ci_framework/roles/cert_manager/molecule/default/molecule.yml
  ci_framework/roles/cert_manager/molecule/default/prepare.yml
  ci_framework/roles/cert_manager/tasks/cleanup.yml
  ci_framework/roles/cert_manager/tasks/main.yml
  ci_framework/roles/cert_manager/tasks/validate_certs.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#837 [rhol_crc] add_crc_creds: Fix check for kubeconfig
  ci_framework/roles/rhol_crc/tasks/add_crc_creds.yml
Labels: approved, lgtm, ok-to-test

#840 Patch dev-scripts repository for reliable deployment
  ci_framework/roles/devscripts/files/virtproxyd.patch
  ci_framework/roles/devscripts/tasks/sub_tasks/31_repo.yml
  ci_framework/roles/libvirt_manager/tasks/drivers.yml
  ci_framework/roles/libvirt_manager/tasks/virsh_checks.yml
Labels: approved, lgtm

#832 Fix the conditions when to use the default network as OCP external subnet
  ci_framework/roles/devscripts/README.md
  ci_framework/roles/devscripts/tasks/02_gather_env_details.yml
Labels: approved, lgtm

#846 Ensure we consume valid CA bundle
  ci_framework/roles/os_net_setup/tasks/main.yml
  ci_framework/roles/os_net_setup/tasks/subtask_net.yml
Labels: approved, lgtm

#848 Create and ignore "custom" directory
  .gitignore
  custom/README.md
Labels: approved, lgtm

#849 Add missing uri parameter
  ci_framework/roles/libvirt_manager/tasks/attach_interface.yml
Labels: approved, lgtm

#816 [networking_mapping] Adding Networking Definition parsing logic
  ci_framework/plugins/module_utils/networking_mapping/exceptions.py
  ci_framework/plugins/module_utils/networking_mapping/networking_definition.py
  ci_framework/tests/requirements.txt
  ci_framework/tests/unit/__init__.py
  ci_framework/tests/unit/module_utils/__init__.py
  ci_framework/tests/unit/module_utils/networking_mapping/test_networking_definitions_all.py
  ci_framework/tests/unit/module_utils/networking_mapping/test_networking_definitions_group_template.py
  ci_framework/tests/unit/module_utils/networking_mapping/test_networking_definitions_instance.py
  ci_framework/tests/unit/module_utils/networking_mapping/test_networking_definitions_network.py
  ci_framework/tests/unit/module_utils/networking_mapping/test_networking_definitions_ranges.py
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid-all-tools.yml
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid-network-template.yml
  ci_framework/tests/unit/module_utils/test_files/networking-definition-valid.yml
  ci_framework/tests/unit/module_utils/test_utils/networking_mapping_stub_data.py
Labels: approved, lgtm

#845 Remove Validated Architecture related content
  docs/source/architecture/00_general_facts.md
  docs/source/architecture/02_validated_architecture.md
  docs/source/quickstart/01_requirements.md
  docs/source/quickstart/03_deploy_infra.md
  docs/source/quickstart/04_consume_infra.md
  docs/source/quickstart/05_clean_infra.md
  docs/source/quickstart/99_FAQ.md
Labels: approved, lgtm

#772 Add role to collect operator images used in the environment
  ci/config/molecule.yaml
  ci_framework/playbooks/99-logs.yml
  ci_framework/roles/env_op_images/README.md
  ci_framework/roles/env_op_images/defaults/main.yml
  ci_framework/roles/env_op_images/meta/main.yml
  ci_framework/roles/env_op_images/molecule/default/converge.yml
  ci_framework/roles/env_op_images/molecule/default/molecule.yml
  ci_framework/roles/env_op_images/molecule/default/prepare.yml
  ci_framework/roles/env_op_images/tasks/main.yml
  docs/dictionary/en-custom.txt
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Feature

#822 rhol crc/manage secrets
  ci_framework/roles/manage_secrets/files/.gitkeep
  ci_framework/roles/manage_secrets/handlers/main.yml
  ci_framework/roles/rhol_crc/README.md
  ci_framework/roles/rhol_crc/defaults/main.yml
  ci_framework/roles/rhol_crc/molecule/default/converge.yml
  ci_framework/roles/rhol_crc/molecule/default/prepare.yml
  ci_framework/roles/rhol_crc/tasks/main.yml
  ci_framework/roles/rhol_crc/vars/main.yml
  docs/source/quickstart/01_requirements.md
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#857 [must-gather] Drop our custom log collection in favor of must-gather
  ci_framework/roles/artifacts/README.md
  ci_framework/roles/artifacts/defaults/main.yml
  ci_framework/roles/artifacts/tasks/crc.yml
  ci_framework/roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#856 Ensure we have correct rights on gathered content
  ci_framework/roles/artifacts/tasks/environment.yml
  ci_framework/roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#701 Adds cifmw-adoption-standalone-base for rhel 9.2 OSP17/CDN job
  zuul.d/adoption.yaml
Labels: approved, lgtm

#858 Added krb dlrn reporting support
  ci_framework/roles/dlrn_report/README.md
  ci_framework/roles/dlrn_report/defaults/main.yml
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
  ci_framework/roles/dlrn_report/tasks/install.yml
  docs/dictionary/en-custom.txt
Labels: approved, lgtm

#859 Update rhol_crc and global documentation
  ci_framework/roles/rhol_crc/README.md
  docs/source/quickstart/03_deploy_infra.md
  docs/source/reproducers/01-considerations.md
Labels: approved, lgtm

#863 Avoid running edpm jobs for a couple of roles
  zuul.d/base.yaml
Labels: approved, lgtm

#865 Add missing parameter to the parent job
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#864 Manage pull-secret only if needed
  ci_framework/roles/rhol_crc/tasks/main.yml
Labels: approved, lgtm

#861 Integrate manage_secrets in devscripts role
  ci_framework/roles/devscripts/README.md
  ci_framework/roles/devscripts/molecule/default/converge.yml
  ci_framework/roles/devscripts/tasks/main.yml
  ci_framework/roles/devscripts/tasks/sub_tasks/32_params.yml
  ci_framework/roles/devscripts/templates/conf_ciuser.sh.j2
Labels: approved, lgtm

#873 Add needed dependency in CI container
  containerfiles/Containerfile.ci
Labels: approved, lgtm
