Repository openstack-k8s-operators/ci-framework, pull requests merged in 2023-05, with the labels that each got.

#158 Pin ansible-compat in order to work around known issue
  ci_framework/roles/edpm_deploy/molecule/default/prepare.yml
  molecule-requirements.txt
Labels: approved, lgtm

#155 Skip operator_build role if no operator list is provided
  ci_framework/playbooks/05-build-operators.yml
Labels: approved, lgtm

#160 Adding CodeQL badge to the README.md
  README.md
Labels: approved, lgtm

#164 Move end-to-end jobs in a dedicated yaml
  ci/templates/jobs-init.yaml
  zuul.d/end-to-end.yaml
  zuul.d/jobs.yaml
Labels: approved, lgtm

#126 New role: edpm_prepare
  USAGE.md
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/roles/ci_setup/tasks/directories.yml
  ci_framework/roles/edpm_prepare/README.md
  ci_framework/roles/edpm_prepare/defaults/main.yml
  ci_framework/roles/edpm_prepare/meta/main.yml
  ci_framework/roles/edpm_prepare/molecule/default/converge.yml
  ci_framework/roles/edpm_prepare/molecule/default/molecule.yml
  ci_framework/roles/edpm_prepare/molecule/default/prepare.yml
  ci_framework/roles/edpm_prepare/tasks/cleanup.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/operator_build/tasks/main.yml
  scenarios/centos-9/ci.yml
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#165 Some quick corrections to zuul and Containerfile.test
  ci/templates/projects.yaml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/operator_build/tasks/build.yml
  containerfiles/Containerfile.tests
  zuul.d/projects.yaml
Labels: approved, lgtm

#163 Add playbooks and job to run kuttl tests
  ci/playbooks/kuttl/e2e-kuttl.yml
  ci/playbooks/kuttl/run.yml
  scenarios/centos-9/kuttl.yml
  zuul.d/kuttl.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#154 Adding EDPM based Zuul Job
  USAGE.md
  ci/playbooks/edpm/post.yml
  ci/playbooks/edpm/run.yml
  ci/templates/projects.yaml
  ci_framework/hooks/playbooks/disable_os_marketplace.yml
  ci_framework/hooks/playbooks/rabbitmq_tuning.yml
  ci_framework/hooks/playbooks/restart_nova_scheduler.yml
  ci_framework/playbooks/02-infra.yml
  ci_framework/playbooks/05-build-operators.yml
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/roles/artifacts/molecule/default/prepare.yml
  ci_framework/roles/artifacts/tasks/cluster_info.yml
  ci_framework/roles/artifacts/tasks/main.yml
  ci_framework/roles/edpm_deploy/README.md
  ci_framework/roles/edpm_deploy/defaults/main.yml
  ci_framework/roles/edpm_deploy/molecule/default/converge.yml
  ci_framework/roles/edpm_deploy/molecule/default/prepare.yml
  ci_framework/roles/edpm_deploy/tasks/cleanup.yml
  ci_framework/roles/edpm_deploy/tasks/configure.yml
  ci_framework/roles/edpm_deploy/tasks/deploy.yml
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_deploy/templates/edpm-play.yaml.j2
  ci_framework/roles/rhol_crc/tasks/add_crc_creds.yml
  scenarios/centos-9/edpm_ci.yml
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#170 Remove name and override-checkout from required projects
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/tests/sanity/ignore-2.15.txt
  zuul.d/content_provider.yaml
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
  zuul.d/jobs.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#173 Use centos-stream-9 nodeset instead of crc nodeset
  zuul.d/jobs.yaml
Labels: approved, lgtm

#174 Dynamically generate sanity-check ignore file based on Ansible version
  ci_framework/tests/sanity/ignore-2.14.txt
  ci_framework/tests/sanity/ignore-2.15.txt
  scripts/run_ansible_test
Labels: approved, lgtm

#175 Remove the unwanted cifmw_edpm_prepare_intall_yamls_output_dir var
  ci_framework/roles/edpm_prepare/tasks/main.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#177 Update mol test playbook for consuming it in edpm-ansible jobs
  ci/playbooks/molecule-prepare.yml
  ci/playbooks/molecule-test.yml
  zuul.d/jobs.yaml
Labels: approved, lgtm

#171 [Content provider]Return cifmw_operator_build_output var to child job
  ci/playbooks/content_provider/content_provider.yml
  ci/playbooks/content_provider/pre.yml
  ci/playbooks/content_provider/run.yml
  ci_framework/roles/operator_build/tasks/build.yml
  ci_framework/roles/registry_deploy/tasks/main.yml
  scenarios/centos-9/content_provider.yml
  zuul.d/content_provider.yaml
Labels: approved, lgtm

#185 Pass additional make_edpm_deploy_env var to inner ansible
  ci/playbooks/edpm/run.yml
Labels: approved, lgtm

#172 Add a simple approach to deploy a local test environment based on CS9 VM
  Makefile
  ci/playbooks/dev-workflow.yml
  ci/templates/projects.yaml
  ci_framework/roles/local_env_vm/README.md
  ci_framework/roles/local_env_vm/defaults/main.yml
  ci_framework/roles/local_env_vm/files/firstboot.sh
  ci_framework/roles/local_env_vm/meta/main.yml
  ci_framework/roles/local_env_vm/molecule/default/converge.yml
  ci_framework/roles/local_env_vm/molecule/default/molecule.yml
  ci_framework/roles/local_env_vm/tasks/main.yml
  dev-local-env.yml
  scenarios/centos-9/local-env.yml
  scripts/local_env_vm_prepare
  zuul.d/end-to-end.yaml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#187 Actually get nested virt
  ci_framework/roles/local_env_vm/tasks/main.yml
Labels: approved, lgtm

#166 Disable e2e skip of the edpm_prepare metaoperator deployment
  ci/playbooks/e2e-prepare.yml
  ci_framework/hooks/playbooks/rabbitmq_tuning.yml
  ci_framework/playbooks/05-build-operators.yml
  ci_framework/roles/edpm_deploy/defaults/main.yml
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/rhol_crc/tasks/install_yamls.yml
  ci_framework/roles/rhol_crc/tasks/main.yml
  scenarios/centos-9/ci-build.yml
  scenarios/centos-9/ci.yml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#189 Allow to pass arbitrary extra vars to playbook
  ci/playbooks/e2e-run.yml
  ci/playbooks/edpm/run.yml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#183 Sphinx documentation and version support
  .readthedocs.yaml
  CONTRIBUTING.md
  Makefile
  docs/Makefile_orig
  docs/doc-requirements.txt
  docs/source/Makefile
  docs/source/artifacts.md
  docs/source/conf.py
  docs/source/contributing.md
  docs/source/index.rst
  docs/source/psi.md
  docs/source/quickstart.md
  docs/source/readme.md
  docs/source/requirements.md
  docs/source/structure.md
Labels: documentation, approved, lgtm

#195 Do not kick any molecule nor e2e job on .md editions
  ci/templates/molecule.yaml
  ci/templates/projects.yaml
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#182 Fix typo in task description
  deploy-edpm.yml
Labels: approved, lgtm

#197 Refactor documentation and add new content
  README.md
  ci/playbooks/collect-logs.yml
  ci_framework/plugins/README.md
  docs/source/Development/01_contributing.md
  docs/source/Internals/01_structure.md
  docs/source/Internals/02_testing.md
  docs/source/Quickstart/01_requirements.md
  docs/source/Quickstart/02_nested_virt.md
  docs/source/Quickstart/03_psi.md
  docs/source/Quickstart/99_FAQ.md
  docs/source/Usage/01_usage.md
  docs/source/Usage/02_own_ci.md
  docs/source/contributing.md
  docs/source/index.rst
  docs/source/plugins_readme.md
  docs/source/readme.md
  zuul.d/doc.yaml
Labels: approved, lgtm

#199 Add baremetal-operator in required-project
  zuul.d/content_provider.yaml
Labels: approved, lgtm

#200 Add documentation about molecule tests
  Makefile
  docs/source/Development/02_molecule.md
Labels: approved, lgtm

#204 Fixing namespaces calculation and full e2e trigger pattern
  ci_framework/roles/openshift_setup/tasks/main.yml
  ci_framework/roles/operator_build/README.md
  ci_framework/roles/operator_build/defaults/main.yml
  ci_framework/roles/operator_build/tasks/build.yml
  scenarios/centos-9/ci-build.yml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#209 Sets cifmw_openshift_setup_kubeconfig for rdo crc-base jobs
  zuul.d/edpm.yaml
Labels: approved, lgtm

#203 Add new doc for non-nested virtualization deploy
  Makefile
  docs/source/Quickstart/04_non-virt.md
Labels: approved, lgtm

#211 Add cifmw_operator_build_extra_bundles to content provider scenario
  scenarios/centos-9/content_provider.yml
Labels: approved, lgtm

#210 Ensure cifmw_kubeconfig is set if externally given out of infra step
  ci_framework/playbooks/02-infra.yml
Labels: approved, lgtm

#202 Move data directory to a more understandable name
  ansible.cfg
  ci/playbooks/collect-logs.yml
  ci_framework/playbooks/01-bootstrap.yml
  ci_framework/playbooks/99-logs.yml
  ci_framework/plugins/README.md
  ci_framework/plugins/modules/generate_make_tasks.py
  ci_framework/roles/artifacts/README.md
  ci_framework/roles/artifacts/defaults/main.yml
  ci_framework/roles/artifacts/molecule/default/converge.yml
  ci_framework/roles/ci_setup/README.md
  ci_framework/roles/ci_setup/defaults/main.yml
  ci_framework/roles/ci_setup/molecule/default/converge.yml
  ci_framework/roles/edpm_deploy/README.md
  ci_framework/roles/edpm_deploy/defaults/main.yml
  ci_framework/roles/edpm_prepare/README.md
  ci_framework/roles/edpm_prepare/defaults/main.yml
  ci_framework/roles/edpm_prepare/molecule/default/prepare.yml
  ci_framework/roles/install_yamls/README.md
  ci_framework/roles/install_yamls/defaults/main.yml
  ci_framework/roles/install_yamls/molecule/default/converge.yml
  ci_framework/roles/libvirt_manager/README.md
  ci_framework/roles/libvirt_manager/defaults/main.yml
  ci_framework/roles/local_env_vm/README.md
  ci_framework/roles/local_env_vm/defaults/main.yml
  ci_framework/roles/operator_build/README.md
  ci_framework/roles/operator_build/defaults/main.yml
  ci_framework/roles/operator_deploy/README.md
  ci_framework/roles/operator_deploy/defaults/main.yml
  ci_framework/roles/pkg_build/README.md
  ci_framework/roles/pkg_build/defaults/main.yml
  ci_framework/roles/repo_setup/README.md
  ci_framework/roles/repo_setup/defaults/main.yml
  ci_framework/roles/repo_setup/molecule/default/converge.yml
  ci_framework/roles/rhol_crc/README.md
  ci_framework/roles/rhol_crc/defaults/main.yml
  ci_framework/roles/rhol_crc/molecule/default/prepare.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/prepare.yml
  ci_framework/roles/run_hook/README.md
  ci_framework/roles/run_hook/tasks/playbook.yml
  docs/source/Quickstart/02_nested_virt.md
  docs/source/Usage/01_usage.md
  scenarios/centos-9/base.yml
  zuul.d/content_provider.yaml
Labels: approved, lgtm

#215 Update create a PSI instance section
  docs/source/Quickstart/03_psi.md
Labels: approved, lgtm

#218 Correct loop label
  ci_framework/roles/ci_setup/tasks/directories.yml
Labels: approved, lgtm

#219 Update the PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/require-checklist.yaml
Labels: approved, lgtm

#213 Update small nits regarding local non virt
  docs/source/Quickstart/04_non-virt.md
Labels: approved, lgtm, ok-to-test

#229 Improve documentation related to the requirements
  docs/source/Quickstart/01_requirements.md
  docs/source/Quickstart/02_nested_virt.md
  docs/source/Quickstart/04_non-virt.md
Labels: approved, lgtm

#222 Replace zuul-worker with zuul
  ci/playbooks/edpm/pre.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#224 Extend generate_make_tasks documentation
  ci_framework/plugins/README.md
Labels: approved, lgtm
