Repository openstack-k8s-operators/ci-framework, pull requests merged in 2023-08, with the labels that each got.

#422 Properly consume exposed modules/actions
  .config/molecule/config_local.yml
  zuul.d/molecule-base.yaml
Labels: approved, lgtm

#424 Update Ceph toy env vars
  scenarios/centos-9/ceph_backends.yml
  scenarios/centos-9/ci.yml
Labels: approved, lgtm

#403 Dump edpm container images in separate log file
  ci_framework/roles/edpm_build_images/tasks/post.yaml
  zuul.d/edpm_build_images.yaml
Labels: approved, lgtm

#425 New role: edpm_kustomize
  ci_framework/roles/edpm_kustomize/README.md
  ci_framework/roles/edpm_kustomize/defaults/main.yml
  ci_framework/roles/edpm_kustomize/meta/main.yml
  ci_framework/roles/edpm_kustomize/molecule/default/converge.yml
  ci_framework/roles/edpm_kustomize/molecule/default/molecule.yml
  ci_framework/roles/edpm_kustomize/molecule/default/prepare.yml
  ci_framework/roles/edpm_kustomize/tasks/kustomize.yml
  ci_framework/roles/edpm_kustomize/tasks/main.yml
  ci_framework/roles/edpm_kustomize/templates/base_kustomization.j2
  docs/dictionary/en-custom.txt
  docs/source/roles/edpm_kustomize.md
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#427 tempest podman with host network
  ci_framework/roles/tempest/tasks/main.yml
Labels: approved, lgtm

#381 Enable tempest on EDPM job
  scenarios/centos-9/edpm_ci.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#429 Examples deploy edpm explicit
  docs/source/quickstart/04_non-virt.md
  scenarios/centos-9/local-env.yml
Labels: approved, lgtm

#432 Disable tempest in edpm check job and enable it in periodic
  scenarios/centos-9/edpm_ci.yml
  scenarios/centos-9/edpm_periodic.yml
Labels: lgtm

#419 Add support of `--build-args` agrs in edpm_build_images role
  ci_framework/roles/edpm_build_images/README.md
  ci_framework/roles/edpm_build_images/defaults/main.yml
  ci_framework/roles/edpm_build_images/tasks/package.yml
Labels: approved, lgtm

#417 Add role to report DLRN results
  ci_framework/roles/dlrn_report/README.md
  ci_framework/roles/dlrn_report/defaults/main.yml
  ci_framework/roles/dlrn_report/meta/main.yml
  ci_framework/roles/dlrn_report/molecule/default/converge.yml
  ci_framework/roles/dlrn_report/molecule/default/molecule.yml
  ci_framework/roles/dlrn_report/molecule/default/prepare.yml
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
  ci_framework/roles/dlrn_report/tasks/install.yml
  ci_framework/roles/dlrn_report/tasks/main.yml
  docs/dictionary/en-custom.txt
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#435 Ensure we keep correct order
  ci/templates/molecule.yaml.j2
  scripts/create_role_molecule.py
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#436 Add var for EDPM nova deployment pod name
  ci_framework/roles/edpm_deploy/README.md
  ci_framework/roles/edpm_deploy/defaults/main.yml
  ci_framework/roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#426 Correct makefile known parameters and how we handle them
  ci_framework/roles/install_yamls/README.md
  ci_framework/roles/install_yamls/defaults/main.yml
  ci_framework/roles/install_yamls/tasks/main.yml
  docs/source/quickstart/04_non-virt.md
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
  scenarios/centos-9/install_yamls.yml
Labels: approved, lgtm

#438 [dlrn_report] use shell module instead of ci_script
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm

#440 [dlrn_report] escape the spaces in shell task
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm

#441 Consider `None` value of hash variables in conditional check
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm

#439 Make edpm_prepare and deploy accept kustomizations
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_kustomize/tasks/kustomize.yml
  ci_framework/roles/edpm_prepare/README.md
  ci_framework/roles/edpm_prepare/defaults/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#442 Wait OpenStackDataplane resource instead of the deploy pod.
  ci_framework/roles/edpm_deploy/README.md
  ci_framework/roles/edpm_deploy/defaults/main.yml
  ci_framework/roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#443 Fix the spacing issue in condition check
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: lgtm

#445 Switch back to shell module instead of command
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: lgtm

#444 Added taskfiles to collect edpm logs from edpm vms
  ci_framework/roles/artifacts/tasks/edpm.yml
  ci_framework/roles/artifacts/tasks/main.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#448 Allow to chose target for CI playbooks
  ci/playbooks/build_runner_image.yml
  ci/playbooks/collect-logs.yml
  ci/playbooks/content_provider/pre.yml
  ci/playbooks/content_provider/run.yml
  ci/playbooks/e2e-collect-logs.yml
  ci/playbooks/edpm/run.yml
  ci/playbooks/edpm_baremetal_deployment/run.yml
  ci/playbooks/edpm_build_images/edpm_build_images_content_provider_run.yaml
  ci/playbooks/edpm_build_images/edpm_image_builder.yml
  ci/playbooks/edpm_build_images/run.yml
  ci/playbooks/tcib/run.yml
Labels: approved, lgtm

#447 Improve edpm log collection
  ci_framework/roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm

#452 Add missing authentication data for k8s task
  ci_framework/roles/openshift_setup/tasks/main.yml
Labels: approved, lgtm

#450 Added information about NTP server config
  docs/dictionary/en-custom.txt
  docs/source/quickstart/99_FAQ.md
Labels: approved, lgtm, ok-to-test

#455 Add new contributor/reviewer
  OWNERS
Labels: approved, lgtm

#456 Filter hosts in CI playbook
  ci/playbooks/build_runner_image.yml
  ci/playbooks/collect-logs.yml
  ci/playbooks/content_provider/pre.yml
  ci/playbooks/content_provider/run.yml
  ci/playbooks/e2e-collect-logs.yml
  ci/playbooks/edpm/run.yml
  ci/playbooks/edpm_baremetal_deployment/run.yml
  ci/playbooks/edpm_build_images/edpm_build_images_content_provider_run.yaml
  ci/playbooks/edpm_build_images/edpm_image_builder.yml
  ci/playbooks/edpm_build_images/run.yml
  ci/playbooks/tcib/run.yml
Labels: approved, lgtm

#458 Run oc with a a proper kubeconfig in tempest
  ci_framework/roles/tempest/tasks/configure-tempest.yml
Labels: approved, lgtm

#454 Ensure CI playbooks have a name
  ci/playbooks/build_runner_image.yml
  ci/playbooks/collect-logs.yml
  ci/playbooks/content_provider/content_provider.yml
  ci/playbooks/content_provider/pre.yml
  ci/playbooks/content_provider/run.yml
  ci/playbooks/dev-workflow.yml
  ci/playbooks/dump_zuul_vars.yml
  ci/playbooks/e2e-collect-logs.yml
  ci/playbooks/e2e-prepare.yml
  ci/playbooks/e2e-run.yml
  ci/playbooks/edpm/run.yml
  ci/playbooks/edpm_baremetal_deployment/run.yml
  ci/playbooks/edpm_build_images/edpm_build_images_content_provider.yaml
  ci/playbooks/edpm_build_images/edpm_build_images_content_provider_run.yaml
  ci/playbooks/edpm_build_images/edpm_image_builder.yml
  ci/playbooks/edpm_build_images/run.yml
  ci/playbooks/kuttl/run.yml
  ci/playbooks/molecule-prepare.yml
  ci/playbooks/molecule-test.yml
  ci/playbooks/pre-doc.yml
  ci/playbooks/run-doc.yml
  ci/playbooks/tcib/run.yml
  ci/playbooks/tcib/tcib.yml
Labels: approved, lgtm

#459 Exporting cifmw_openshift_login_skip_tls_verify as global
  ci_framework/roles/openshift_login/README.md
  ci_framework/roles/openshift_login/defaults/main.yml
  ci_framework/roles/openshift_login/tasks/login.yml
  docs/source/usage/01_usage.md
Labels: approved

#460 Ensure we don't fail on stopped VM
  ci_framework/roles/libvirt_manager/tasks/clean_layout.yml
Labels: approved, lgtm

#464 Ensure we use the discovered image in computes if not other one given.
  ci_framework/roles/libvirt_manager/tasks/deploy_edpm_compute.yml
Labels: approved, lgtm

#461 Ensure we collect logs from compute(s) with new layout
  ci_framework/roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm

#466 Correct a small typo in the action plugin
  ci_framework/plugins/modules/get_makefiles_env.py
Labels: approved, lgtm

#467 Update container tags ending with any filter
  ci_framework/roles/set_openstack_containers/README.md
  ci_framework/roles/set_openstack_containers/defaults/main.yml
  ci_framework/roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm

#468 Add openstack-k8s-operators/ovn-operator in required-project
  zuul.d/content_provider.yaml
Labels: approved, lgtm

#469 Fixing the install_yamls expected cloned path
  scenarios/centos-9/install_yamls.yml
Labels: approved, lgtm

#470 Fixing artifacts include vars typo
  ci_framework/roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm

#457 Run os_must_gather only in case of failure
  ci_framework/playbooks/99-logs.yml
  ci_framework/roles/artifacts/README.md
  ci_framework/roles/artifacts/defaults/main.yml
  ci_framework/roles/artifacts/tasks/main.yml
  deploy-edpm.yml
Labels: approved, lgtm

#472 Early load hooks env in logs playbook
  ci_framework/roles/artifacts/tasks/edpm.yml
  ci_framework/roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#473 Fix podified/edpm log collection
  ci_framework/roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#462 Set proper container registry url and hash for edpm_deploy
  ci_framework/roles/edpm_deploy/defaults/main.yml
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/repo_setup/defaults/main.yml
  scenarios/centos-9/edpm_periodic.yml
Labels: approved, lgtm

#478 Change base container image ubi9->centos
  ci_framework/roles/build_containers/defaults/main.yml
Labels: approved, lgtm

#475 Add SoftwareFactory ZUUL app to all operators
  zuul.d/content_provider.yaml
Labels: approved, lgtm

#486 Ony report DLRN results when var is true
  ci_framework/roles/dlrn_report/tasks/main.yml
Labels: approved, lgtm

#361 Introduce new CI layout for end-to-end jobs
  ci/playbooks/collect-logs.yml
  ci/playbooks/e2e-run.yml
  ci/playbooks/wait-for-crc.yaml
  ci/templates/projects.yaml
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
  scenarios/centos-9/ci.yml
  scenarios/centos-9/edpm_ci.yml
  scenarios/centos-9/install_yamls.yml
  scenarios/centos-9/multinode-ci.yml
  scenarios/centos-9/nested_virt.yml
  zuul.d/edpm.yaml
  zuul.d/edpm_multinode.yaml
  zuul.d/edpm_periodic.yaml
  zuul.d/end-to-end.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#481 Add new target for checking modified zuul files
  .pre-commit-config.yaml
  Makefile
  scripts/check_zuul_files.sh
Labels: approved, lgtm

#407 Add task to create tempestconf profile
  ci_framework/roles/tempest/README.md
  ci_framework/roles/tempest/tasks/configure-tempest.yml
  docs/dictionary/en-custom.txt
Labels: approved, lgtm

#323 Integrate OCP deployment using Hive
  ci_framework/playbooks/02-infra.yml
  ci_framework/roles/hive/meta/main.yml
Labels: approved, lgtm

#379 Improve content provider to work with standalone crc job
  ci/playbooks/collect-logs.yml
  ci/playbooks/content_provider/content_provider.yml
  ci/playbooks/content_provider/run.yml
  ci/playbooks/set_crc_insecure_registry.yml
  ci/playbooks/wait-for-crc.yaml
  zuul.d/content_provider.yaml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#483 Fix task name typo in openshift_login role
  ci_framework/roles/openshift_login/tasks/login.yml
Labels: approved, lgtm

#471 Use install_yamls defaults to locate CRs to deploy instead of searching
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
Labels: approved, lgtm

#492 Replace crc passwd for nested crc jobs
  scenarios/centos-9/ci.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm
