Repository openstack-k8s-operators/ci-framework, pull requests merged in 2023-09, with the labels that each got.

#485 Add barbican and swift operators to required-projects list
  zuul.d/content_provider.yaml
Labels: approved, lgtm

#494 Rename wait-for-crc playbook
  ci/playbooks/multinode-customizations.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#421 ci_script implementation [1]
  ci_framework/roles/openshift_provisioner_node/molecule/defaults/converge.yml
  ci_framework/roles/os_must_gather/tasks/main.yml
  ci_framework/roles/set_openstack_containers/tasks/main.yml
Labels: approved, lgtm

#488 Collect pod status and their crs file
  ci_framework/roles/artifacts/tasks/crc.yml
Labels: approved, lgtm

#490 Remove galera job
  ci/playbooks/collect-logs.yml
  ci/templates/projects.yaml
  docs/dictionary/en-custom.txt
  docs/source/cookbooks/zuul-job-nodeset.md
  scenarios/centos-9/ci.yml
  zuul.d/edpm_multinode.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#499 Pin Ceph container to latest-reef
  ci_framework/roles/cifmw_cephadm/README.md
  ci_framework/roles/cifmw_cephadm/defaults/main.yml
Labels: approved, lgtm

#497 Remove disable_default_gw flag
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#484 Allow to override repo-setup in downstream
  ci_framework/roles/edpm_deploy_baremetal/README.md
  ci_framework/roles/edpm_deploy_baremetal/defaults/main.yml
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#482 Correct edpm.yml artifacts collection
  ci/playbooks/multinode-customizations.yml
  ci_framework/roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm

#500 Add new logo to the project
  README.md
  docs/dictionary/en-custom.txt
  docs/source/conf.py
  docs/source/images/logo.svg
  docs/source/images/logo_cifmw.svg
  docs/source/images/logo_cifmw_128.png
  docs/source/images/logo_cifmw_200.png
  docs/source/images/logo_cifmw_256.png
  docs/source/images/logo_cifmw_64.png
  docs/source/images/logo_cifmw_800.png
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#509 Rename ansible builtin calls using fully qualified names
  ci_framework/playbooks/ceph.yml
  ci_framework/roles/cifmw_ceph_client/README.md
  ci_framework/roles/cifmw_ceph_client/molecule/default/converge.yml
  ci_framework/roles/cifmw_ceph_client/molecule/default/prepare.yml
  ci_framework/roles/cifmw_ceph_client/tasks/create_ceph_conf.yml
  ci_framework/roles/cifmw_ceph_client/tasks/create_keys.yml
  ci_framework/roles/cifmw_ceph_client/tasks/main.yml
  ci_framework/roles/cifmw_ceph_spec/README.md
  ci_framework/roles/cifmw_ceph_spec/tasks/cleanup.yml
  ci_framework/roles/cifmw_ceph_spec/tasks/main.yml
  ci_framework/roles/cifmw_cephadm/molecule/default/converge.yml
  ci_framework/roles/cifmw_cephadm/molecule/default/prepare.yml
  ci_framework/roles/cifmw_cephadm/molecule/default/tasks/verify.yml
  ci_framework/roles/cifmw_cephadm/tasks/apply_spec.yml
  ci_framework/roles/cifmw_cephadm/tasks/bootstrap.yml
  ci_framework/roles/cifmw_cephadm/tasks/ceph_cli.yml
  ci_framework/roles/cifmw_cephadm/tasks/cephadm_config_set.yml
  ci_framework/roles/cifmw_cephadm/tasks/check_keyring.yml
  ci_framework/roles/cifmw_cephadm/tasks/export.yml
  ci_framework/roles/cifmw_cephadm/tasks/keys.yml
  ci_framework/roles/cifmw_cephadm/tasks/monitor_ceph_orch.yml
  ci_framework/roles/cifmw_cephadm/tasks/pools.yml
  ci_framework/roles/cifmw_cephadm/tasks/post.yml
  ci_framework/roles/cifmw_cephadm/tasks/pre.yml
  ci_framework/roles/cifmw_cephadm/tasks/selinux.yml
  ci_framework/roles/cifmw_cephadm/tasks/toggle_cephadm.yml
  ci_framework/roles/cifmw_cephadm/tasks/wait_for_expected_num_mons.yml
  ci_framework/roles/cifmw_cephadm/tasks/wait_for_expected_num_osds.yml
  ci_framework/roles/cifmw_create_admin/molecule/addkey/converge.yml
  ci_framework/roles/cifmw_create_admin/molecule/addkey/prepare.yml
  ci_framework/roles/cifmw_create_admin/molecule/keygen/prepare.yml
  ci_framework/roles/cifmw_create_admin/tasks/authorize_user.yml
  ci_framework/roles/cifmw_create_admin/tasks/create_user.yml
  ci_framework/roles/cifmw_create_admin/tasks/distribute_key_files.yml
  ci_framework/roles/cifmw_create_admin/tasks/main.yml
Labels: approved, lgtm

#487 Removed old dead EDPM log collection from edpm_deploy
  ci_framework/roles/edpm_deploy/README.md
  ci_framework/roles/edpm_deploy/defaults/main.yml
  ci_framework/roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#498 Run content provider on script changes
  zuul.d/content_provider.yaml
Labels: approved, lgtm

#506 Continue ci_script implementation replacing shell and command built-i…
  ci_framework/roles/repo_setup/molecule/default/converge.yml
  ci_framework/roles/repo_setup/tasks/artifacts.yml
  ci_framework/roles/repo_setup/tasks/configure.yml
  ci_framework/roles/repo_setup/tasks/install.yml
  ci_framework/roles/repo_setup/tasks/rhos_release.yml
Labels: approved, lgtm

#507 Continue ci_script implementation
  ci_framework/roles/libvirt_manager/tasks/create_vms.yml
Labels: approved, lgtm

#514 Revert "Continue ci_script implementation"
  ci_framework/roles/repo_setup/molecule/default/converge.yml
  ci_framework/roles/repo_setup/tasks/artifacts.yml
  ci_framework/roles/repo_setup/tasks/configure.yml
  ci_framework/roles/repo_setup/tasks/install.yml
  ci_framework/roles/repo_setup/tasks/rhos_release.yml
Labels: approved

#513 Skip EDPM jobs on content provider irrelevant_files
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#510 Continue ci_script implementation for ceph roles
  ci_framework/roles/cifmw_cephadm/defaults/main.yml
  ci_framework/roles/cifmw_cephadm/tasks/bootstrap.yml
Labels: approved, lgtm

#516 Update pyspell.yml
  .github/workflows/pyspell.yml
Labels: approved, lgtm

#493 Add retries to install_yamls input target
  ci_framework/roles/edpm_prepare/tasks/main.yml
Labels: approved, lgtm

#489 Add Dev-preview workaround to finish EDPM deployment
  deploy-edpm.yml
Labels: approved, lgtm

#479 Update ci-framework to support DP CRD design
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
  ci_framework/roles/edpm_kustomize/README.md
  ci_framework/roles/edpm_kustomize/molecule/default/converge.yml
  docs/dictionary/en-custom.txt
Labels: approved, lgtm

#527 Fix OpenStackProvisionServer for EDPM baremetal jobs
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#532 Revert "Continue ci_script implementation replacing shell and command built-in modules"
  ci_framework/roles/cifmw_cephadm/defaults/main.yml
  ci_framework/roles/cifmw_cephadm/tasks/bootstrap.yml
Labels: approved, lgtm

#517 Add support to set concurrency value in tempest
  ci_framework/roles/tempest/README.md
  ci_framework/roles/tempest/defaults/main.yml
  ci_framework/roles/tempest/tasks/main.yml
Labels: approved, lgtm

#534 Introduce Zuul Project template
  ci/templates/projects.yaml
  zuul.d/project-templates.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#536 Run ansibleee kuttl tests as default
  zuul.d/kuttl.yaml
Labels: approved, lgtm

#537 Revert "Add Dev-preview workaround to finish EDPM deployment"
  deploy-edpm.yml
Labels: approved, lgtm

#480 Gather cluster related logs for kuttl job
  zuul.d/kuttl.yaml
Labels: approved, lgtm

#540 Fix indentation issues in the read-the-docs config
  .readthedocs.yaml
Labels: approved, lgtm

#542 Add more project template and improve it
  zuul.d/content_provider.yaml
  zuul.d/project-templates.yaml
Labels: approved, lgtm

#545 Correct pyspell configuration file indentation
  .spellcheck.yml
Labels: approved, lgtm

#525 Fix the way we call ini lookup on the `initial.ceph` config file
  ci_framework/playbooks/ceph.yml
Labels: approved, lgtm

#503 Add a simple retries mechanism for os_net_config
  ci_framework/roles/os_net_setup/README.md
  ci_framework/roles/os_net_setup/defaults/main.yml
  ci_framework/roles/os_net_setup/tasks/main.yml
  ci_framework/roles/os_net_setup/tasks/subtask_net.yml
  docs/dictionary/en-custom.txt
Labels: approved, lgtm

#547 Rely on zuul var to set cifmw_operator_build_operators var
  ci/playbooks/content_provider/content_provider.yml
Labels: approved, lgtm

#544 Pass extra install_yamls variables to the set_openstack_containers role
  ci_framework/roles/edpm_prepare/tasks/main.yml
  ci_framework/roles/set_openstack_containers/tasks/main.yml
Labels: approved, lgtm

#549 Fix Ceph Spec play to correctly map hostname to storage IP
  ci_framework/playbooks/ceph.yml
Labels: approved, lgtm

#451 Fixes for kuttl tests
  ci/playbooks/kuttl/e2e-kuttl.yml
  ci/playbooks/kuttl/run-kuttl-tests.yml
  ci/templates/projects.yaml
  scenarios/centos-9/kuttl.yml
  zuul.d/kuttl_multinode.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#546 FQCN fix for calls to ansible.utils.ipaddr in ceph playbook
  ci_framework/playbooks/ceph.yml
  ci_framework/roles/cifmw_ceph_spec/README.md
  docs/dictionary/en-custom.txt
Labels: approved, lgtm

#551 Add a simple retries mechanism to the keystone-public route fetch
  ci_framework/roles/edpm_prepare/README.md
  ci_framework/roles/edpm_prepare/defaults/main.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
Labels: approved, lgtm

#512 Add support for dlrn_hash_tag in repo-setup role
  ci_framework/roles/dlrn_report/tasks/dlrn_report_results.yml
  ci_framework/roles/repo_setup/README.md
  ci_framework/roles/repo_setup/defaults/main.yml
  ci_framework/roles/repo_setup/tasks/artifacts.yml
  ci_framework/roles/repo_setup/tasks/configure.yml
  zuul.d/edpm_build_images.yaml
Labels: approved, lgtm

#553 edpm_kustomize hack that allows multidocument manifests
  ci_framework/roles/edpm_deploy/tasks/main.yml
  ci_framework/roles/edpm_kustomize/tasks/kustomize.yml
  ci_framework/roles/edpm_prepare/tasks/main.yml
Labels: approved, lgtm

#555 Pin tempest container to last known good tag
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#559 Update ceph roles for cloud-admin
  ci_framework/playbooks/ceph.yml
  ci_framework/roles/cifmw_cephadm/README.md
  ci_framework/roles/cifmw_cephadm/tasks/keys.yml
Labels: approved, lgtm

#554 Replace jmspath query with a native Ansible one
  ci_framework/roles/openshift_login/tasks/login.yml
Labels: approved, lgtm

#556 Add tempest related vars for periodic jobs
  scenarios/centos-9/edpm_periodic.yml
  zuul.d/edpm_periodic.yaml
Labels: approved, lgtm

#543 Generate gating.repo to install built packages
  ci_framework/roles/build_openstack_packages/tasks/create_repo.yml
Labels: approved, lgtm

#535 Update documentation for change in ci_framework location
  docs/source/quickstart/04_non-virt.md
Labels: approved, lgtm

#539 Add flake8 linting and black formatting to CI
  .pre-commit-config.yaml
  Makefile
  ci_framework/plugins/action/ci_make.py
  ci_framework/plugins/action/ci_script.py
  ci_framework/plugins/action/discover_latest_image.py
  ci_framework/plugins/modules/cephx_key.py
  ci_framework/plugins/modules/generate_make_tasks.py
  ci_framework/plugins/modules/get_makefiles_env.py
  ci_framework/plugins/modules/tempest_list_allowed.py
  ci_framework/plugins/modules/tempest_list_skipped.py
  ci_framework/roles/cifmw_create_admin/molecule/addkey/tests/test_keyadd.py
  ci_framework/roles/cifmw_create_admin/molecule/default/tests/test_default.py
  ci_framework/roles/cifmw_create_admin/molecule/keygen/tests/test_keygen.py
  docs/source/conf.py
  scripts/create_role_molecule.py
  scripts/tests/test_create_role_molecule.py
  tox.ini
Labels: approved, lgtm

#563 Revert "Pin tempest container to last known good tag"
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#552 Add cinder to the list of kuttl tests
  zuul.d/kuttl_multinode.yaml
Labels: approved, lgtm

#565 Move all the base jobs to base.yaml
  zuul.d/base.yaml
  zuul.d/content_provider.yaml
  zuul.d/edpm.yaml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#567 Make CI flake match the tox settings
  .pre-commit-config.yaml
Labels: approved, lgtm

#561 Add management networks for Ceph SSH and OSD replication
  ci_framework/playbooks/ceph.yml
  ci_framework/roles/cifmw_ceph_spec/defaults/main.yml
  ci_framework/roles/cifmw_ceph_spec/molecule/default/converge.yml
  ci_framework/roles/cifmw_ceph_spec/molecule/default/tasks/verify_conf.yml
  ci_framework/roles/cifmw_ceph_spec/molecule/default/tasks/verify_spec.yml
  ci_framework/roles/cifmw_ceph_spec/tasks/main.yml
  ci_framework/roles/cifmw_ceph_spec/templates/initial_ceph.conf.j2
Labels: approved, lgtm

#572 Gather "zuul" parameter
  ci_framework/playbooks/01-bootstrap.yml
Labels: approved, lgtm

#571 Allow to gather passed hooks in the custom params
  ci_framework/playbooks/01-bootstrap.yml
Labels: approved, lgtm

#570 Fix typo in hive role
  ci_framework/roles/hive/tasks/baremetal_delete_cluster.yml
Labels: approved, lgtm

#577 Remove noop DeployStrategy
  ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
  ci_framework/roles/libvirt_manager/templates/kustomize_compute.yml.j2
Labels: approved, lgtm

#511 Add ci_kustomize action plugin
  ci_framework/plugins/action/ci_kustomize.py
  ci_framework/tests/integration/targets/kustomize/files/a-sorting-kustomization.yml
  ci_framework/tests/integration/targets/kustomize/files/b-sorting-kustomization.yml
  ci_framework/tests/integration/targets/kustomize/files/c-sorting-kustomization.yml
  ci_framework/tests/integration/targets/kustomize/files/cm-kustomization-1.yml
  ci_framework/tests/integration/targets/kustomize/files/cm-kustomization-2.yml
  ci_framework/tests/integration/targets/kustomize/files/kustomization.yaml
  ci_framework/tests/integration/targets/kustomize/files/kustomization.yml
  ci_framework/tests/integration/targets/kustomize/files/multiple-kustomizations-in-one-file.yml
  ci_framework/tests/integration/targets/kustomize/files/single-kustomization-file-1.yaml
  ci_framework/tests/integration/targets/kustomize/files/single-kustomization-file-2.yaml
  ci_framework/tests/integration/targets/kustomize/files/testing-cm.yml
  ci_framework/tests/integration/targets/kustomize/files/testing-combined-manifests.yml
  ci_framework/tests/integration/targets/kustomize/files/testing-deployment.yaml
  ci_framework/tests/integration/targets/kustomize/tasks/main.yml
  ci_framework/tests/integration/targets/kustomize/tasks/run_test_case.yml
  ci_framework/tests/integration/targets/kustomize/tasks/run_test_case_validate.yml
  ci_framework/tests/integration/targets/kustomize/tasks/run_test_case_validate_failure.yml
  ci_framework/tests/integration/targets/kustomize/tasks/run_test_case_validate_success.yml
  ci_framework/tests/integration/targets/kustomize/tasks/scenarios/ci_kustomize_extras_scenario.yml
  ci_framework/tests/integration/targets/kustomize/tasks/scenarios/ci_kustomize_failures_scenario.yml
  ci_framework/tests/integration/targets/kustomize/tasks/scenarios/ci_kustomize_file_input_scenario.yml
  ci_framework/tests/integration/targets/kustomize/tasks/scenarios/ci_kustomize_mixed_input_scenario.yml
  ci_framework/tests/integration/targets/kustomize/tasks/scenarios/ci_kustomize_vars_input_scenario.yml
Labels: approved, lgtm

#576 Handle ceph orch stuck issues
  ci_framework/playbooks/ceph.yml
Labels: approved, lgtm, ok-to-test

#579 Do not set cifmw_cephadm_first_mon_ip from Ceph spec
  ci_framework/playbooks/ceph.yml
Labels: approved, lgtm

#560 Use default single-nic-vlans.j2
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
  ci_framework/tests/integration/targets/make/files/get_makefiles_env/expected_variables_values.yml
  ci_framework/tests/integration/targets/make/files/get_makefiles_env/makefiles/Makefile
  ci_framework/tests/integration/targets/make/files/get_makefiles_env/makefiles/subdir/Makefile
Labels: approved, lgtm

#562 Add edpm multinode job with 3 computes
  ci/playbooks/multinode-customizations.yml
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
  ci_framework/roles/artifacts/tasks/edpm.yml
  ci_framework/roles/edpm_kustomize/README.md
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#558 Add dlrn_promote role
  ci_framework/roles/dlrn_promote/README.md
  ci_framework/roles/dlrn_promote/defaults/main.yml
  ci_framework/roles/dlrn_promote/files/centos9_antelope.yaml
  ci_framework/roles/dlrn_promote/meta/main.yml
  ci_framework/roles/dlrn_promote/molecule/default/converge.yml
  ci_framework/roles/dlrn_promote/molecule/default/molecule.yml
  ci_framework/roles/dlrn_promote/molecule/default/prepare.yml
  ci_framework/roles/dlrn_promote/tasks/check_for_previous_promotions.yml
  ci_framework/roles/dlrn_promote/tasks/check_promotion_criteria.yml
  ci_framework/roles/dlrn_promote/tasks/check_reported_jobs.yml
  ci_framework/roles/dlrn_promote/tasks/install.yml
  ci_framework/roles/dlrn_promote/tasks/main.yml
  ci_framework/roles/dlrn_promote/tasks/promote_hash.yml
  ci_framework/roles/dlrn_promote/tasks/query_criteria.yml
  docs/dictionary/en-custom.txt
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#584 Bump flavor for edpm baremetal job
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  zuul.d/edpm.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#581 Duplicate network-config-{override,template} functionality
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#587 Bump flavor for EDPM baremetal job.
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  zuul.d/edpm.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#585 Fix the value for cifmw_dlrn_promote_hash_in_promote_target
  ci_framework/roles/dlrn_promote/tasks/check_for_previous_promotions.yml
  ci_framework/roles/dlrn_promote/tasks/main.yml
Labels: approved, lgtm

#582 Automatically skip bootstrapped network cleanup if autohold
  ci/playbooks/multinode-authold.yml
  zuul.d/base.yaml
Labels: approved, lgtm

#590 Fix CoreDNS loading 127.0.0.1 as nameserver
  ci/playbooks/multinode-customizations.yml
Labels: approved, lgtm

#592 Use dlrnapi agg-status to fetch the CI results for a particular hash
  ci_framework/roles/dlrn_promote/tasks/check_reported_jobs.yml
Labels: approved, lgtm

#594 Fixing missing comma in autohold URI
  ci/playbooks/multinode-authold.yml
Labels: approved, lgtm

#591 Correct parameter value
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#596 Fix the file name for check_reported_jobs taskfile
  ci_framework/roles/dlrn_promote/tasks/check_reported_jobs.yml
Labels: approved, lgtm

#601 Removed Ignacio
  OWNERS
Labels: approved, lgtm

#600 Improvements to dlrn_promote playbook
  ci_framework/roles/dlrn_promote/tasks/check_promotion_criteria.yml
  ci_framework/roles/dlrn_promote/tasks/check_reported_jobs.yml
  ci_framework/roles/dlrn_promote/tasks/query_criteria.yml
Labels: approved, lgtm

#603 Fix the var name for cifmw_dlrn_promote_kerberos_auth
  ci_framework/roles/dlrn_promote/tasks/promote_hash.yml
Labels: approved, lgtm

#593 Fix RGW default value
  ci_framework/roles/cifmw_cephadm/defaults/main.yml
Labels: approved, lgtm

#586 New role: ci_network
  ci_framework/roles/ci_network/README.md
  ci_framework/roles/ci_network/defaults/main.yml
  ci_framework/roles/ci_network/meta/main.yml
  ci_framework/roles/ci_network/molecule/default/converge.yml
  ci_framework/roles/ci_network/molecule/default/molecule.yml
  ci_framework/roles/ci_network/molecule/default/prepare.yml
  ci_framework/roles/ci_network/tasks/apply.yml
  ci_framework/roles/ci_network/tasks/main.yml
  ci_framework/roles/ci_network/tasks/nm-cleanup.yml
  ci_framework/roles/ci_network/vars/main.yml
  docs/dictionary/en-custom.txt
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#608 Drop sandeep as he is moving org.
  OWNERS
Labels: approved, lgtm

#597 Add test dir under irrelevant_files list
  zuul.d/base.yaml
Labels: approved, lgtm

#607 Address comments from #586
  ci_framework/roles/ci_network/defaults/main.yml
  ci_framework/roles/ci_network/tasks/apply.yml
  ci_framework/roles/ci_network/tasks/main.yml
  ci_framework/roles/ci_network/tasks/validate.yml
  ci_framework/roles/ci_network/vars/main.yml
Labels: approved, lgtm

#606 Improve dlrn_promote role
  ci_framework/roles/dlrn_promote/README.md
  ci_framework/roles/dlrn_promote/defaults/main.yml
  ci_framework/roles/dlrn_promote/molecule/default/converge.yml
  ci_framework/roles/dlrn_promote/tasks/get_hash_from_commit.yaml
  ci_framework/roles/dlrn_promote/tasks/get_hashes.yml
  ci_framework/roles/dlrn_promote/tasks/main.yml
  ci_framework/roles/dlrn_promote/tasks/promote_hash.yml
  docs/dictionary/en-custom.txt
  zuul.d/base.yaml
Labels: approved, lgtm

#609 Allow to customize the inventory hostname for CRC
  ci_framework/hooks/playbooks/fetch_compute_facts.yml
  docs/source/usage/01_usage.md
Labels: approved, lgtm

#610 Fixing get_makefiles_env when special chars are in place
  ci_framework/plugins/modules/get_makefiles_env.py
Labels: approved, lgtm

#615 Remove the 3-replicas Galera configuration
  scenarios/centos-9/ci.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#595 Fix autoholds API url that differs from the UI one
  ci/playbooks/multinode-autohold.yml
  zuul.d/base.yaml
Labels: approved, lgtm

#618 Ensure we deploy EDPM
  ci_framework/roles/edpm_deploy/tasks/main.yml
  scenarios/centos-9/multinode-ci.yml
Labels: approved, lgtm

#611 Ensure we fetch generated parameters
  ci_framework/roles/artifacts/tasks/edpm.yml
  ci_framework/roles/artifacts/tasks/environment.yml
Labels: approved, lgtm

#614 Rename ee image var to RELATED_IMAGE_ANSIBLEEE_IMAGE_URL_DEFAULT
  ci/playbooks/build_runner_image.yml
Labels: approved, lgtm

#617 Correct typo in playbook hook launcher
  ci_framework/roles/run_hook/tasks/playbook.yml
Labels: approved, lgtm

#613 Make sure parameters directory exists on install_yamls role
  ci_framework/roles/install_yamls/tasks/main.yml
Labels: approved, lgtm

#616 Set DATAPLANE_GROWVOLS_ARGS for baremetal job
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: approved, lgtm

#557 Create cephfs volume that can be consumed by Manila
  ci_framework/playbooks/ceph.yml
  ci_framework/roles/cifmw_cephadm/README.md
  ci_framework/roles/cifmw_cephadm/defaults/main.yml
  ci_framework/roles/cifmw_cephadm/tasks/cephfs.yml
  docs/dictionary/en-custom.txt
Labels: approved, lgtm
