Repository openstack-k8s-operators/ci-framework, pull requests merged in 2023-04, with the labels that each got.

#94 Reorganize a bit the Makefile, add new targets
  Makefile
Labels: approved, lgtm

#92 Molecule fix avoiding 'failed to create tmp dir' error
  .config/molecule/config.yml
  .config/molecule/config_local.yml
  .config/molecule/config_podman.yml
Labels: approved, lgtm, ok-to-test

#95 Feature/libvirt manager role
  .zuul.d/collect-logs.yml
  .zuul.d/molecule-prepare.yml
  .zuul.d/molecule-test.yml
  .zuul.yaml
  ci_framework/roles/libvirt_manager/README.md
  ci_framework/roles/libvirt_manager/defaults/main.yml
  ci_framework/roles/libvirt_manager/meta/main.yml
  ci_framework/roles/libvirt_manager/molecule/default/converge.yml
  ci_framework/roles/libvirt_manager/molecule/default/molecule.yml
  ci_framework/roles/libvirt_manager/molecule/default/prepare.yml
  ci_framework/roles/libvirt_manager/molecule/deploy_edpm_compute/converge.yml
  ci_framework/roles/libvirt_manager/molecule/deploy_edpm_compute/molecule.yml
  ci_framework/roles/libvirt_manager/molecule/deploy_edpm_compute/prepare.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_edpm_compute.yml
  ci_framework/roles/libvirt_manager/tasks/main.yml
  ci_framework/roles/libvirt_manager/tasks/packages.yml
  ci_framework/roles/libvirt_manager/tasks/polkit_rules.yml
  ci_framework/roles/libvirt_manager/tasks/virsh_checks.yml
  ci_framework/roles/libvirt_manager/tasks/virtualization_prerequisites.yml
  ci_framework/roles/libvirt_manager/templates/80-libvirt-manage.rules.j2
  ci_framework/roles/libvirt_manager/vars/main.yml
  ci_framework/roles/test_deps/tasks/main.yml
  scenarios/centos-9/ci.yml
Labels: approved, lgtm

#93 Ensure we can re-run the script multiple times
  scripts/run_ansible_test
Labels: approved, lgtm

#99 Workaround gnupg2 issue
  containerfiles/Containerfile.ci
Labels: approved

#98 Adding new reviewer
  OWNERS
Labels: approved, lgtm

#100 Better workaround for the gnupg2 vs sha-1 issue
  containerfiles/Containerfile.ci
Labels: approved, lgtm

#102 Add environment exports to ci_make reproducer
  ci_framework/plugins/action/ci_make.py
  ci_framework/tests/integration/targets/make/tasks/main.yml
Labels: approved, lgtm

#103 Inject new role path in ansible
  USAGE.md
  ansible.cfg
  ci_framework/roles/use_install_yamls/defaults/main.yml
Labels: approved, lgtm

#105 Rename use_install_yamls role
  ci_framework/plugins/modules/generate_make_tasks.py
  ci_framework/roles/install_yamls/README.md
  ci_framework/roles/install_yamls/defaults/main.yml
  ci_framework/roles/install_yamls/meta/main.yml
  ci_framework/roles/install_yamls/molecule/default/converge.yml
  ci_framework/roles/install_yamls/molecule/default/molecule.yml
  ci_framework/roles/install_yamls/molecule/default/prepare.yml
  ci_framework/roles/install_yamls/tasks/.gitignore
  ci_framework/roles/install_yamls/tasks/main.yml
  ci_framework/roles/use_install_yamls/README.md
  deploy-edpm.yml
  scenarios/centos-9/install_yamls.yml
Labels: approved, lgtm

#107 Correct some wrong/bad behavior
  ci_framework/plugins/action/ci_make.py
  ci_framework/plugins/modules/generate_make_tasks.py
  ci_framework/roles/install_yamls/README.md
  ci_framework/roles/install_yamls/defaults/main.yml
  ci_framework/tests/integration/targets/make/tasks/main.yml
Labels: approved, lgtm

#109 Ensure we create the compute once we get RHOL/CRC
  ci_framework/playbooks/deploy-edpm.yml
  ci_framework/roles/libvirt_manager/tasks/main.yml
Labels: approved, lgtm

#113 Update CS9 cloud image url
  ci_framework/roles/libvirt_manager/defaults/main.yml
Labels: approved, lgtm

#111 Set minimal required version for ansible
  ansible-requirements.txt
Labels: approved, lgtm

#115 Ensure we have ansible log in known location
  ansible.cfg
Labels: approved, lgtm

#118 Adds storage bundle build
  ci_framework/roles/operator_build/README.md
  ci_framework/roles/operator_build/defaults/main.yml
  ci_framework/roles/operator_build/tasks/build.yml
  ci_framework/roles/operator_build/tasks/main.yml
Labels: approved, lgtm

#116 Remove "`" from task name
  ci_framework/plugins/modules/generate_make_tasks.py
Labels: approved, lgtm

#112 Add discover_latest_image role
  ci_framework/roles/discover_latest_image/README.md
  ci_framework/roles/discover_latest_image/defaults/main.yml
  ci_framework/roles/discover_latest_image/molecule/default/converge.yml
  ci_framework/roles/discover_latest_image/molecule/default/molecule.yml
  ci_framework/roles/discover_latest_image/molecule/default/prepare.yml
  ci_framework/roles/discover_latest_image/tasks/main.yml
  ci_framework/roles/libvirt_manager/defaults/main.yml
  ci_framework/roles/libvirt_manager/meta/main.yml
  deploy-edpm.yml
Labels: approved, lgtm

#110 Leverage install_yamls generated tasks in rhol_crc
  ci_framework/roles/rhol_crc/molecule/add_crc_creds/converge.yml
  ci_framework/roles/rhol_crc/molecule/add_crc_creds/prepare.yml
  ci_framework/roles/rhol_crc/molecule/default/converge.yml
  ci_framework/roles/rhol_crc/molecule/default/prepare.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/converge.yml
  ci_framework/roles/rhol_crc/molecule/install_yamls/prepare.yml
  ci_framework/roles/rhol_crc/tasks/install_yamls.yml
Labels: approved, lgtm

#117 Add basic inventory, extend ansible configuration
  ansible.cfg
  ci_framework/playbooks/logs.yml
  inventory.yml
Labels: approved, lgtm

#114 Enable artifacts generation and gathering
  ci_framework/playbooks/logs.yml
  ci_framework/roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#119 Refactore once more the main edpm-deploy.yml playbook
  ci_framework/playbooks/01-bootstrap.yml
  ci_framework/playbooks/02-infra.yml
  ci_framework/playbooks/03-build-packages.yml
  ci_framework/playbooks/04-build-containers.yml
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/playbooks/99-logs.yml
  ci_framework/playbooks/build-containers.yml
  ci_framework/playbooks/build-packages.yml
  ci_framework/playbooks/deploy-edpm.yml
  deploy-edpm.yml
Labels: approved, lgtm

#120 Cosmetic changes to the operator_build role
  ci_framework/roles/operator_build/tasks/build.yml
  ci_framework/roles/operator_build/tasks/main.yml
Labels: approved, lgtm

#106 Add git pre-push hook
  .githooks/pre-push
  CONTRIBUTING.md
  Makefile
Labels: approved, lgtm

#122 Pad index in filenames
  ci_framework/plugins/action/ci_make.py
  ci_framework/tests/integration/targets/make/tasks/main.yml
Labels: approved, lgtm

#123 Cleaning up some unused files, and consolidate PATH
  USAGE.md
  ci_framework/playbooks/01-bootstrap.yml
  ci_framework/playbooks/05-build-operators.yml
  ci_framework/roles/libvirt_manager/tasks/deploy_edpm_compute.yml
  ci_framework/roles/operator_build/files/.gitkeep
  ci_framework/roles/operator_build/handlers/main.yml
  ci_framework/roles/rhol_crc/tasks/install_yamls.yml
Labels: approved, lgtm

#124 Retry base image download
  ci_framework/roles/libvirt_manager/tasks/deploy_edpm_compute.yml
Labels: approved, lgtm

#125 Consolidate run_hook "playbook" tasks
  ci_framework/roles/run_hook/README.md
  ci_framework/roles/run_hook/tasks/playbook.yml
Labels: approved, lgtm

#127 Remove problematic lines in _skeleton_
  _skeleton_role_/defaults/main.yml.j2
Labels: approved, lgtm

#129 Update OWNERS
  OWNERS
Labels: approved, lgtm, needs-ok-to-test

#128 Add build_openstack_packages role
  ci_framework/roles/build_openstack_packages/README.md
  ci_framework/roles/build_openstack_packages/defaults/main.yml
  ci_framework/roles/build_openstack_packages/meta/main.yml
  ci_framework/roles/build_openstack_packages/molecule/default/converge.yml
  ci_framework/roles/build_openstack_packages/molecule/default/molecule.yml
  ci_framework/roles/build_openstack_packages/molecule/default/prepare.yml
  ci_framework/roles/build_openstack_packages/tasks/cleanup_dlrn.yml
  ci_framework/roles/build_openstack_packages/tasks/create_repo.yml
  ci_framework/roles/build_openstack_packages/tasks/install_dlrn.yml
  ci_framework/roles/build_openstack_packages/tasks/main.yml
  ci_framework/roles/build_openstack_packages/tasks/run_dlrn.yml
  ci_framework/roles/build_openstack_packages/templates/projects.ini.j2
  ci_framework/roles/build_openstack_packages/templates/run_dlrn.sh.j2
Labels: approved, lgtm

#130 Use an action plugin instead of a list of tasks
  ci_framework/plugins/README.md
  ci_framework/plugins/action/discover_latest_image.py
  ci_framework/roles/discover_latest_image/molecule/default/converge.yml
  ci_framework/roles/discover_latest_image/tasks/main.yml
  requirements.txt
  scripts/run_ansible_test
Labels: approved, lgtm

#132 Add registry_deploy role
  ci_framework/roles/registry_deploy/README.md
  ci_framework/roles/registry_deploy/defaults/main.yml
  ci_framework/roles/registry_deploy/meta/main.yml
  ci_framework/roles/registry_deploy/molecule/default/converge.yml
  ci_framework/roles/registry_deploy/molecule/default/molecule.yml
  ci_framework/roles/registry_deploy/molecule/default/prepare.yml
  ci_framework/roles/registry_deploy/tasks/main.yml
Labels: approved, lgtm

#136 Added playbook to dump zuul vars
  .zuul.d/collect-logs.yml
  .zuul.d/dump_zuul_vars.yml
  .zuul.d/e2e-run.yml
  .zuul.yaml
Labels: approved, lgtm

#137 Correct variable used for gating_repo location
  ci_framework/roles/build_openstack_packages/tasks/create_repo.yml
Labels: approved, lgtm

#139 Allow to pass an alternative image for golang
  ci_framework/roles/operator_build/README.md
  ci_framework/roles/operator_build/defaults/main.yml
  ci_framework/roles/operator_build/tasks/build.yml
Labels: approved, lgtm

#134 Allow ci_make to work with remote host
  ci_framework/plugins/action/ci_make.py
Labels: approved, lgtm

#101 Package builder container
  ci_framework/playbooks/02-infra.yml
  ci_framework/playbooks/03-build-packages.yml
  ci_framework/roles/pkg_build/README.md
  ci_framework/roles/pkg_build/defaults/main.yml
  ci_framework/roles/pkg_build/meta/main.yml
  ci_framework/roles/pkg_build/molecule/default/converge.yml
  ci_framework/roles/pkg_build/molecule/default/molecule.yml
  ci_framework/roles/pkg_build/molecule/default/prepare.yml
  ci_framework/roles/pkg_build/tasks/build.yml
  ci_framework/roles/pkg_build/tasks/cleanup.yml
  ci_framework/roles/pkg_build/tasks/main.yml
  ci_framework/roles/pkg_build/templates/containerfile.buildpkg.j2
  ci_framework/roles/pkg_build/templates/pkg_build_play.j2
  ci_framework/roles/pkg_build/vars/main.yml
Labels: approved, lgtm

#141 Introduce Zuul jobs directory structure
  .zuul.yaml
  ci/playbooks/collect-logs.yml
  ci/playbooks/dump_zuul_vars.yml
  ci/playbooks/e2e-prepare.yml
  ci/playbooks/e2e-run.yml
  ci/playbooks/molecule-prepare.yml
  ci/playbooks/molecule-test.yml
  zuul.d/jobs.yaml
  zuul.d/nodeset.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#138 Operator build plugin now outputs a results dictionary
  ci_framework/roles/operator_build/molecule/default/converge.yml
  ci_framework/roles/operator_build/tasks/build.yml
  ci_framework/roles/operator_build/tasks/clone.yml
  ci_framework/roles/operator_build/tasks/main.yml
  ci_framework/roles/operator_build/vars/main.yml
Labels: approved, lgtm

#144 Switch test_deps to repo_setup role
  ci_framework/roles/repo_setup/README.md
  ci_framework/roles/repo_setup/defaults/main.yml
  ci_framework/roles/repo_setup/tasks/configure.yml
  ci_framework/roles/repo_setup/tasks/install.yml
  ci_framework/roles/repo_setup/tasks/rhos_release.yml
  ci_framework/roles/test_deps/tasks/main.yml
Labels: approved, lgtm

#135 Add support for Zuul jobs in operator_build role
  ci_framework/roles/operator_build/README.md
  ci_framework/roles/operator_build/molecule/default/converge.yml
  ci_framework/roles/operator_build/tasks/build.yml
  ci_framework/roles/operator_build/tasks/clone.yml
  ci_framework/roles/operator_build/tasks/main.yml
  ci_framework/roles/operator_build/tasks/zuul_info.yml
  scenarios/centos-9/ci.yml
Labels: approved, lgtm

#145 Make generate_make_env module output install_yamls Makefile default values
  ci_framework/plugins/README.md
  ci_framework/plugins/modules/generate_make_env.py
  ci_framework/plugins/modules/get_makefiles_env.py
  ci_framework/roles/install_yamls/README.md
  ci_framework/roles/install_yamls/defaults/main.yml
  ci_framework/roles/install_yamls/molecule/default/converge.yml
  ci_framework/roles/install_yamls/tasks/main.yml
  ci_framework/tests/sanity/ignore.txt
Labels: approved, lgtm

#148 Fixing comments from PR#135
  ci_framework/roles/operator_build/molecule/default/converge.yml
  ci_framework/roles/operator_build/molecule/default/validate_outputs.yml
  ci_framework/roles/operator_build/tasks/build.yml
  ci_framework/roles/operator_build/tasks/main.yml
Labels: approved, lgtm

#143 Added support for content provider job
  ci/playbooks/collect-logs.yml
  ci/playbooks/content_provider/content_provider.yml
  ci/playbooks/content_provider/pre.yml
  ci/playbooks/content_provider/run.yml
  ci/playbooks/dump_zuul_vars.yml
  ci/playbooks/e2e-prepare.yml
  ci_framework/roles/operator_build/defaults/main.yml
  ci_framework/roles/operator_build/tasks/build.yml
  ci_framework/roles/registry_deploy/tasks/main.yml
  scenarios/centos-9/ci.yml
  scenarios/centos-9/content_provider.yml
  zuul.d/content_provider.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#149 Add operator src directory for usage in future deploy stages.
  ci_framework/roles/operator_build/molecule/default/validate_outputs.yml
  ci_framework/roles/operator_build/tasks/build.yml
Labels: approved, lgtm

#150 Add missing retries on pushing images to registry
  ci_framework/roles/operator_build/tasks/build.yml
Labels: approved, lgtm

#152 Introduce hook callback
  ci_framework/playbooks/02-infra.yml
  ci_framework/playbooks/03-build-packages.yml
  ci_framework/playbooks/04-build-containers.yml
  ci_framework/playbooks/05-build-operators.yml
  ci_framework/playbooks/06-deploy-edpm.yml
  ci_framework/roles/run_hook/README.md
  ci_framework/roles/run_hook/molecule/default/converge.yml
  ci_framework/roles/run_hook/molecule/default/prepare.yml
  ci_framework/roles/run_hook/tasks/playbook.yml
Labels: approved, lgtm

#153 New hook: deploy ceph using install_yamls target
  ci/playbooks/e2e-run.yml
  ci_framework/hooks/playbooks/ceph-deploy.yml
  ci_framework/plugins/action/ci_make.py
  ci_framework/tests/integration/targets/make/tasks/main.yml
  scenarios/centos-9/ci.yml
Labels: approved, lgtm
