Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-09, with the labels that each got.

#2220 [libvirt_manager] Adopt cloud-init usage while provisioning EL based vms
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/molecule/deploy_layout/cleanup.yml
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/molecule/deploy_layout/prepare.yml
  roles/libvirt_manager/tasks/create_cloud_init_iso.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/manage_vms.yml
  roles/libvirt_manager/templates/static_ip.j2
  roles/libvirt_manager/vars/main.yml
Labels: approved, lgtm, Ready For Review, cloud-init

#2290 Set nodeexporterimage via cifmw_update_containers_edpmnodeexporterimage
  docs/dictionary/en-custom.txt
  roles/update_containers/README.md
  roles/update_containers/defaults/main.yml
  roles/update_containers/templates/update_containers.j2
Labels: approved, lgtm, Ready For Review

#2224 Enable unique names for certain types of VMs
  docs/source/usage/01_usage.md
  reproducer-clean.yml
  reproducer.yml
  roles/ci_gen_kustomize_values/templates/bgp/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-common-nodeset-values/common-bgp-edpm-values.yaml.j2
  roles/ci_gen_kustomize_values/templates/common/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/common/edpm-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/shiftstack/edpm-nodeset-values/values.yaml.j2
  roles/devscripts/README.md
  roles/devscripts/molecule/check_cluster_status/prepare.yml
  roles/devscripts/molecule/check_cluster_status/tasks/test.yml
  roles/devscripts/tasks/110_check_ocp.yml
  roles/devscripts/tasks/310_prepare_overlay.yml
  roles/libvirt_manager/molecule/check_dns/converge.yml
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/molecule/deploy_layout/prepare.yml
  roles/libvirt_manager/molecule/generate_network_data/converge.yml
  roles/libvirt_manager/molecule/generate_network_data/vars/input.yml
  roles/libvirt_manager/molecule/generate_network_data/vars/scenarios.yml
  roles/libvirt_manager/molecule/ocp_layout/cleanup.yml
  roles/libvirt_manager/molecule/ocp_layout/converge.yml
  roles/libvirt_manager/molecule/ocp_layout/molecule.yml
  roles/libvirt_manager/molecule/ocp_layout/prepare.yml
  roles/libvirt_manager/molecule/ocp_layout/vars/net-def.yml
  roles/libvirt_manager/molecule/spine_leaf/converge.yml
  roles/libvirt_manager/molecule/spine_leaf/verify.yml
  roles/libvirt_manager/tasks/attach_interface.yml
  roles/libvirt_manager/tasks/clean_layout.yml
  roles/libvirt_manager/tasks/create_dns_records.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/generate_macs.yml
  roles/libvirt_manager/tasks/generate_networking_data.yml
  roles/libvirt_manager/tasks/manage_vms.yml
  roles/libvirt_manager/tasks/ocp_layout.yml
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
  roles/libvirt_manager/tasks/start_vms.yml
  roles/libvirt_manager/templates/inventory.yml.j2
  roles/reproducer/molecule/crc_layout/converge.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/ocp_layout.yml
  roles/reproducer/tasks/prepare_networking.yml
Labels: approved, lgtm, Ready For Review, github-experimental

#2288 Pin devscripts repo at working hash
  roles/devscripts/vars/main.yml
Labels: approved, lgtm, Ready For Review, github-experimental

#2267 Use cifmw_architecture_scenario to set proper automation file
  docs/source/usage/01_usage.md
  roles/reproducer/tasks/configure_controller.yml
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
  scenarios/reproducers/dt-osasinfra.yml
  scenarios/reproducers/va-pidone.yml
  zuul.d/architecture-jobs.yaml
Labels: approved, lgtm, Ready For Review

#2258 Introduce Ceph Upgrade tasks
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/ceph_upgrade.yml
Labels: approved, lgtm, Ready For Review

#2263 Allow to know what data were used
  roles/hci_prepare/tasks/load_parameters.yml
Labels: approved, lgtm, Ready For Review

#2236 Optimize ceph conf overrides
  roles/cifmw_cephadm/tasks/pre.yml
  roles/cifmw_cephadm/tasks/rgw.yml
  roles/cifmw_cephadm/templates/ceph_rgw.conf.j2
Labels: approved, lgtm, Ready For Review

#2292 Use cifmw_architecture_scenario to set proper automation file
  docs/source/usage/01_usage.md
  roles/reproducer/tasks/configure_controller.yml
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
  scenarios/reproducers/dt-osasinfra.yml
  scenarios/reproducers/va-pidone.yml
  zuul.d/architecture-jobs.yaml
Labels: approved, lgtm, Ready For Review

#2225 added nodeset value file for HCI
  roles/ci_gen_kustomize_values/templates/nfv-ovs-dpdk-sriov-hci/edpm-nodeset-values/values.yaml.j2
  scenarios/reproducers/dt-nfv-ovs-dpdk-sriov-hci.yml
Labels: approved, lgtm, Ready For Review

#2300 Ensure we don't hardcode "compute-0" anymore
  hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm, Ready For Review

#2296 Allow to NOT connect some VMs to the public network
  roles/libvirt_manager/molecule/generate_network_data/vars/scenarios.yml
  roles/libvirt_manager/tasks/generate_networking_data.yml
Labels: approved, lgtm, Ready For Review

#2289 Store update related repo_setup repos in update_repository
  playbooks/update.yml
Labels: approved, lgtm, Ready For Review

#2312 Add motd on controller-0
  roles/reproducer/molecule/crc_layout/converge.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/templates/motd.j2
Labels: approved, lgtm, Ready For Review, github-experimental

#2308 Add nodeset centos-9-xxl-2x-centos-9-crc-extracted-2-39-0-xxl
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#2319 nit: Correct typo in Makefile help output
  Makefile
Labels: approved, lgtm, Ready For Review

#2295 Introduce cifmw_test_operator_privileged parameter
  docs/dictionary/en-custom.txt
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2311 Add missing cifmw_architecture_automation_file
  playbooks/06-deploy-architecture.yml
Labels: approved, lgtm, Ready For Review

#2313 Don't harcode "compute-0" reference in hci_prepare
  roles/hci_prepare/tasks/load_parameters.yml
Labels: approved, lgtm, Ready For Review

#2316 Unskip no valid host whitebox neutron tempest plugin tests
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2320 Ensure we deepscrube between tests
  roles/libvirt_manager/molecule/deploy_layout/cleanup.yml
  roles/libvirt_manager/molecule/deploy_layout/prepare.yml
  roles/libvirt_manager/molecule/generate_network_data/tasks/test.yml
  roles/libvirt_manager/tasks/clean_layout.yml
  roles/libvirt_manager/tasks/storage_pool.yml
Labels: approved, lgtm, Ready For Review

#2324 Convert trigger action into reusable workflow
  .github/workflows/github-action-trigger-downstream-job-reusable-workflow.yaml
  .github/workflows/trigger-downstream-job.yaml
Labels: approved, lgtm, Ready For Review

#2326 Fixed the repo name in github workflow
  .github/workflows/trigger-downstream-job.yaml
Labels: approved, lgtm, Ready For Review

#2318 Do not add the unique ID to VM names in specific case
  roles/libvirt_manager/molecule/check_dns/converge.yml
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/molecule/generate_network_data/vars/scenarios.yml
  roles/libvirt_manager/molecule/spine_leaf/converge.yml
  roles/libvirt_manager/molecule/spine_leaf/verify.yml
  roles/libvirt_manager/tasks/generate_networking_data.yml
  roles/reproducer/molecule/crc_layout/converge.yml
Labels: approved, lgtm, Ready For Review, github-experimental

#2310 Ensure we can re-run the framework without issue on config_drive
  roles/config_drive/tasks/main.yml
  roles/libvirt_manager/tasks/create_vms.yml
Labels: approved, lgtm, Ready For Review

#2328 Correct how config_drive content is generated
  roles/config_drive/tasks/main.yml
  roles/config_drive/templates/user-data.j2
Labels: approved, lgtm, Ready For Review

#2169 Introduce control plane testing.
  roles/update/README.md
  roles/update/defaults/main.yml
  roles/update/files/continuous-test.sh
  roles/update/tasks/create_test_files.yml
  roles/update/tasks/main.yml
  roles/update/templates/control_plane_test_start.sh.j2
  roles/update/templates/control_plane_test_stop.sh.j2
  roles/update/templates/workload_launch_k8s.sh.j2
Labels: approved, lgtm, minor update, Ready For Review

#2329 Introduce DCN network-values template and job scenario parameters
  roles/ci_gen_kustomize_values/templates/dcn/network-values/values.yaml.j2
  scenarios/reproducers/va-dcn.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#2281 Add cifmw_set_openstack_containers_prefix_filter variable to set_openstack_cotaniners
  roles/set_openstack_containers/README.md
  roles/set_openstack_containers/defaults/main.yml
  roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm, Ready For Review

#2330 Enable "backup" for config_drive generated files
  roles/config_drive/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2303 Use single command to get operator pod name and their env variables
  roles/set_openstack_containers/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2331 Trigger libvirt_manager molecule on config_drive changes
  ci/config/molecule.yaml
  roles/config_drive/defaults/main.yml
  zuul.d/molecule.yaml
Labels: approved, lgtm, Ready For Review

#2335 Add a comment to sushy_driver SSH pub key
  reproducer-clean.yml
  roles/libvirt_manager/tasks/create_cloud_init_iso.yml
  roles/sushy_emulator/tasks/collect_details.yml
Labels: approved, lgtm, Ready For Review

#2327 Ensure we configure any "managed" VM
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/manage_vms.yml
Labels: approved, lgtm, Ready For Review, github-experimental

#2336 Skip neutron SGL test blocking promotion
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2276 [polarion] Each result dir equals polarion test run
  roles/polarion/README.md
  roles/polarion/defaults/main.yml
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2333 Use cifmw_architecture_scenario to set proper automation file
  docs/source/usage/01_usage.md
  roles/reproducer/tasks/configure_controller.yml
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
  scenarios/reproducers/dt-osasinfra.yml
  scenarios/reproducers/va-pidone.yml
Labels: approved, lgtm, Ready For Review, github-experimental

#2302 Libvirt manager/dont add blank unmanaged vms to inventory
  roles/libvirt_manager/tasks/generate_networking_data.yml
Labels: approved, lgtm, Ready For Review

#2304 Use if instead of elif to set container overrides
  roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm, Ready For Review

#2243 Remove checking if commit in multiple PRs
  .github/workflows/review-ready-label.yml
Labels: approved, lgtm, Ready For Review

#2332 Use the VM UUID instead of some other randomly value
  roles/libvirt_manager/tasks/create_cloud_init_iso.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
Labels: approved, lgtm, Ready For Review

#2342 Use cifmw_architecture_scenario file in set va scenario
  roles/kustomize_deploy/molecule/flexible_loop/converge.yml
Labels: approved, lgtm, Ready For Review

#2341 Rework inventory generation
  roles/libvirt_manager/tasks/deploy_layout.yml
Labels: approved, lgtm, Ready For Review

#1984 Multi-node and multi-cell netconfig fixes
  zuul.d/adoption.yaml
Labels: approved, lgtm, Ready For Review

#2305 [test-operator] Add the `wait_timeout` parameter to cleanup tasks
  roles/test_operator/tasks/cleanup.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#2345 Fix polarion result dir filtering
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2347 Run fdb aging tests in single thread only
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2339 Move Tobiko tests to be performed last.
  .gitignore
  roles/test_operator/tasks/main.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#2285 Introduce two new playbooks for adoption infra
  create-infra.yml
  deploy-ocp.yml
  playbooks/adoption/infra.yml
  playbooks/adoption/network.yml
  playbooks/adoption/pre.yml
  playbooks/unique-id.yml
  reproducer.yml
  scenarios/adoption/hci.yml
Labels: approved, lgtm, Ready For Review

#2264 NFV update workload scripts changes
  roles/update/templates/workload_launch.sh.j2
Labels: approved, lgtm, minor update, Ready For Review

#2351 Revert "Run fdb aging tests in single thread only"
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2356 Exclude neutron whitebox test_ovn_fdb tests
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm

#2358 Update single-thread tests for neutron whitebox plugin
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2359 Fix tempest container tag for nested-crc-baremetal jobs
  zuul.d/edpm_periodic.yaml
Labels: approved, lgtm, Ready For Review

#2360 Neutron whitebox tests default to single thread
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2344 Add support for NFV HCI scenario
  hooks/playbooks/ceph-bm.yml
  playbooks/ceph.yml
  roles/ci_gen_kustomize_values/templates/nfv-ovs-dpdk-sriov-hci/edpm-nodeset-values/values.yaml.j2
  scenarios/reproducers/dt-nfv-ovs-dpdk-sriov-hci.yml
Labels: approved, lgtm, Ready For Review

#2322 Rename extraMounts to extraConfigmapsMounts
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2362 [tempest] Set dhcp_domain to match nova-operator defaults
  roles/tempest/vars/main.yml
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2269 Profile molecule jobs
  ci/playbooks/molecule-test.yml
Labels: approved, lgtm, Ready For Review

#2227 [reproducer] Enable configuration of NTP service on controller-0
  docs/source/usage/01_usage.md
  galaxy.yml
  requirements.yml
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, Ready For Review, github-experimental

#2368 Revert "[reproducer] Enable configuration of NTP service on controller-0"
  docs/source/usage/01_usage.md
  galaxy.yml
  requirements.yml
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, Ready For Review

#2278 Add logging for `setup_tests` and `setup_molecule` targets in Makefile
  Makefile
Labels: approved, lgtm, Ready For Review

#2235 [Reproducer] Add support for disabling ocp overlays
  docs/source/usage/01_usage.md
  roles/devscripts/tasks/300_post.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/ocp_layout.yml
  roles/reproducer/tasks/ocp_layout.yml
Labels: approved, lgtm, Ready For Review

#2242 [VA HCI]Adds cindervolume and manilashare names for update_containers
  roles/update_containers/defaults/main.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm, Ready For Review

#2372 Run trigger job on net_map changes
  zuul.d/trigger_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2357 Fix rbd pools trash purge scheduling
  playbooks/ceph.yml
  roles/cifmw_cephadm/tasks/pools.yml
Labels: approved, lgtm, Ready For Review

#2376 Adding toolbelt catalog metadata file
  docs/toolbelt-catalog.yaml
Labels: approved, lgtm, Ready For Review

#2301 Configure Ceph RGW with a object storage network
  ci/playbooks/files/networking-env-definition.yml
  playbooks/ceph.yml
  roles/cifmw_cephadm/tasks/check_vip.yml
  scenarios/reproducers/networking-definition.yml
Labels: approved, lgtm, Ready For Review

#2364 [test-operator] Add wait_timeout for removing CRD instances in test-o…
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: approved, lgtm, Ready For Review

#1841 [networking_mapper] Add the network to ranges validation message
  plugins/module_utils/net_map/exceptions.py
  plugins/module_utils/net_map/networking_definition.py
  tests/unit/module_utils/net_map/test_networking_definitions_group_template.py
Labels: approved, lgtm, Ready For Review, github-experimental

#2355 [18.0.0-proposed] Add trigger_branch_name to the trigger job
  zuul.d/trigger_jobs.yaml
Labels: approved, lgtm, Ready For Review, github-experimental

#2380 Link title needs quotes
  docs/toolbelt-catalog.yaml
Labels: approved, lgtm, Ready For Review

#2385 Gather ssh private key from the hostvars in ceph playbook
  playbooks/ceph.yml
Labels: approved, lgtm, Ready For Review

#2390 Fix molecule - add swift network
  roles/ci_gen_kustomize_values/molecule/default/files/3-ocp-net-def.yml
Labels: approved, lgtm, Ready For Review

#2383 Only gather required ansible facts
  ci/playbooks/molecule-test.yml
Labels: approved, lgtm, Ready For Review

#2395 Use Ceph monitoring (not RGW) network for Dashboard
  playbooks/ceph.yml
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/dashboard/configure_dashboard_backends.yml
  roles/cifmw_cephadm/tasks/dashboard/validation.yml
  roles/cifmw_cephadm/templates/ceph_monitoring_stack.yml.j2
Labels: approved, lgtm, Ready For Review

#2405 Use Ceph monitoring (not RGW) network for Dashboard
  playbooks/ceph.yml
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/dashboard/configure_dashboard_backends.yml
  roles/cifmw_cephadm/tasks/dashboard/validation.yml
  roles/cifmw_cephadm/templates/ceph_monitoring_stack.yml.j2
Labels: approved, lgtm, Ready For Review

#2403 Fix EDPM instances IPs for VLAN nets
  roles/ci_gen_kustomize_values/templates/common/edpm-nodeset-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2407 Fix ci_gen_kustomize_values role name in files
  zuul.d/trigger_jobs.yaml
Labels: approved, lgtm, Ready For Review
