Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-11, with the labels that each got.

#2503 [ci_netconfig] Remove unused and outdated role
  ci/config/molecule.yaml
  roles/ci_netconfig/README.md
  roles/ci_netconfig/defaults/main.yml
  roles/ci_netconfig/meta/main.yml
  roles/ci_netconfig/molecule/default/converge.yml
  roles/ci_netconfig/molecule/default/molecule.yml
  roles/ci_netconfig/molecule/default/prepare.yml
  roles/ci_netconfig/tasks/cleanup.yml
  roles/ci_netconfig/tasks/main.yml
  roles/ci_netconfig/templates/netconfig.yml.j2
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#2504 [ci_metallb] Remove unused and outdated role
  ci/config/molecule.yaml
  roles/ci_metallb/README.md
  roles/ci_metallb/defaults/main.yml
  roles/ci_metallb/meta/main.yml
  roles/ci_metallb/molecule/default/converge.yml
  roles/ci_metallb/molecule/default/molecule.yml
  roles/ci_metallb/molecule/default/prepare.yml
  roles/ci_metallb/tasks/cleanup.yml
  roles/ci_metallb/tasks/main.yml
  roles/ci_metallb/tasks/metallb_k8s_install.yml
  roles/ci_metallb/templates/ipaddresspools.yaml.j2
  roles/ci_metallb/templates/l2advertisements.yaml.j2
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#2506 Specify Ceph configuration file path for Cinder backup
  roles/ci_dcn_site/templates/service-values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2511 Remove `rebtoor` from approvers
  OWNERS
Labels: approved, lgtm, Ready For Review

#2512 Remove cjeanner from OWNERS approvers
  OWNERS
Labels: approved, lgtm, Ready For Review

#2495 Enable ironic testing in component lines
  ci/playbooks/bootstrap-networking-mapper.yml
  docs/source/usage/01_usage.md
  playbooks/02-infra.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm, Ready For Review

#2518 Use multiple Ceph secrets in ci_dcn_site role
  roles/ci_dcn_site/tasks/az.yml
  roles/ci_dcn_site/tasks/post-ceph.yml
  roles/ci_dcn_site/templates/ceph_secerts.yaml.j2
  roles/ci_dcn_site/templates/edpm_extra_mounts.yaml.j2
  roles/ci_dcn_site/templates/service-values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2521 Skip ironic tests which need to be fixed
  roles/test_operator/files/list_skipped.yml
Labels: approved, lgtm, Ready For Review

#2526 Set the revision of ansible-podman-collections to 'main'
  galaxy.yml
Labels: approved, lgtm, Ready For Review

#2529 Add watcher-operator to the content provider base job
  zuul.d/base.yaml
Labels: approved, lgtm, Ready For Review

#2530 Add more Ceph OSDs for adoption context
  scenarios/adoption/hci.yml
Labels: approved, lgtm, Ready For Review

#2531 Create S3 openstack user when Ceph RGW is deployed
  roles/cifmw_cephadm/tasks/ceph_cli.yml
  roles/cifmw_cephadm/tasks/post.yml
Labels: approved, lgtm, Ready For Review

#2523 roles/ci_dcn_site: Add multicell to DCN DT
  roles/ci_dcn_site/tasks/post-ceph.yml
  roles/ci_dcn_site/templates/deployment/values.yaml.j2
  roles/ci_dcn_site/templates/service-values.yaml.j2
  roles/ci_dcn_site/templates/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2536 trivial: fix ironic test name
  roles/test_operator/files/list_skipped.yml
Labels: approved, lgtm, Ready For Review

#2522 [ci_dcn_site] Add support for network availability zones
  roles/ci_dcn_site/defaults/main.yml
  roles/ci_dcn_site/templates/edpm-pre-ceph/nodeset/values.yaml.j2
  roles/ci_dcn_site/templates/service-values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2544 [Shiftstack]Support proxy
  roles/shiftstack/README.md
  roles/shiftstack/tasks/cleanup.yml
  roles/shiftstack/tasks/deploy_shiftstackclient_pod.yml
  roles/shiftstack/tasks/pre_test_shiftstack.yml
Labels: approved, lgtm, Ready For Review

#2547 Add scenario for OVS-DPDK
  scenarios/reproducers/va-nfv-ovs-dpdk.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#2481 Add osasinfra-ipv6 network-values template
  reproducer.yml
  roles/ci_gen_kustomize_values/templates/osasinfra-ipv6/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2546 [kustomize_deploy] Include symlinks when user kustomize dir is set
  roles/kustomize_deploy/tasks/generate_base64_patches_from_tree.yml
Labels: approved, lgtm, Ready For Review

#2543 Check if openstack user exists before trying to create it
  roles/cifmw_cephadm/tasks/post.yml
Labels: approved, lgtm, Ready For Review

#2554 Fix interface aggregation in switch_config
  roles/switch_config/tasks/junos_config.yml
Labels: bug, lgtm, do-not-merge/hold, do-not-merge/contains-merge-commits, Ready For Review

#2557 Set storage_availability_zone for DCN cinder backup
  roles/ci_dcn_site/templates/service-values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2550 multinode: Add adoption vars for osp repos
  zuul.d/adoption.yaml
Labels: approved, lgtm, Ready For Review

#2564 Skip vlan transparent tests until there is a fix
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2566 Kuttl multinode: bump the timeout
  zuul.d/kuttl_multinode.yaml
Labels: approved, lgtm, Ready For Review

#2567 Expose new parameter expectedFailuresList
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2553 [polarion] Allow users pass extra custom-fields
  roles/polarion/README.md
  roles/polarion/defaults/main.yml
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2569 Exclude watcher-operator-index- image in env_op_images role
  roles/env_op_images/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2555 Add uni alpha adoption network values
  roles/ci_gen_kustomize_values/templates/uni01alpha-adoption/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2570 Enable sushy-emulator in create-infra.yml
  create-infra.yml
  roles/adoption_osp_deploy/tasks/main.yml
  roles/podman/tasks/main.yml
  roles/sushy_emulator/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2532 Add task for security tlse
  roles/validations/tasks/security/invoke_tlse_playbooks.yml
Labels: approved, lgtm, Ready For Review

#2577 Add possibility to run Tobiko in debug mode
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review
