Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-06, with the labels that each got.

#1806 Use the cifmw venv to run VA validations
  Makefile
  ci/playbooks/architecture/run.yml
  ci/playbooks/architecture/validate-architecture.yml
  zuul.d/architecture-jobs.yaml
Labels: approved, lgtm, Ready For Review

#1761 Add additional listen-address to CRC dnsmasq service
  ci/playbooks/multinode-customizations.yml
Labels: approved, lgtm, Ready For Review

#1583 Integrate update_containers in validated architecture role
  playbooks/06-deploy-architecture.yml
Labels: approved, lgtm, Ready For Review

#1791 Add override-checkout option to cifmw_reproducer_default_repositories
  roles/reproducer/tasks/default_repositories.yml
Labels: approved, lgtm, Ready For Review

#1807 nit: Update ctx make targets to be portable
  Makefile
Labels: approved, lgtm, Ready For Review

#1811 Ensure local _cifmw_networking_mapper_definition fact is empty
  roles/networking_mapper/tasks/main.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1795 Add missing 'https://' to cifmw_ceph_rgw_keystone_ep
  roles/cifmw_cephadm/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1805 Add support to run IT tests in MacOS and arm64
  tests/integration/targets/kustomize/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1782 [ci_gen_kustomize] Preserve additional non ConfigMap manifests
  .pre-commit-config.yaml
  plugins/filter/to_nice_yaml_all.py
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
  roles/ci_gen_kustomize_values/tasks/generate_values.yml
  roles/ci_gen_kustomize_values/vars/main.yml
Labels: approved, lgtm, Ready For Review

#1814 sushy-emulator podman - restart_policy: on-failure
  roles/sushy_emulator/tasks/create_container.yml
Labels: approved, lgtm, Ready For Review

#1778 Fix Mountpath for installation-volume
  roles/shiftstack/templates/shiftstackclient_pod.yml.j2
Labels: approved, lgtm, needs-ok-to-test, Ready For Review

#1764 Create new nodeset of 2.36 (OCP 4.14)
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#1808 [anisble_test] Add retries to ansible galaxy install
  scripts/run_ansible_test
Labels: approved, lgtm, Ready For Review

#1809 [rhol_crc]Set default version of CRC deployed
  roles/rhol_crc/README.md
  roles/rhol_crc/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1797 Change to hostname rather than IP for validations check node
  roles/validations/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1819 Allow cifmw_use_lvms in the reproducer variables file
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, Ready For Review

#1823 Fix small typo
  roles/openshift_adm/tasks/api_cert.yml
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1827 Add retries/delays when applying LVMS manifests
  roles/ci_lvms_storage/tasks/main.yml
  roles/ci_lvms_storage/tasks/status.yml
  roles/ci_lvms_storage/tasks/test.yml
Labels: approved, lgtm, Ready For Review

#1825 Remove conflicting and useless parameter
  scenarios/reproducers/va-common.yml
Labels: approved, lgtm, Ready For Review

#1833 Newer CentOS image converge with RHEL image
  scenarios/reproducers/3-nodes.yml
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
  scenarios/reproducers/external-ceph.yml
  scenarios/reproducers/va-common.yml
Labels: approved, lgtm, Ready For Review

#1804 polarion: update the usage of cifmw_polarion_update_testcases
  roles/polarion/README.md
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1834 De-dup task name
  roles/openshift_adm/tasks/api_cert.yml
Labels: approved, lgtm, needs-ok-to-test, Ready For Review

#1836 Introduce new cifmw_nolog global parameter
  docs/source/usage/01_usage.md
  roles/reproducer/tasks/ci_job.yml
  roles/reproducer/tasks/configure_architecture.yml
  roles/reproducer/tasks/main.yml
  roles/run_hook/tasks/playbook.yml
Labels: approved, lgtm, Ready For Review

#1839 dnsmasq - Enable Router Advertisements if v6 range
  roles/dnsmasq/templates/network.conf.j2
Labels: approved, lgtm, Ready For Review, ipv6

#1837 [networking_mapper] Make null templates behave like an empty one
  plugins/module_utils/net_map/networking_definition.py
Labels: approved, lgtm, Ready For Review

#1818 [ci_gen_kustomize-values] Support extra manifests in b64 patches
  roles/ci_gen_kustomize_values/filter_plugins/cifmw_gen_kustomize_values_b64_combine.py
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
Labels: approved, lgtm, Ready For Review

#1815 Get OpenStackControlPlane to update the OpenStackVersion
  playbooks/06-deploy-architecture.yml
  roles/edpm_prepare/tasks/kustomize_and_deploy.yml
  roles/edpm_prepare/tasks/main.yml
  roles/update_containers/defaults/main.yml
  roles/update_containers/molecule/default/converge.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: approved, lgtm, Ready For Review

#1843 Fix image pushing to local registry
  ci/playbooks/edpm_build_images/edpm_build_images_content_provider.yaml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1844 Add multinode-tempest job to ci-framework pipeline
  zuul.d/project-templates.yaml
Labels: approved, lgtm, Ready For Review

#1790 [test-operator] Remove ntp_extra_image
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1730 Update some jobs to CRC 2.36 (OCP4.15)
  docs/source/cookbooks/zuul-job-nodeset.md
  zuul.d/kuttl_multinode.yaml
  zuul.d/podified_multinode.yaml
  zuul.d/tempest_multinode.yaml
Labels: approved, lgtm, Ready For Review, 4.15 Migration

#1799 Move and add retries to ci_local_storage
  playbooks/06-deploy-architecture.yml
  roles/ci_local_storage/tasks/fetch_names.yml
Labels: approved, lgtm, Ready For Review

#1840 Fix bgp_dt01 templates
  roles/ci_gen_kustomize_values/templates/bgp_dt01/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#1822 [os_must_gather] Add SOS_DECOMPRESS environment variable
  roles/os_must_gather/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1828 Skip validations in edpm deploy for arch deployment
  playbooks/06-deploy-edpm.yml
Labels: approved, lgtm, Ready For Review

#1798 Add tasks to serve gating repo over content provider
  roles/build_openstack_packages/README.md
  roles/build_openstack_packages/defaults/main.yml
  roles/build_openstack_packages/tasks/create_repo.yml
  roles/build_openstack_packages/tasks/serve_gating_repo.yml
  roles/repo_setup/tasks/main.yml
  roles/repo_setup/tasks/populate_gating_repo.yml
Labels: approved, lgtm, Ready For Review

#1159 Set srbac by default
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1851 [artifacts] Fix undefined var when compute group is missing
  roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm, Ready For Review

#1683 Add nodeset and job config for multicell
  zuul.d/adoption.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#1848 uni01alpha - update network-values values.j2 for ironic
  roles/ci_gen_kustomize_values/templates/uni01alpha/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review, uni01alpha

#1847 Use DataPlaneService.DataSources
  roles/hci_prepare/templates/dpservice-nova-custom-ceph.yml.j2
Labels: approved, lgtm, Ready For Review

#1816 Fixed validate-architecture zuul job
  ci/playbooks/architecture/run.yml
  ci/playbooks/architecture/validate-architecture.yml
  zuul.d/architecture-jobs.yaml
Labels: approved, lgtm, Ready For Review

#1861 remove `psathyan` from OWNERS file
  OWNERS
Labels: approved, lgtm, Ready For Review

#1860 No group in inventory for `managed: false` vms.
  roles/libvirt_manager/templates/all-inventory.yml.j2
Labels: approved, lgtm, Ready For Review, uni01alpha

#1863 Hooks for bootstrapping ironic
  hooks/playbooks/ironic_enroll_nodes.yml
  hooks/playbooks/ironic_flavor.yml
  hooks/playbooks/ironic_network.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1864 test_operator/tempest: auth.tempest_roles empty by default
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1854 Patch network operator for OCP 4.15
  roles/openshift_setup/tasks/main.yml
  roles/openshift_setup/tasks/patch_network_operator.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review, 4.15 Migration

#1869 Add delorean repo filename var to dlrn_promote
  roles/dlrn_promote/README.md
  roles/dlrn_promote/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1779 [networking_mapper] Fix the way ranges are combined in group templates
  plugins/module_utils/net_map/networking_definition.py
Labels: approved, lgtm, Ready For Review, ipv6

#1846 Change iscsid login timeout
  roles/devscripts/templates/iscsi.j2
Labels: approved, lgtm, Ready For Review

#1870 Use host_ip in _sushy_url
  roles/sushy_emulator/tasks/create_container.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1867 Converge namespace for hooks
  hooks/playbooks/cinder_multiattach_volume_type.yml
  hooks/playbooks/control_plane_hci_pre_deploy.yml
  hooks/playbooks/control_plane_ironic.yml
  hooks/playbooks/fetch_compute_facts.yml
  hooks/playbooks/manila_create_default_resources.yml
  hooks/playbooks/rabbitmq_tuning.yml
  hooks/playbooks/restart_nova_scheduler.yml
  hooks/playbooks/templates/config_ceph_backends.yaml.j2
  roles/run_hook/README.md
  roles/run_hook/tasks/playbook.yml
Labels: approved, lgtm, Ready For Review

#1871 Expose cifmw_repo_setup_dlrn_url from repo-setup-get-hash utility
  roles/repo_setup/tasks/artifacts.yml
Labels: approved, lgtm

#1872 Use component commit.yaml url to promote a particular component
  roles/dlrn_promote/tasks/get_hashes.yml
Labels: approved, lgtm, Ready For Review

#1855 Use tlse in adoption standalone no ceph job
  zuul.d/adoption.yaml
Labels: approved, lgtm, Ready For Review

#1874 Pass dlrn url without commits.yml as commit_url for component
  roles/dlrn_promote/tasks/get_hashes.yml
Labels: approved, lgtm, Ready For Review

#1862 Switch back public network to be not shared by default
  roles/os_net_setup/defaults/main.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1732 nat64-appliance integration in the reproducer
  reproducer-clean.yml
  roles/nat64_appliance/tasks/cleanup.yml
  roles/nat64_appliance/tasks/deploy.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/tasks/nat64_appliance.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1859 Add support for uni07eta in ci_gen_kustomize_values
  roles/ci_gen_kustomize_values/templates/uni07eta/network-values/values.yaml.j2
Labels: approved, lgtm, ok-to-test, Ready For Review

#1800 Build os-net-config package and serve gating repo on compute
  ci/playbooks/tcib/run.yml
  ci/playbooks/tcib/tcib.yml
  hooks/playbooks/fetch_compute_facts.yml
  roles/build_openstack_packages/defaults/main.yml
  scenarios/centos-9/tcib.yml
Labels: approved, lgtm, Ready For Review

#1866 Add scaledown validator
  roles/validations/defaults/main.yml
  roles/validations/tasks/edpm/scaledown.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1876 Enforce some kind of timeout for selected tasks
  roles/openshift_adm/tasks/shutdown.yml
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: approved, lgtm, Ready For Review

#1881 Revert "Enforce some kind of timeout for selected tasks"
  roles/openshift_adm/tasks/shutdown.yml
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: approved, lgtm, Ready For Review

#1849 Rename OSDPS play to playbookContents
  roles/validations/tasks/edpm/hugepages_and_reboot.yml
Labels: approved, Ready For Review

#1842 Fix sushy_emulator integration in reproducer
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1829 Update adoption and base to crc 2.36(OCP 4.15)
  zuul.d/adoption.yaml
  zuul.d/base.yaml
Labels: approved, lgtm, 4.15 Migration

#1830 Update edpm, multinode and e2e to crc 2.36(OCP 4.15)
  zuul.d/edpm.yaml
  zuul.d/edpm_multinode.yaml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm, Ready For Review, 4.15 Migration

#1879 Remove change_message from zuul parameters
  ci/playbooks/dump_zuul_data.yml
Labels: approved, lgtm, Ready For Review

#1883 test_operator: more tempest-related SRBAC keyword
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1889 Add includepkgs into yum_repository call
  roles/reproducer/tasks/configure_computes.yml
Labels: approved, lgtm, Ready For Review

#1886 hook ironic_network - neutron availability zone
  hooks/playbooks/ironic_network.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1826 Drop unused dataplane vars
  roles/edpm_deploy/README.md
  roles/edpm_kustomize/molecule/default/prepare.yml
  roles/install_yamls/molecule/default/converge.yml
  tests/integration/targets/make/files/get_makefiles_env/expected_variables_values.yml
  tests/integration/targets/make/files/get_makefiles_env/makefiles/Makefile
Labels: approved, lgtm, Ready For Review

#1877 Leverage async for devscripts role feedback
  roles/devscripts/README.md
  roles/devscripts/defaults/main.yml
  roles/devscripts/tasks/cleanup.yml
  roles/devscripts/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1894 nit: Add hjensas as reviewer for the project
  OWNERS
Labels: approved, lgtm, Ready For Review

#1878 Can't use ULA addresses in NAT64
  roles/nat64_appliance/defaults/main.yml
  roles/nat64_appliance/files/elements/nat64-router/static/usr/local/sbin/configure-nat64
  roles/nat64_appliance/molecule/default/converge.yml
  roles/nat64_appliance/templates/config-data.j2
  roles/nat64_appliance/templates/ipv6_network.xml.j2
Labels: approved, lgtm, Ready For Review, ipv6

#1897 Ensure we install tmux
  roles/ci_setup/vars/main.yml
  roles/ci_setup/vars/redhat.yml
Labels: approved, lgtm, Ready For Review

#1899 Remove wrong templated ovn interfaces that are no longer needed
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/service-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk/service-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/sriov/service-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#1901 manila default share type: enable snapshot extra spec
  hooks/playbooks/manila_create_default_resources.yml
Labels: approved, lgtm

#1887 Move Tofu resource creation to hooks dir
  hooks/playbooks/run_tofu.yml
  roles/tofu/tasks/plan.yml
  roles/tofu/tasks/prepare.yml
Labels: approved, lgtm, va-2, Ready For Review

#1900 increase cpu/ram specs for ocp nodes in va-hci scenario
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm, Ready For Review

#1821 use UUIDS while configuring rgw as objectstore
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/configure_object.yml
  roles/cifmw_cephadm/tasks/pre.yml
Labels: approved, lgtm, Ready For Review

#1801 dnsmasq - use dhcp-hostdir
  roles/dnsmasq/tasks/configure.yml
  roles/dnsmasq/tasks/manage_host.yml
  roles/dnsmasq/templates/cifmw-dnsmasq.conf.j2
Labels: approved, lgtm, Ready For Review

#1895 Add missing var in the README
  roles/update_containers/README.md
Labels: approved, lgtm, Ready For Review

#1898 Ensure cifmw_network_dnsmasq_config isn't used
  roles/ci_network/README.md
  roles/reproducer/tasks/validations.yml
Labels: approved, lgtm, Ready For Review

#1885 [tcib]Use inner ansible vars to expose dlrn md5 hash
  ci/playbooks/tcib/run.yml
  ci/playbooks/tcib/tcib.yml
  zuul.d/tcib.yaml
Labels: approved, lgtm, Ready For Review

#1884 Use update_containers role to update openstack services container image
  ci/playbooks/build_runner_image.yml
  roles/edpm_prepare/tasks/kustomize_and_deploy.yml
  roles/edpm_prepare/tasks/main.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/templates/content-provider.yml.j2
  roles/update_containers/templates/update_containers.j2
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: approved, lgtm, Ready For Review

#1893 Move integration jobs to update_containers role
  scenarios/centos-9/edpm_periodic.yml
  zuul.d/edpm_periodic.yaml
  zuul.d/tempest_periodic.yaml
Labels: approved, lgtm, Ready For Review

#1911 Stop hard-coding the framework path
  roles/reproducer/tasks/ci_job.yml
  roles/reproducer/tasks/configure_architecture.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/tasks/push_code.yml
  roles/reproducer/templates/content-provider.yml.j2
Labels: approved, lgtm, Ready For Review

#1915 Ensure we don't try to set resources via dev-scripts
  roles/reproducer/molecule/ocp_validations/converge.yml
  roles/reproducer/molecule/ocp_validations/vars/scenarios.yml
  roles/reproducer/tasks/ocp_layout.yml
  roles/reproducer/tasks/ocp_layout_assertions.yml
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm, validation, Ready For Review

#1906 Dnsmasq manage host dual stack
  roles/dnsmasq/README.md
  roles/dnsmasq/molecule/default/converge.yml
  roles/dnsmasq/tasks/manage_host.yml
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
  roles/reproducer/tasks/ocp_layout.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1912 Add extra-disks to va1 scenario file
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm, Ready For Review

#1913 Donot filter cifmw_update_containers_registry only for reproducer job
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/templates/content-provider.yml.j2
Labels: approved, lgtm, Ready For Review

#1917 nit: Fix typo in matcher
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1904 Ensure virtqemud-sock is present before cleaning
  roles/libvirt_manager/molecule/deploy_layout/prepare.yml
  roles/libvirt_manager/tasks/clean_layout.yml
Labels: approved, lgtm, validation, Ready For Review

#1926 Switch to dhcp-hostsfile
  roles/dnsmasq/tasks/manage_host.yml
  roles/dnsmasq/templates/cifmw-dnsmasq.conf.j2
Labels: approved, lgtm, Ready For Review

#1920 Change the python script shebang to a sane default
  plugins/action/ci_kustomize.py
  plugins/action/ci_net_map.py
  plugins/filter/reproducer_gerrit_infix.py
  plugins/filter/reproducer_refspec.py
  plugins/filter/to_nice_yaml_all.py
  roles/ci_gen_kustomize_values/filter_plugins/cifmw_gen_kustomize_values_b64_combine.py
  roles/ci_nmstate/filter_plugins/ci_nmstate_map_instance_nets.py
  roles/ci_nmstate/library/ci_nmstate_apply_state.py
  roles/kustomize_deploy/filter_plugins/ci_kustomize_deploy_combine_base64_patch_dict.py
  scripts/create_role_molecule.py
Labels: approved, lgtm, Ready For Review

#1927 nit: Ensure dnsmasq configuration is really cleaned
  roles/dnsmasq/tasks/configure.yml
Labels: approved, lgtm, Ready For Review

#1850 [Test-operator] Expose extraRPMs parameter
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm

#1919 Move cifmw-crc-podified-edpm-baremetal back to crc-2-30
  zuul.d/edpm.yaml
Labels: approved, lgtm, Ready For Review

#1890 Enable "backup" for files created by networking_mapper
  roles/networking_mapper/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1925 install switch config hook requirements
  hooks/playbooks/switch_config.yml
Labels: approved, lgtm, va-2, Ready For Review

#1908 Ensure CRC is using our new dnsmasq
  roles/reproducer/tasks/configure_crc.yml
  roles/reproducer/tasks/prepare_networking.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1932 Allow skipping public network creation
  docs/source/usage/01_usage.md
  playbooks/07-admin-setup.yml
Labels: approved, lgtm, ok-to-test, va-2, Ready For Review

#1934 Remove nmcli call on controller-0
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, ipv6

#1937 Ensure we rely only on dnsmasq
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/configure_crc.yml
  roles/reproducer/tasks/crc_layout.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1940 Correct OCP validations
  roles/reproducer/molecule/ocp_validations/converge.yml
  roles/reproducer/molecule/ocp_validations/vars/scenarios.yml
  roles/reproducer/tasks/ocp_layout_assertions.yml
Labels: approved, lgtm, Ready For Review

#1896 Bump crc resources in centos-9-medium-3x-centos-9-crc-extracted-2-36-0-xxl
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#1902 Set snapshot specs in manila's default type
  hooks/playbooks/manila_create_default_resources.yml
Labels: approved, lgtm, Ready For Review

#1784 Add ssh_jumper role
  roles/ssh_jumper/README.md
  roles/ssh_jumper/defaults/main.yml
  roles/ssh_jumper/meta/main.yml
  roles/ssh_jumper/molecule/default/cleanup.yml
  roles/ssh_jumper/molecule/default/converge.yml
  roles/ssh_jumper/molecule/default/molecule.yml
  roles/ssh_jumper/molecule/default/prepare.yml
  roles/ssh_jumper/tasks/cleanup.yml
  roles/ssh_jumper/tasks/main.yml
  roles/ssh_jumper/tasks/manage_ssh_jumper_entry.yml
  roles/ssh_jumper/templates/ssh_host.conf.j2
  roles/ssh_jumper/vars/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review, ipv6

#1921 Modify libvirt_manager to run linear instead of batches
  roles/libvirt_manager/tasks/clean_layout.yml
  roles/libvirt_manager/tasks/create_networks.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/generate_networking_data.yml
  roles/libvirt_manager/tasks/manage_vms.yml
  roles/libvirt_manager/tasks/ocp_layout.yml
  roles/libvirt_manager/tasks/start_vms.yml
  roles/libvirt_manager/tasks/volumes.yml
  roles/libvirt_manager/templates/all-inventory.yml.j2
  roles/libvirt_manager/templates/domain.xml.j2
Labels: approved, lgtm, Ready For Review

#1949 Releasing constraint on go
  ci/playbooks/pre-doc.yml
Labels: approved, lgtm, Ready For Review

#1939 Added var to update IPA agent image
  roles/update_containers/README.md
  roles/update_containers/defaults/main.yml
  roles/update_containers/templates/update_containers.j2
Labels: approved, lgtm, Ready For Review

#1945 Set cifmw_update_containers_edpm_image_url for NFV VA
  scenarios/reproducers/va-nfv-ovs-dpdk-sriov.yml
Labels: approved, lgtm, va-2, Ready For Review

#1928 Enable forward in libvirt zone
  roles/devscripts/tasks/133_host_network.yml
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/tasks/clean_layout.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/ocp_layout.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1938 hook - ironic_network - set nameserver
  hooks/playbooks/ironic_network.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1948 Update default openshift version to 4.15.18
  roles/devscripts/vars/main.yml
Labels: approved, lgtm, Ready For Review

#1882 [OSASINFRA] Add an option to set the project name
  roles/shiftstack/README.md
  roles/shiftstack/defaults/main.yml
  roles/shiftstack/tasks/deploy_shiftstackclient_pod.yml
  roles/shiftstack/tasks/pre_test_shiftstack.yml
  roles/shiftstack/tasks/test_shiftstack.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1952 Put ssh_jumper to use in libvirt_manager role
  roles/libvirt_manager/tasks/clean_layout.yml
  roles/libvirt_manager/tasks/manage_vms.yml
  roles/ssh_jumper/README.md
  roles/ssh_jumper/molecule/default/converge.yml
  roles/ssh_jumper/tasks/cleanup.yml
  roles/ssh_jumper/tasks/main.yml
  roles/ssh_jumper/tasks/manage_ssh_jumper_entry.yml
  roles/ssh_jumper/vars/main.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1950 Add rp_port to content provider template in reproducer
  roles/reproducer/templates/content-provider.yml.j2
Labels: approved, lgtm, Ready For Review

#1935 Add support for running tests locally in git worktree
  .ansible-lint
  Makefile
  containerfiles/Containerfile.tests
Labels: approved, lgtm, Ready For Review

#1953 Add STP settings on osppr bridge
  roles/reproducer/tasks/prepare_networking.yml
Labels: approved, lgtm, Ready For Review

#1959 Skip fixing the marketplace when dry-run enabled
  roles/openshift_setup/tasks/fix_openshift_marketplace.yml
Labels: approved, lgtm, Ready For Review

#1951 Correct OCP related DNS configuration
  roles/reproducer/tasks/ocp_layout.yml
Labels: approved, lgtm, Ready For Review

#1955 Add eurijon as a Reviewer
  OWNERS
Labels: approved, lgtm, Ready For Review

#1960 Fix handling of group-template for crc vms
  roles/libvirt_manager/tasks/generate_networking_data.yml
Labels: approved, lgtm, Ready For Review

#1954 Hook: ironic_inject_tls - IPA images with certs
  hooks/playbooks/ironic_inject_tls.yml
Labels: approved, lgtm, Ready For Review

#1965 Refresh triggers for reproducer and libvirt_manager
  ci/config/molecule.yaml
  zuul.d/molecule.yaml
Labels: approved, lgtm, Ready For Review

#1967 hook: ironic_provide_nodes
  hooks/playbooks/ironic_provide_nodes.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1964 Create proper DNS records for each host/network pair
  roles/dnsmasq/molecule/default/cleanup.yml
  roles/dnsmasq/molecule/default/converge.yml
  roles/dnsmasq/molecule/default/prepare.yml
  roles/dnsmasq/tasks/manage_host_record.yml
  roles/dnsmasq/templates/network.conf.j2
  roles/libvirt_manager/tasks/create_networks.yml
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/tasks/prepare_networking.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1956 Add tolerations to lvms cluster resource
  docs/dictionary/en-custom.txt
  roles/ci_lvms_storage/README.md
  roles/ci_lvms_storage/defaults/main.yml
  roles/ci_lvms_storage/templates/lvms-cluster.yaml.j2
Labels: approved, lgtm, Ready For Review

#1973 Get just the nmstate operator when waiting for install
  roles/ci_nmstate/tasks/nmstate_k8s_install.yml
Labels: approved, lgtm, Ready For Review

#1892 Add Meta content provider job to test opendev and github changes
  ci/playbooks/meta_content_provider/meta_content_provider.yml
  ci/playbooks/meta_content_provider/run.yml
  ci/templates/projects.yaml
  roles/build_openstack_packages/tasks/main.yml
  roles/build_openstack_packages/tasks/parse_and_build_pkgs.yml
  roles/edpm_prepare/tasks/kustomize_and_deploy.yml
  roles/edpm_prepare/tasks/main.yml
  scenarios/centos-9/meta_content_provider.yml
  zuul.d/content_provider.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#1971 hook: nova_manage_discover_hosts.yml
  hooks/playbooks/nova_manage_discover_hosts.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1969 Avoid printing secret with CA in install_openstack_ca
  roles/install_openstack_ca/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1972 [edpm_prepare] Kustomize controlplane name
  roles/edpm_prepare/tasks/kustomize_and_deploy.yml
Labels: approved, lgtm, Ready For Review

#1957 [fetch_compute hook]filter controller hostname from groups
  hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm, Ready For Review

#1979 [docs] Fix files trigger for the docs job
  zuul.d/doc.yaml
Labels: approved, lgtm, Ready For Review

#1930 Ensure we don't expose kuebconfig in custom-params.yml
  playbooks/01-bootstrap.yml
  roles/reproducer/tasks/ci_deploy_data.yml
Labels: approved, lgtm, Ready For Review

#1961 Consolidate, correct and test devscripts checks
  roles/devscripts/molecule/check_cluster_status/converge.yml
  roles/devscripts/molecule/check_cluster_status/molecule.yml
  roles/devscripts/molecule/check_cluster_status/prepare.yml
  roles/devscripts/molecule/check_cluster_status/tasks/test.yml
  roles/devscripts/molecule/check_cluster_status/vars/3_master.yml
  roles/devscripts/molecule/check_cluster_status/vars/3_master_worker.yml
  roles/devscripts/molecule/check_cluster_status/vars/scenarios.yml
  roles/devscripts/tasks/110_check_ocp.yml
  roles/devscripts/tasks/133_host_network.yml
  roles/devscripts/tasks/get_ocp_vips.yml
  roles/devscripts/tasks/main.yml
  roles/reproducer/tasks/ocp_layout.yml
Labels: approved, lgtm, Ready For Review

#1987 Enable some debugging on failure
  roles/libvirt_manager/tasks/generate_networking_data.yml
Labels: approved, lgtm, Ready For Review
