Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-05, with the labels that each got.

#1595 Drop nncp ctlplane routes
  roles/ci_gen_kustomize_values/templates/common/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/network-values/values.yaml.j2
Labels: approved, lgtm

#1601 doc: reorder and clean hook descriptions
  docs/source/usage/01_usage.md
Labels: approved, lgtm

#1614 Expose CRC kubeadmin-password in controller-0
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/crc_layout.yml
Labels: approved, lgtm

#1618 Don't trigger deployment on specific files
  zuul.d/base.yaml
Labels: approved, lgtm

#1623 [reproducer] Fix undefined devscripts_kubeadm
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#1617 Toggle ansible-lint to offline
  .ansible-lint
Labels: approved, lgtm

#1621 Set dlrn proper tag for components
  roles/repo_setup/tasks/artifacts.yml
Labels: approved, lgtm

#1613 [run_hook] Fix default value of state key in CR type
  roles/run_hook/tasks/cr.yml
Labels: approved, lgtm

#1619 Correct regexp in generate_snippets
  .ansible-lint
  roles/ci_gen_kustomize_values/molecule/default/converge.yml
  roles/ci_gen_kustomize_values/molecule/default/files/3-ocp-net-def.yml
  roles/ci_gen_kustomize_values/molecule/default/prepare.yml
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
Labels: approved, lgtm

#1622 [test-operator] Add option to set networkAttachments
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm

#1624 Drop cifmw_repo_setup_component var
  roles/repo_setup/defaults/main.yml
  roles/repo_setup/tasks/artifacts.yml
Labels: approved, lgtm

#1615 Correct import vs include
  playbooks/06-deploy-architecture.yml
  playbooks/06-deploy-edpm.yml
Labels: approved, lgtm

#1628 Allow to run a layout without any CRC
  roles/reproducer/tasks/ci_data.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1630 Rework imported vars in the reproducer
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#1625 [test-operator] Fix tempest workflows
  roles/test_operator/tasks/main.yml
Labels: approved, lgtm

#1607 [run_hook] Allow passing namespace if needed in CR hooks
  roles/run_hook/tasks/cr.yml
Labels: approved, lgtm

#1584 pod/extend pod jobs
  .pre-commit-config.yaml
  Makefile
  ci/playbooks/pod-jobs.yml
  ci/templates/projects.yaml
  zuul.d/pods.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1598 Remove cacheable: true from ci_data.yml
  roles/reproducer/tasks/ci_data.yml
Labels: approved, lgtm

#1635 Fix bad link rendering
  containerfiles/README.md
Labels: approved, lgtm

#1632 [os_net_setup] Update public default allocation pool
  roles/os_net_setup/defaults/main.yml
Labels: approved, lgtm, ok-to-test

#1597 Cleanup commented out defaults
  roles/build_containers/defaults/main.yml
  roles/build_openstack_packages/defaults/main.yml
Labels: approved, lgtm

#1641 Correct networking layout used in molecule
  roles/kustomize_deploy/molecule/flexible_loop/files/networking-environment-definition.yml
Labels: approved, lgtm

#1639 Remove cifmw_discover_latest_image_qcow_prefix from molecule config
  .config/molecule/config_local.yml
Labels: approved, lgtm

#1629 Ensure we run custom, injected hooks in all cases
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm

#1640 Fix allow/skip list generation in test-operator
  roles/test_operator/tasks/tempest-tests.yml
Labels: approved, lgtm

#1638 Avoid ansibleee-operator hardcoded version
  roles/edpm_prepare/tasks/main.yml
Labels: approved, lgtm

#1645 Do not trigger deployment on molecule related change
  zuul.d/base.yaml
Labels: approved, lgtm

#1651 Filter out and update cifmw_set_openstack_containers_registry
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/templates/content-provider.yml.j2
Labels: approved, lgtm

#1642 Extend ip ranges and regexes to allow deploying additional ocp workers
  roles/libvirt_manager/tasks/start_manage_vms.yml
  scenarios/reproducers/networking-definition.yml
Labels: approved, lgtm

#1652 Drop task to install dataplane services
  roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#1232 minor fixes to tofu role
  roles/tofu/tasks/plan.yml
  roles/tofu/tasks/prepare.yml
Labels: approved, lgtm, needs-ok-to-test

#1626 Dump dlrn md5 hash from current-podified while using component repo
  roles/repo_setup/tasks/artifacts.yml
Labels: approved, lgtm

#1552 [shiftstack] Add shifstack-qa gerrithub repo change support
  docs/dictionary/en-custom.txt
  roles/shiftstack/README.md
  roles/shiftstack/defaults/main.yml
  roles/shiftstack/tasks/test_shiftstack.yml
Labels: approved, lgtm, ok-to-test

#1573 Prepare for job dependency
  ci/playbooks/noop.yml
  ci/templates/noop-molecule.yaml.j2
  ci/templates/projects.yaml
  scripts/create_role_molecule.py
  zuul.d/molecule-base.yaml
  zuul.d/molecule.yaml
  zuul.d/project-templates.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1656 [env_op_images] Avoid using install_yamls defaults
  roles/env_op_images/tasks/main.yml
Labels: approved, lgtm

#1637 Fix(?) CRC DNS
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/configure_crc.yml
Labels: approved, lgtm

#1604 Split dataplane deployment in edpm_deploy role
  roles/edpm_deploy/README.md
  roles/edpm_deploy/defaults/main.yml
  roles/edpm_deploy/tasks/main.yml
Labels: approved, lgtm

#1660 Replace noop molecule job parent
  ci/playbooks/noop.yml
  zuul.d/molecule-base.yaml
Labels: approved, lgtm

#1662 Fix dlrn_reporting role for component promotion
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm

#1581 Use update_containers role to update EDPM BM OS image
  roles/edpm_deploy_baremetal/tasks/main.yml
  roles/edpm_prepare/tasks/main.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_periodic.yml
Labels: approved, lgtm

#1661 Add Github workflow to set [re]opened PRs into draft state
  .github/workflows/auto-draft.yml
  docs/source/development/01_guidelines.md
  docs/source/index.rst
Labels: approved, lgtm

#1655 [kustomize_deploy] Combine multiple user kustomizations as one
  docs/source/usage/01_usage.md
  roles/kustomize_deploy/molecule/flexible_loop/converge.yml
  roles/kustomize_deploy/molecule/flexible_loop/prepare.yml
  roles/kustomize_deploy/molecule/flexible_loop/resources/vars.yml
  roles/kustomize_deploy/tasks/_compute_user_kustomize.yml
  roles/kustomize_deploy/tasks/check_requirements.yml
  roles/kustomize_deploy/tasks/execute_step.yml
  roles/kustomize_deploy/tasks/install_operators.yml
Labels: approved, lgtm

#1233 Deploy BGP Spine/Leaf infrastructure on a HV
  roles/ci_gen_kustomize_values/templates/bgp/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp/network-values/values.yaml.j2
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/molecule/spine_leaf/cleanup.yml
  roles/libvirt_manager/molecule/spine_leaf/converge.yml
  roles/libvirt_manager/molecule/spine_leaf/molecule.yml
  roles/libvirt_manager/molecule/spine_leaf/prepare.yml
  roles/libvirt_manager/tasks/attach_interface.yml
  roles/libvirt_manager/tasks/create_vms.yml
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
Labels: approved, lgtm

#1665 Fixed dlrnapi hash params
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm

#1659 [ci_gen_kustomize_values] renamed olm template folder
  roles/ci_gen_kustomize_values/templates/common/olm-values/values.yaml.j2
Labels: approved, lgtm

#1407 Move again NFS server after EDPM deploy
  playbooks/06-deploy-edpm.yml
Labels: approved, lgtm

#1616 Use ad-hoc reboot play
  roles/validations/tasks/edpm/hugepages_and_reboot.yml
Labels: approved, lgtm

#1664 Pass reproducer Job zuul-params.yml in tcib content provider
  roles/reproducer/templates/content-provider.yml.j2
Labels: approved, lgtm

#1670 Check for cifmw_repo_setup_component_name definition
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm

#1669 Add openshift_setup role to kuttl playbook
  ci/playbooks/kuttl/e2e-kuttl.yml
  scenarios/centos-9/kuttl.yml
Labels: approved, lgtm

#1671 Update auto-draft workflow to use pull_request_target event
  .github/workflows/auto-draft.yml
Labels: approved, lgtm

#1487 Add tempest job based on EDPM multinode
  scenarios/centos-9/ceph_backends.yml
  zuul.d/tempest_multinode.yaml
Labels: approved, lgtm

#1165 Add repo sync repos and set_openstack_containers roles to update playbook
  playbooks/update.yml
  scenarios/centos-9/multinode-ci.yml
Labels: approved, lgtm, minor update

#1668 [test-operator] Add Vif tests to skiplist
  roles/test_operator/files/list_skipped.yml
Labels: approved, lgtm

#1672 Remove podified-multinode-edpm-e2e-nobuild-tagged-crc job def
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#1654 [libvirt_manager] Update domain.xml.j2 to support baremetal instance
  roles/libvirt_manager/README.md
  roles/libvirt_manager/templates/domain.xml.j2
Labels: approved, lgtm, Ready For Review

#1650 New role: dnsmasq
  docs/dictionary/en-custom.txt
  roles/dnsmasq/README.md
  roles/dnsmasq/defaults/main.yml
  roles/dnsmasq/files/.gitkeep
  roles/dnsmasq/files/cifmw-dnsmasq.service
  roles/dnsmasq/handlers/main.yml
  roles/dnsmasq/meta/main.yml
  roles/dnsmasq/molecule/default/converge.yml
  roles/dnsmasq/molecule/default/molecule.yml
  roles/dnsmasq/molecule/default/prepare.yml
  roles/dnsmasq/tasks/cleanup.yml
  roles/dnsmasq/tasks/configure.yml
  roles/dnsmasq/tasks/main.yml
  roles/dnsmasq/tasks/manage_host.yml
  roles/dnsmasq/tasks/manage_network.yml
  roles/dnsmasq/templates/cifmw-dnsmasq.conf.j2
  roles/dnsmasq/templates/network.conf.j2
  roles/dnsmasq/vars/main.yml
  zuul.d/base.yaml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1680 Add namespace to osdpns lookup
  roles/validations/tasks/edpm/hugepages_and_reboot.yml
Labels: approved, lgtm, Ready For Review

#1526 [OSASINFRA] Attach a PVC to shiftstack client
  docs/dictionary/en-custom.txt
  roles/shiftstack/README.md
  roles/shiftstack/defaults/main.yml
  roles/shiftstack/molecule/default/converge.yml
  roles/shiftstack/tasks/deploy_shiftstackclient_pod.yml
  roles/shiftstack/tasks/test_shiftstack.yml
  roles/shiftstack/templates/shiftstackclient_pod.yml.j2
  roles/shiftstack/templates/shiftstackclient_pvc.yml.j2
Labels: approved, lgtm, ok-to-test

#1677 Add review ready label automation
  .github/workflows/review-ready-label.yml
  docs/source/development/01_guidelines.md
Labels: approved, lgtm, Ready For Review

#1675 Loop through .xml files for jump
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1673 Update NFS playbook for better firewall handling
  playbooks/nfs.yml
Labels: approved, lgtm, Ready For Review

#1653 Make start VM and Manage (inventory + jumper) optional
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/manage_vms.yml
  roles/libvirt_manager/tasks/start_vms.yml
Labels: approved, lgtm, Ready For Review

#1646 Allow to deploy architecture against CRC
  playbooks/06-deploy-architecture.yml
  roles/kustomize_deploy/tasks/reduce_ocp_cluster.yml
Labels: approved, lgtm, Ready For Review

#1685 Use ansible.builtin.stat to check src file existence
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
Labels: approved, lgtm, Ready For Review

#1633 Add a (post-deploy) hook to set a multiattach volume type
  hooks/playbooks/cinder_multiattach_volume_type.yml
Labels: approved, lgtm, Ready For Review

#1688 [dlrn_promote]Fixed dlrnapi hash params
  roles/dlrn_promote/tasks/check_for_previous_promotions.yml
Labels: approved, lgtm, Ready For Review

#1689 Switch away from `lookup()`
  ci/config/molecule.yaml
  roles/kustomize_deploy/molecule/flexible_loop/converge.yml
  roles/kustomize_deploy/molecule/flexible_loop/prepare.yml
  roles/kustomize_deploy/tasks/execute_step.yml
  zuul.d/molecule.yaml
Labels: approved, lgtm, Ready For Review

#1693 Add become in bootstrap-hypervisor.yml
  docs/source/files/bootstrap-hypervisor.yml
Labels: approved, lgtm, Ready For Review

#1699 Ensure we have kubectl and kustomize on controller-0
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1682 Reload crc NetworkManager in reproducer
  roles/reproducer/tasks/configure_crc.yml
Labels: approved, lgtm, Ready For Review

#1647 [test-operator] Make ntp_extra_image more generic
  docs/dictionary/en-custom.txt
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1702 Refine a bit dnsmasq role
  roles/dnsmasq/tasks/configure.yml
  roles/dnsmasq/tasks/manage_host.yml
  roles/dnsmasq/tasks/manage_network.yml
  roles/dnsmasq/templates/network.conf.j2
Labels: approved, lgtm, Ready For Review

#1704 Don't hardcode device image file in unit template
  roles/cifmw_block_device/templates/ceph-osd-losetup.service.j2
Labels: approved, lgtm, Ready For Review

#1708 Ensure we clean dnsmasq lease file upon cleanup
  roles/dnsmasq/tasks/cleanup.yml
Labels: approved, lgtm

#1709 Ensure the reproducer cleans /etc/ci directory
  reproducer-clean.yml
Labels: approved, lgtm

#1701 Remove duplicate entry in usage doc
  docs/source/usage/01_usage.md
Labels: approved, lgtm, ok-to-test

#1710 Update auto-draft workflow to skip on nit: PRs
  .github/workflows/auto-draft.yml
  docs/source/development/01_guidelines.md
Labels: approved, lgtm, Ready For Review

#1712 Promote cescgina to approver
  OWNERS
Labels: approved, lgtm, Ready For Review

#1297 Add role to deploy mirror-registry
  roles/mirror_registry/README.md
  roles/mirror_registry/defaults/main.yml
  roles/mirror_registry/meta/main.yml
  roles/mirror_registry/molecule/default/converge.yml
  roles/mirror_registry/molecule/default/molecule.yml
  roles/mirror_registry/molecule/default/prepare.yml
  roles/mirror_registry/tasks/cleanup.yml
  roles/mirror_registry/tasks/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#1463 Hotfix qe job
  roles/validations/defaults/main.yml
  roles/validations/tasks/edpm/hotfix.yml
Labels: approved, lgtm, validation, Ready For Review

#1711 Allow to enable DNS listener in dnsmasq
  roles/dnsmasq/README.md
  roles/dnsmasq/molecule/default/converge.yml
  roles/dnsmasq/molecule/default/prepare.yml
  roles/dnsmasq/templates/network.conf.j2
Labels: approved, lgtm, Ready For Review

#1703 Switch from `kustomize` to `oc kustomize`
  roles/kustomize_deploy/molecule/flexible_loop/prepare.yml
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm, Ready For Review

#1676 Allow passing base64 encoded patches to ci_gen_kustomize
  roles/ci_gen_kustomize_values/README.md
  roles/ci_gen_kustomize_values/defaults/main.yml
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
  roles/kustomize_deploy/filter_plugins/ci_kustomize_deploy_combine_base64_patch_dict.py
  roles/kustomize_deploy/tasks/_compute_user_kustomize.yml
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm, Ready For Review

#1705 Fix loop for jump
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1716 [test-operator] Expose nodeSelector and tolerations parameters
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#1719 [ci_gen_kustomize] Remove the dedicated ctlplaneInterface var
  roles/ci_gen_kustomize_values/README.md
  roles/ci_gen_kustomize_values/defaults/main.yml
  roles/ci_gen_kustomize_values/tasks/edpm_core_asserts.yml
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/sriov/edpm-nodeset-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#1667 Architecture repository test playbook
  Makefile
  ci/playbooks/files/networking-env-definition.yml
  ci/playbooks/validate-architecture.yml
  ci/templates/projects.yaml
  roles/ci_setup/tasks/packages.yml
  zuul.d/architecture-jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#1720 [run_hook] Fixed `crd_path` content and added CR hook example
  roles/run_hook/README.md
  roles/run_hook/tasks/cr.yml
Labels: approved, lgtm, Ready For Review

#1696 [kustomize_deploy] Generate kustomizatize patches from localhost tree
  docs/source/usage/01_usage.md
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
  roles/kustomize_deploy/tasks/_compute_user_kustomize.yml
  roles/kustomize_deploy/tasks/generate_base64_patches_from_tree.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1723 Add tolerations and nodeSelector to test-operator-controller-manager
  roles/test_operator/README.md
  roles/test_operator/tasks/main.yml
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: approved, lgtm, Ready For Review

#1724 Fix multiattach volume type create playbook
  hooks/playbooks/cinder_multiattach_volume_type.yml
Labels: approved, lgtm, Ready For Review

#1728 Trick ansible in loading mock data
  ci/playbooks/validate-architecture.yml
Labels: approved, lgtm, Ready For Review

#1687 Add playbooks to set up the nat64 net and VM
  docs/dictionary/en-custom.txt
  roles/config_drive/templates/network-config.j2
  roles/nat64_appliance/README.md
  roles/nat64_appliance/defaults/main.yml
  roles/nat64_appliance/files/elements/nat64-router/static/usr/local/sbin/configure-nat64
  roles/nat64_appliance/files/nat64-appliance.yaml
  roles/nat64_appliance/molecule/default/cleanup.yml
  roles/nat64_appliance/molecule/default/converge.yml
  roles/nat64_appliance/molecule/default/prepare.yml
  roles/nat64_appliance/tasks/cleanup.yml
  roles/nat64_appliance/tasks/deploy.yml
  roles/nat64_appliance/tasks/main.yml
  roles/nat64_appliance/templates/config-data.j2
  roles/nat64_appliance/templates/domain.xml.j2
  roles/nat64_appliance/templates/ipv4_network.xml.j2
  roles/nat64_appliance/templates/ipv6_network.xml.j2
Labels: approved, lgtm, Ready For Review

#1733 Use dlrnapi repo-status for finding component reported jobs
  roles/dlrn_promote/tasks/check_reported_jobs.yml
Labels: approved, lgtm, Ready For Review

#1714 Add new tag for devscripts layout bootstrap
  docs/source/usage/01_usage.md
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1736 Update autodraft workflow to skip bots
  .github/workflows/auto-draft.yml
Labels: approved, lgtm, Ready For Review

#1738 Update the repo_setup role readme
  roles/repo_setup/README.md
Labels: approved, lgtm, Ready For Review

#1740 [uni01alpha] Add support for testing DT
  ci/playbooks/files/networking-env-definition.yml
Labels: approved, lgtm, Ready For Review

#1742 [uni04delta] Add ceph type nodes to assist gate checks
  ci/playbooks/files/networking-env-definition.yml
Labels: approved, lgtm, Ready For Review

#1727 Refine a bit validate-architecture related make targets
  Makefile
  roles/ci_setup/tasks/directories.yml
Labels: approved, lgtm, Ready For Review

#1678 [os_net_setup] Update public allocation pool and network configuration
  roles/os_net_setup/defaults/main.yml
  scenarios/reproducers/networking-definition.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1560 Add support for Sushy Emulator backed virtual baremetal
  docs/source/usage/01_usage.md
  roles/libvirt_manager/tasks/create_networks.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/network_bridge_info_gen.yml
  roles/reproducer/defaults/main.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/generate_bm_info.yml
  roles/sushy_emulator/README.md
  roles/sushy_emulator/defaults/main.yml
  roles/sushy_emulator/molecule/default/converge.yml
  roles/sushy_emulator/molecule/default/prepare.yml
  roles/sushy_emulator/tasks/collect_details.yml
  roles/sushy_emulator/tasks/create_container.yml
  roles/sushy_emulator/tasks/main.yml
  roles/sushy_emulator/tasks/verify.yml
  roles/sushy_emulator/templates/config_conf.j2
  roles/sushy_emulator/templates/secret_yaml.j2
Labels: approved, lgtm, Ready For Review

#1753 Fix sushy_emulator integration in reproducer
  ci/config/molecule.yaml
  roles/podman/README.md
  roles/podman/defaults/main.yml
  roles/podman/tasks/main.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/sushy_emulator/README.md
  roles/sushy_emulator/defaults/main.yml
  zuul.d/molecule.yaml
Labels: approved, lgtm, Ready For Review

#1750 Ensure we clean all the generated files as well
  roles/libvirt_manager/tasks/clean_layout.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1760 Use '::' for sushy emulator default listen address
  roles/sushy_emulator/defaults/main.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1749 Avoid failures on cleaning
  roles/dnsmasq/handlers/main.yml
  roles/libvirt_manager/tasks/clean_layout.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1747 Allow to specify pool directory
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/tasks/storage_pool.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1580 Use update_containers role to update ansibleee image
  ci/playbooks/build_runner_image.yml
  roles/edpm_prepare/tasks/main.yml
  roles/update_containers/tasks/main.yml
  roles/update_containers/templates/update_containers.j2
Labels: approved, lgtm, Ready For Review

#1746 Allow custom VM template
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/tasks/create_vms.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1762 nit: Ensure we focus on CI job rerun
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1754 Remove multi-hypervisor testing in molecule
  docs/source/quickstart/02_prepare_env.md
  docs/source/quickstart/03_deploy_infra.md
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1768 nit: Ensure sushy is installed after base packages
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1722 Allow to patch devscripts config overrides
  roles/devscripts/README.md
  roles/devscripts/molecule/default/converge.yml
  roles/devscripts/molecule/default/molecule.yml
  roles/devscripts/tasks/110_check_ocp.yml
  roles/devscripts/tasks/133_host_network.yml
  roles/devscripts/tasks/build_config.yml
  roles/devscripts/tasks/main.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1755 Silent the assertion in sushy_emulator
  roles/sushy_emulator/tasks/verify.yml
Labels: approved, lgtm, Ready For Review

#1758 Ensure we're targeting the right VMs
  roles/libvirt_manager/tasks/manage_vms.yml
Labels: approved, lgtm, Ready For Review

#1725 Set nfs network vars from ipset
  playbooks/nfs.yml
Labels: approved, lgtm, Ready For Review

#1717 Prepare networking as early as possible
  roles/devscripts/tasks/133_host_network.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/tasks/prepare_networking.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1765 sushy-emulator - use listening addr in _sushy_url
  roles/sushy_emulator/tasks/create_container.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1775 Add abays and fultonj to the owners file
  OWNERS
Labels: approved, lgtm, Ready For Review

#1769 Remove default_style="\"" from to_nice_yaml
  roles/config_drive/templates/meta-data.j2
  roles/config_drive/templates/user-data.j2
Labels: approved, lgtm, Ready For Review, ipv6

#1757 Set edpmRoleServiceName for nova-custom-ceph
  roles/hci_prepare/templates/dpservice-nova-custom-ceph.yml.j2
Labels: approved, lgtm, Ready For Review

#1774 nit: Correct the used SSH key in ansible inventory
  roles/libvirt_manager/templates/inventory.yml.j2
Labels: approved, lgtm, Ready For Review

#1776 Grab dnsmasq output in case of failure
  roles/dnsmasq/tasks/configure.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1752 Add reproducer scenario for PIDONE VA
  ci/playbooks/files/networking-env-definition.yml
  scenarios/reproducers/va-pidone.yml
Labels: approved, lgtm, Ready For Review

#1707 Introduce ci_lvms_storage role
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  playbooks/06-deploy-architecture.yml
  playbooks/06-deploy-edpm.yml
  roles/ci_gen_kustomize_values/README.md
  roles/ci_gen_kustomize_values/defaults/main.yml
  roles/ci_gen_kustomize_values/templates/bgp/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/common/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni01alpha/network-values/values.yaml.j2
  roles/ci_lvms_storage/README.md
  roles/ci_lvms_storage/defaults/main.yml
  roles/ci_lvms_storage/meta/main.yml
  roles/ci_lvms_storage/tasks/cleanup.yml
  roles/ci_lvms_storage/tasks/main.yml
  roles/ci_lvms_storage/tasks/status.yml
  roles/ci_lvms_storage/tasks/test.yml
  roles/ci_lvms_storage/templates/lvms-cluster.yaml.j2
  roles/ci_lvms_storage/templates/lvms-namespace.yaml.j2
  roles/ci_lvms_storage/templates/operator-group.yaml.j2
  roles/ci_lvms_storage/templates/subscription.yaml.j2
  roles/ci_lvms_storage/templates/test/test-pod.yaml.j2
  roles/ci_lvms_storage/templates/test/test-pvc.yaml.j2
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review, ipv6

#1734 Add bgp_dt01 kustomize values.yaml templates
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-common-nodeset-values/common-bgp-edpm-values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-networker-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#1780 Re-add the host IPs in controller-0 .ssh/config, revert hostname
  roles/libvirt_manager/tasks/manage_vms.yml
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, Ready For Review

#1786 Fix '_sushy_emulator_available' var when cifmw_use_sushy_emulator=false
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, Ready For Review

#1565 [devscripts] Modifying the OpenShift version to 4.15
  roles/devscripts/vars/main.yml
Labels: approved, lgtm, Ready For Review

#1766 [devscripts] Configure cinder-volumes vg only for specific disks
  roles/devscripts/README.md
  roles/devscripts/defaults/main.yml
  roles/devscripts/files/lv-cinder-volumes.sh
  roles/devscripts/tasks/137_custom_install.yml
  roles/devscripts/templates/lv.j2
Labels: approved, lgtm, Ready For Review

#1785 dnsmasq manage forwarder/address/host-record
  docs/dictionary/en-custom.txt
  roles/dnsmasq/README.md
  roles/dnsmasq/molecule/default/cleanup.yml
  roles/dnsmasq/molecule/default/converge.yml
  roles/dnsmasq/tasks/manage_address.yml
  roles/dnsmasq/tasks/manage_forwarder.yml
  roles/dnsmasq/tasks/manage_host_record.yml
Labels: approved, lgtm, Ready For Review

#1788 Make sure podman is installed before cleaning vbmc container
  roles/virtualbmc/tasks/cleanup.yml
Labels: approved, lgtm, Ready For Review

#1793 Revert the VA CI base Net Env Def to HCI like
  ci/playbooks/files/networking-env-definition.yml
Labels: approved, lgtm, Ready For Review

#1713 Ensure to run cephfs task for nfs ganesha
  playbooks/ceph.yml
  roles/cifmw_cephadm/tasks/cephfs.yml
  roles/cifmw_cephadm/tasks/cephnfs.yml
Labels: approved, lgtm, Ready For Review

#1694 Ceph settings: more modular manila configuration
  hooks/playbooks/templates/config_ceph_backends.yaml.j2
Labels: approved, lgtm, Ready For Review

#1729 [shiftstack] Templates for rendering the right values to be used in the DT
  roles/ci_gen_kustomize_values/templates/shiftstack/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/shiftstack/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#1648 Add base tempest job
  zuul.d/tempest_multinode.yaml
  zuul.d/tempest_periodic.yaml
Labels: approved, lgtm, Ready For Review
