Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-04, with the labels that each got.

#1370 [openshift_adm] Generalize the retry count.
  roles/openshift_adm/README.md
  roles/openshift_adm/defaults/main.yml
  roles/openshift_adm/tasks/wait_for_cluster.yml
  roles/reproducer/tasks/devscripts_post.yml
Labels: approved, lgtm

#1366 Fix lvm-iscsi volume group name
  roles/devscripts/files/lv-cinder-volumes.sh
Labels: approved, lgtm

#1259 Adapt VA-HCI for shiftstack
  reproducer.yml
  scenarios/reproducers/shift-on-stack-overrides.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm, ok-to-test

#1361 Allow to manually override the root_partition_id
  docs/source/usage/01_usage.md
  scenarios/reproducers/3-nodes.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1355 [FIPS] Allow to deploy VA-HCI with FIPS enabled
  docs/source/usage/01_usage.md
  roles/ci_gen_kustomize_values/templates/hci/edpm-values/values.yaml.j2
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1294 Stop ceph playbooks as early as possible
  playbooks/06-deploy-edpm.yml
  playbooks/ceph.yml
Labels: approved, lgtm

#1352 Updates dataplane services in hci_prepare role
  roles/hci_prepare/README.md
  roles/hci_prepare/defaults/main.yml
  roles/hci_prepare/tasks/phase1.yml
  roles/hci_prepare/tasks/phase2.yml
Labels: approved, lgtm

#1360 Use zuul_inventory to find out edpm vms ip
  roles/artifacts/tasks/edpm.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm

#1350 [build_openstack_packages]Replace osp_release with cifmw_bop_osp_release
  roles/build_openstack_packages/README.md
  roles/build_openstack_packages/defaults/main.yml
  roles/build_openstack_packages/tasks/install_dlrn.yml
  roles/build_openstack_packages/templates/projects.ini.j2
Labels: approved, lgtm

#1374 Set tenant MTU to 1500 for shift on stack
  scenarios/reproducers/shift-on-stack-overrides.yml
Labels: approved, lgtm, ok-to-test

#1375 Update docs related to push_code
  docs/source/reproducers/03-zuul.md
  roles/reproducer/README.md
Labels: approved, lgtm

#1376 Add missing default vars for compute disk,mem and cpu for va-hci
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1227 Add additional extra var to update plyabook run
  ci/playbooks/edpm/update.yml
Labels: approved, lgtm, minor update

#1363 Ensure we're using the right VM layout
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/libvirt_layout.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1201 Add tripleo controllers into adoption multinode source nodeset
  ci/playbooks/multinode-customizations.yml
  zuul.d/adoption.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#1229 Make sure component repos in update jobs are setup during update phase only
  roles/repo_setup/tasks/main.yml
Labels: approved, lgtm, minor update

#1330 Add adoption variant to run minimal without ceph
  zuul.d/adoption.yaml
Labels: approved, lgtm

#1379 Prepare architecture automation file change
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm

#1382 [Test-operator] Fix mounting of ssh key
  roles/test_operator/tasks/tempest-tests.yml
Labels: approved, lgtm

#1381 Fix layout when clause that assumed computes exist
  roles/reproducer/tasks/libvirt_layout.yml
Labels: approved, lgtm

#1296 Add application_credential module
  .readthedocs.yaml
  plugins/modules/application_credential.py
  scripts/prepare_doc_build_env.sh
Labels: approved, lgtm

#1383 Allow longer names for hooks related content
  roles/run_hook/tasks/playbook.yml
Labels: approved, lgtm

#1240 Adds a new single node HCI job
  hooks/playbooks/control_plane_ceph_backends.yml
  hooks/playbooks/control_plane_hci_pre_deploy.yml
  scenarios/centos-9/ceph_backends.yml
  scenarios/centos-9/hci_ceph_backends.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#1386 Correct issues due to cached facts and k8s core module
  roles/kustomize_deploy/tasks/execute_step.yml
  roles/reproducer/tasks/ci_job.yml
  roles/reproducer/tasks/configure_architecture.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1385 Add openstack documentation fragments
  plugins/doc_fragments/openstack.py
Labels: approved, lgtm

#1392 Allow to inject custom wait_conditions during stages
  docs/source/usage/01_usage.md
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm

#1332 Extend and generate files based on IPMI data
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#1345 Add deploy_bmh role
  docs/dictionary/en-custom.txt
  roles/deploy_bmh/README.md
  roles/deploy_bmh/defaults/main.yml
  roles/deploy_bmh/meta/main.yml
  roles/deploy_bmh/molecule/default/cleanup.yml
  roles/deploy_bmh/molecule/default/converge.yml
  roles/deploy_bmh/molecule/default/molecule.yml
  roles/deploy_bmh/molecule/default/prepare.yml
  roles/deploy_bmh/tasks/cleanup.yml
  roles/deploy_bmh/tasks/main.yml
  roles/deploy_bmh/template/bmh.yml.j2
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1396 Store nfs related facts to artifacts/parameters
  playbooks/06-deploy-edpm.yml
  playbooks/nfs.yml
Labels: approved, lgtm

#1378 Remove unused cifmw_operator_build_meta_image_base variable
  roles/operator_build/README.md
  roles/operator_build/defaults/main.yml
Labels: approved, lgtm

#1406 Ensure we create CRC and OCP first
  roles/libvirt_manager/tasks/deploy_layout.yml
  scenarios/reproducers/3-nodes.yml
  scenarios/reproducers/external-ceph.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1401 Add a new parameter to inject extravars in nested plays
  roles/reproducer/README.md
  roles/reproducer/defaults/main.yml
  roles/reproducer/tasks/configure_architecture.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/templates/script.sh.j2
Labels: approved, lgtm

#1402 [Test operator] Fix skiplist generation
  roles/test_operator/tasks/tempest-tests.yml
Labels: approved, lgtm

#1409 Include install-certs dataplane service
  roles/hci_prepare/tasks/phase2.yml
  roles/hci_prepare/templates/dpservice-nova-custom-ceph.yml.j2
Labels: approved, lgtm

#1398 Ensure install_yamls "download_tools.yml" play is run early
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1411 [deploy_bmh] Allow CRs patching
  roles/deploy_bmh/README.md
  roles/deploy_bmh/defaults/main.yml
  roles/deploy_bmh/molecule/default/cleanup.yml
  roles/deploy_bmh/molecule/default/converge.yml
  roles/deploy_bmh/tasks/cleanup.yml
  roles/deploy_bmh/tasks/create_templated_resource.yml
  roles/deploy_bmh/tasks/main.yml
  roles/deploy_bmh/template/bmh-secret.yml.j2
  roles/deploy_bmh/template/bmh.yml.j2
Labels: approved, lgtm

#1416 Always Enable file logging for a Ceph cluster
  roles/cifmw_cephadm/tasks/cephadm_config_set.yml
Labels: approved, lgtm

#1410 Explicitly deploy MDS from a template spec
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/cephfs.yml
  roles/cifmw_cephadm/templates/ceph_mds.yml.j2
Labels: approved, lgtm

#1405 Ensure we have an undying virtualbmc
  roles/virtualbmc/tasks/cleanup.yml
  roles/virtualbmc/tasks/main.yml
Labels: approved, lgtm

#1391 [EDPM]Switch to test_operator for running tempest tests
  scenarios/centos-9/edpm_periodic.yml
  scenarios/centos-9/multinode-ci.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1417 [openshift_adm] Replace removed `openssl_certificate_info`
  roles/openshift_adm/tasks/api_cert.yml
Labels: approved, lgtm

#1399 Call deploy_bmh in deploy-edpm
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  playbooks/02-infra.yml
Labels: approved, lgtm

#1419 [libvirt_manager] Remove filter on list vms task
  roles/libvirt_manager/tasks/deploy_layout.yml
Labels: approved, lgtm

#1424 Do not duplicate nodes in the placement section when deploy mds
  roles/cifmw_cephadm/templates/ceph_mds.yml.j2
Labels: approved, lgtm

#1420 [test-operator] Fix k8s_info metadata parsing
  roles/test_operator/tasks/main.yml
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: approved, lgtm

#1427 Add skip tests missing from test operator role
  roles/test_operator/files/list_skipped.yml
Labels: approved, lgtm

#1400 Generate and use scripts for CI runner
  roles/reproducer/tasks/ci_job.yml
Labels: approved, lgtm

#1434 Use ansible_user_id instead of ansible_user on podman fix
  roles/virtualbmc/tasks/main.yml
Labels: approved, lgtm

#1429 [deploy_bmh] Add rootDeviceHints field support
  roles/deploy_bmh/README.md
  roles/deploy_bmh/defaults/main.yml
  roles/deploy_bmh/template/bmh.yml.j2
Labels: approved, lgtm

#1333 [Test-operator] Introduce Tempest workflow
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm

#1438 Pin CentOS image used in molecule
  .config/molecule/config_local.yml
  ci/templates/molecule.yaml.j2
  zuul.d/molecule.yaml
Labels: approved, lgtm

#1437 Deploy bmh/support bm nmstate
  roles/deploy_bmh/README.md
  roles/deploy_bmh/tasks/main.yml
  roles/deploy_bmh/template/bmh-nmstate.yml.j2
  roles/deploy_bmh/template/bmh.yml.j2
Labels: approved, lgtm

#1431 Symlink skiplists between tempest and test-operator
  roles/tempest/files/list_allowed.yml
  roles/tempest/files/list_skipped.yml
Labels: approved, lgtm

#1390 [ci_gen_kustomize_values] Add mac address mapping for `nic1`
  roles/ci_gen_kustomize_values/templates/hci/edpm-values/values.yaml.j2
Labels: approved, lgtm

#1389 [Test-operator] Introduce option for nt-plugin extra image
  docs/dictionary/en-custom.txt
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm

#1432 Run e2e log collection in tcib jobs
  zuul.d/tcib.yaml
Labels: approved, lgtm

#1443 [deploy_bmh] Fixing indent, default namespace and secret name
  roles/deploy_bmh/README.md
  roles/deploy_bmh/defaults/main.yml
  roles/deploy_bmh/template/bmh-nmstate.yml.j2
  roles/deploy_bmh/template/bmh.yml.j2
Labels: approved, lgtm

#1435 Determine jump result dir based on the tempest role
  roles/polarion/README.md
  roles/polarion/defaults/main.yml
Labels: approved, lgtm

#1439 Allow defined VM with amount=0
  roles/libvirt_manager/README.md
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
Labels: approved, lgtm

#1430 [libvirtmanager] Allow layout configuration patching
  roles/libvirt_manager/README.md
  roles/libvirt_manager/tasks/deploy_layout.yml
Labels: approved, lgtm

#1433 Use role defaults in tcib job
  ci/playbooks/tcib/tcib.yml
  roles/build_openstack_packages/README.md
  roles/build_openstack_packages/defaults/main.yml
Labels: approved, lgtm

#1326 Establish framework for QE Validation jobs
  playbooks/06-deploy-architecture.yml
  playbooks/06-deploy-edpm.yml
  playbooks/validations.yml
  roles/validations/README.md
  roles/validations/defaults/main.yml
  roles/validations/meta/main.yml
  roles/validations/molecule/default/converge.yml
  roles/validations/molecule/default/molecule.yml
  roles/validations/molecule/default/prepare.yml
  roles/validations/tasks/compute/main.yml
  roles/validations/tasks/edpm/main.yml
  roles/validations/tasks/main.yml
  roles/validations/tasks/networking/main.yml
  roles/validations/tasks/nfv/main.yml
  roles/validations/tasks/storage/main.yml
  roles/validations/tasks/telemetry/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1444 Add a simple document about the format of the BM file
  docs/source/baremetal/01_baremetal_hosts_data.md
  docs/source/index.rst
  docs/source/usage/01_usage.md
  roles/deploy_bmh/molecule/default/prepare.yml
  roles/deploy_bmh/tasks/main.yml
  roles/deploy_bmh/template/bmh.yml.j2
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#1445 Ensure we keep track of the kustomize builds
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm

#1441 Add validation and assert before get all ip addresses
  playbooks/ceph.yml
Labels: approved, lgtm

#1447 [deploy_bmh] Pass host credentials through a file
  docs/source/baremetal/01_baremetal_hosts_data.md
  roles/deploy_bmh/tasks/main.yml
  roles/deploy_bmh/template/bmh-secret.yml.j2
Labels: approved, lgtm

#1442 Wait for secret creation in install_openstack_ca
  roles/install_openstack_ca/tasks/main.yml
Labels: approved, lgtm

#1380 Add Validated Architecture NFV DPDK SR-IOV
  scenarios/reproducers/va-nfv-ovs-dpdk-sriov.yml
Labels: approved, lgtm, ok-to-test

#1415 [openshift_obs] Add support for deploying observability operator
  ci/config/molecule.yaml
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  playbooks/02-infra.yml
  roles/openshift_obs/README.md
  roles/openshift_obs/defaults/main.yml
  roles/openshift_obs/meta/main.yml
  roles/openshift_obs/molecule/default/converge.yml
  roles/openshift_obs/molecule/default/molecule.yml
  roles/openshift_obs/molecule/default/prepare.yml
  roles/openshift_obs/tasks/cleanup.yml
  roles/openshift_obs/tasks/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1451 Drop cifmw_test_operator_tempest_tests_exclude_override_scenario from scenario file
  scenarios/centos-9/multinode-ci.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1448 Update CRC configuration in reproducer
  roles/reproducer/tasks/configure_crc.yml
Labels: approved, lgtm

#1373 Add docs for MakeFile target
  roles/install_yamls/README.md
Labels: approved, lgtm

#1347 Disable swift in hci job
  hooks/playbooks/control_plane_hci_pre_deploy.yml
  scenarios/centos-9/hci_ceph_backends.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#1450 Allow to push secrets on controller-0
  roles/manage_secrets/README.md
  roles/manage_secrets/defaults/main.yml
  roles/manage_secrets/tasks/_push_secret.yml
  roles/manage_secrets/tasks/main.yml
  roles/manage_secrets/tasks/reproducer.yml
  roles/reproducer/molecule/crc_layout/converge.yml
  roles/reproducer/molecule/crc_layout/prepare.yml
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, va-2

#1454 [copy-quay] Add quay api url parameter option
  roles/copy_container/files/copy-quay/config.go
  roles/copy_container/files/copy-quay/config.yaml
  roles/copy_container/files/copy-quay/copy.go
  roles/copy_container/files/copy-quay/go.mod
  roles/copy_container/files/copy-quay/go.sum
  roles/copy_container/files/copy-quay/main.go
  roles/copy_container/files/copy-quay/quayapi.go
  roles/copy_container/files/copy-quay/tag.go
Labels: approved, lgtm

#1456 Restart dnsmasq if available
  ci/playbooks/multinode-customizations.yml
Labels: approved, lgtm

#1428 [reproducer] Add reproducer validations
  docs/source/quickstart/02_prepare_env.md
  reproducer.yml
  roles/reproducer/README.md
  roles/reproducer/defaults/main.yml
  roles/reproducer/tasks/validations.yml
Labels: approved, lgtm

#1364 Try to get a faster re-run for libvirt_manager
  ci/config/molecule.yaml
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/tasks/clean_layout.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/start_manage_vms.yml
  roles/virtualbmc/molecule/default/prepare.yml
Labels: enhancement, approved, lgtm

#1446 Network Values for DPDK SR-IOV
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/network-values/values.yaml.j2
Labels: approved, lgtm, ok-to-test, va-2

#1387 [link2file] Replace given links with source files.
  hooks/playbooks/README.md
  hooks/playbooks/link2file.yml
Labels: approved, lgtm

#1388 [label] Support applying a label on a given resource.
  common-requirements.txt
  hooks/crs/.gitkeep
  roles/run_hook/README.md
  roles/run_hook/tasks/cr.yml
  roles/run_hook/tasks/crd.yml
Labels: approved, lgtm

#1459 [networking_mapper] Save instance's facts for troubleshooting
  roles/networking_mapper/tasks/main.yml
Labels: approved, lgtm

#1462 [cert_manager] Use oc commands to check the status of csv
  roles/cert_manager/tasks/main.yml
Labels: approved, lgtm

#1436 Add new feature in the reproducer: molecule jobs
  roles/reproducer/tasks/ci_data.yml
  roles/reproducer/tasks/ci_deploy_data.yml
  roles/reproducer/tasks/ci_job.yml
  roles/reproducer/tasks/ci_molecule_data.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/libvirt_layout.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/tasks/push_code.yml
  roles/reproducer/templates/play.yml.j2
Labels: enhancement, approved, lgtm

#1466 [deploy_bmh] Add missing field key typo
  roles/deploy_bmh/template/bmh.yml.j2
Labels: approved, lgtm

#1468 [devscripts] Fix patch failure of dev-scripts repo.
  roles/devscripts/files/proxy.patch
Labels: approved, lgtm

#854 Cifmw dashboard validation
  roles/cifmw_cephadm/tasks/dashboard/validation.yml
  roles/cifmw_cephadm/tasks/post.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm, ok-to-test, ceph

#1469 [deploy_bmh] Fix new line char in single line jinja2
  roles/deploy_bmh/template/bmh.yml.j2
Labels: approved, lgtm

#1465 Fix multiple IP addresses listing during collect
  docs/source/usage/01_usage.md
  roles/devscripts/tasks/110_check_ocp.yml
  roles/libvirt_manager/tasks/start_manage_vms.yml
Labels: approved, lgtm

#1472 Hardcode the base dir as it's not properly computed with delegate_to
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#1453 [openshift_login] Only slurp install-yamls-params when update is needed
  roles/openshift_login/tasks/main.yml
Labels: approved, lgtm

#1473 [deploy_bmh] Fix the molecule input file path
  roles/deploy_bmh/molecule/default/converge.yml
  roles/deploy_bmh/tasks/cleanup.yml
Labels: approved, lgtm

#1457 Improve gating content generation in build_openstack_packages role
  ci/playbooks/tcib/tcib.yml
  roles/build_openstack_packages/README.md
  roles/build_openstack_packages/defaults/main.yml
  roles/build_openstack_packages/tasks/create_repo.yml
  roles/pkg_build/templates/pkg_build_play.j2
Labels: approved, lgtm

#1470 cifmw_target_host isn't a mandatory parameter
  roles/reproducer/tasks/validations.yml
Labels: approved, lgtm

#1474 Allow rhel-9.3
  docs/source/quickstart/02_prepare_env.md
  roles/reproducer/defaults/main.yml
Labels: approved, lgtm

#1475 Correct ssh configuration cleaning
  roles/libvirt_manager/tasks/clean_layout.yml
Labels: approved, lgtm

#1476 Correct IP detection
  roles/libvirt_manager/tasks/start_manage_vms.yml
Labels: approved, lgtm

#1479 Toggle nolog to true for architecture deploy
  roles/reproducer/tasks/configure_architecture.yml
Labels: approved, lgtm

#1483 Fix push_code and zuul_vars vs zuul
  roles/reproducer/tasks/push_code.yml
Labels: approved, lgtm

#1418 [bop]Build RPM pkgs from OpenDev Depends On
  ci/playbooks/tcib/tcib.yml
  roles/build_openstack_packages/README.md
  roles/build_openstack_packages/defaults/main.yml
  roles/build_openstack_packages/molecule/default/converge.yml
  roles/build_openstack_packages/tasks/main.yml
  roles/build_openstack_packages/tasks/parse_and_build_pkgs.yml
  roles/build_openstack_packages/tasks/run_dlrn.yml
  roles/pkg_build/templates/pkg_build_play.j2
Labels: approved, lgtm

#1480 Allow to NOT deploy rhos-release on rhel-based computes
  roles/reproducer/README.md
  roles/reproducer/defaults/main.yml
  roles/reproducer/tasks/configure_computes.yml
Labels: approved, lgtm

#1486 Switch to import_role for openshift_login
  playbooks/02-infra.yml
Labels: approved, lgtm

#1460 edpm values template for zeta
  roles/ci_gen_kustomize_values/templates/uni06zeta
Labels: approved, lgtm

#1482 Delete/Recreate openshift marketplace pods
  roles/openshift_setup/tasks/fix_openshift_marketplace.yml
  roles/openshift_setup/tasks/main.yml
Labels: approved, lgtm

#1478 Lock wait_conditions to `oc|kubectl wait` pattern
  roles/kustomize_deploy/molecule/flexible_loop/converge.yml
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm

#1488 Switch from "import" to "include"
  playbooks/02-infra.yml
Labels: approved, lgtm

#1337 Add new role to install and configure Sushy Emulator
  ci/config/molecule.yaml
  docs/dictionary/en-custom.txt
  roles/sushy_emulator/README.md
  roles/sushy_emulator/defaults/main.yml
  roles/sushy_emulator/meta/main.yml
  roles/sushy_emulator/molecule/default/converge.yml
  roles/sushy_emulator/molecule/default/molecule.yml
  roles/sushy_emulator/molecule/default/prepare.yml
  roles/sushy_emulator/tasks/apply_resources.yml
  roles/sushy_emulator/tasks/collect_details.yml
  roles/sushy_emulator/tasks/create_container.yml
  roles/sushy_emulator/tasks/main.yml
  roles/sushy_emulator/tasks/render_resources.yml
  roles/sushy_emulator/templates/config_conf.j2
  roles/sushy_emulator/templates/configmap_yaml.j2
  roles/sushy_emulator/templates/pod_yaml.j2
  roles/sushy_emulator/templates/route_yaml.j2
  roles/sushy_emulator/templates/secret_yaml.j2
  roles/sushy_emulator/templates/service_yaml.j2
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1496 Move generated YAML files to more appropriate location
  roles/reproducer/tasks/configure_architecture.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/templates/content-provider.yml.j2
Labels: approved, lgtm

#1493 Fix relative path for custom CR hook type
  roles/run_hook/tasks/cr.yml
Labels: approved, lgtm

#1498 Don't trigger deployment job on reproducer role change
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#1507 Add "reproducer" role ignore to the right place
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#1506 Ensure the configuration patch works
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/molecule/deploy_layout/molecule.yml
Labels: approved, lgtm

#1503 Replace shell cmds with ansible in append repos task
  roles/build_openstack_packages/tasks/append_repos.yml
  roles/build_openstack_packages/tasks/install_dlrn.yml
Labels: approved, lgtm

#1497 Refactored the `99-logs` playbook to handle all the log files
  playbooks/99-logs.yml
Labels: approved, lgtm

#1508 Delete all the resources of openshift-marketplace
  roles/openshift_setup/molecule/default/converge.yml
  roles/openshift_setup/tasks/fix_openshift_marketplace.yml
Labels: approved, lgtm

#1403 [install_yamls] Skip setting operators_repo var for repos not in openstack-k8s-operators org
  roles/install_yamls/molecule/default/converge.yml
  roles/install_yamls/tasks/zuul_set_operators_repo.yml
Labels: approved, lgtm

#1510 Pinning golang version for doc builds to 1.21.7
  ci/playbooks/pre-doc.yml
Labels: approved, lgtm

#1515 add missing ssh-known-hosts service to hci_prepare
  roles/hci_prepare/tasks/phase1.yml
  roles/hci_prepare/tasks/phase2.yml
Labels: approved, lgtm

#1210 Add shiftstack role
  ci/config/molecule.yaml
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  roles/shiftstack/README.md
  roles/shiftstack/defaults/main.yml
  roles/shiftstack/meta/main.yml
  roles/shiftstack/molecule/default/cleanup.yml
  roles/shiftstack/molecule/default/converge.yml
  roles/shiftstack/molecule/default/molecule.yml
  roles/shiftstack/molecule/default/prepare.yml
  roles/shiftstack/tasks/cleanup.yml
  roles/shiftstack/tasks/deploy_shiftstackclient_pod.yml
  roles/shiftstack/tasks/exec_command_in_pod.yml
  roles/shiftstack/tasks/main.yml
  roles/shiftstack/tasks/pre_test_shiftstack.yml
  roles/shiftstack/tasks/test_shiftstack.yml
  roles/shiftstack/templates/shiftstackclient_pod.yml.j2
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, ok-to-test

#1519 Revert "Pinning golang version for doc builds to 1.21.7"
  ci/playbooks/pre-doc.yml
Labels: approved, lgtm

#1520 Pinning golang version for doc builds to 1.21.7
  ci/playbooks/pre-doc.yml
Labels: approved, lgtm

#1505 Correct reproducer following the zuul -> zuul_vars renaming
  roles/reproducer/tasks/ci_job.yml
  roles/reproducer/tasks/ci_molecule_data.yml
  roles/reproducer/templates/play.yml.j2
Labels: approved, lgtm

#1522 [ci_gen_kustomize_values] - allow overwrite of values.yaml
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
Labels: approved, lgtm

#1530 Exclude main.yml from found_validations
  roles/validations/tasks/main.yml
Labels: approved, lgtm

#1531 Add BM job to edpm_deploy_baremetal role changes
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#1538 Fix ansible lint issue raised in pod job
  roles/shiftstack/molecule/default/cleanup.yml
Labels: approved, lgtm

#1527 edpm values template for beta
  roles/ci_gen_kustomize_values/templates/uni02beta
Labels: approved, lgtm

#1529 Extract podman related bits in its own role
  roles/podman/README.md
  roles/podman/defaults/main.yml
  roles/podman/meta/main.yml
  roles/podman/molecule/default/converge.yml
  roles/podman/molecule/default/molecule.yml
  roles/podman/molecule/default/prepare.yml
  roles/podman/tasks/main.yml
  roles/podman/vars/main.yml
  roles/virtualbmc/tasks/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1543 Add default for cifmw_validations_edpm_check_node
  roles/validations/defaults/main.yml
Labels: approved, lgtm

#1542 Create local PV directories with 0775 permissions
  roles/ci_local_storage/molecule/default/converge.yml
  roles/ci_local_storage/tasks/worker_node_dirs.yml
Labels: approved, lgtm

#1514 Add dnsmasq DHCP to ci_network and devscripts
  roles/ci_network/README.md
  roles/ci_network/defaults/main.yml
  roles/ci_network/tasks/add-static-leases.yml
  roles/ci_network/tasks/apply-dnsmasq.yml
  roles/ci_network/tasks/cleanup-dns.yml
  roles/ci_network/templates/local_domain.conf.j2
  roles/devscripts/molecule/default/converge.yml
  roles/devscripts/tasks/133_host_network.yml
  roles/devscripts/tasks/cleanup.yml
  roles/libvirt_manager/tasks/start_manage_vms.yml
  roles/reproducer/tasks/devscripts_post.yml
Labels: approved, lgtm

#1471 [ci_gen_kustomize_values] Add support to va2 NFV related values.yml
  roles/ci_gen_kustomize_values/README.md
  roles/ci_gen_kustomize_values/defaults/main.yml
  roles/ci_gen_kustomize_values/tasks/edpm_core_asserts.yml
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/edpm-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk/edpm-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/sriov/edpm-values/values.yaml.j2
Labels: approved, lgtm

#1534 [bop]Move dlrn-venv to a proper ansible var
  roles/build_openstack_packages/README.md
  roles/build_openstack_packages/defaults/main.yml
  roles/build_openstack_packages/tasks/cleanup_dlrn.yml
  roles/build_openstack_packages/tasks/install_dlrn.yml
  roles/build_openstack_packages/tasks/run_dlrn.yml
  roles/build_openstack_packages/templates/run_dlrn.sh.j2
Labels: approved, lgtm

#1545 [bop] Lower the priority of DLRN repo while using gating repo
  roles/build_openstack_packages/tasks/create_repo.yml
Labels: approved, lgtm

#1544 [devscripts] Fix lookup of OpenShift api and ingress IP addresses
  roles/devscripts/tasks/110_check_ocp.yml
  roles/devscripts/tasks/133_host_network.yml
  roles/devscripts/tasks/get_ocp_vips.yml
Labels: approved, lgtm

#1537 Ensure we know what template has been used
  .pre-commit-config.yaml
  Makefile
  roles/ci_gen_kustomize_values/README.md
  roles/ci_gen_kustomize_values/templates/common/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/common/olm/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/hci/edpm-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/edpm-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk/edpm-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/sriov/edpm-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni01alpha/network-values/values.yaml.j2
  scripts/check_k8s_snippets_comment.sh
Labels: approved, lgtm

#1550 Add a cifmw_cephadm_min_compat_client default value
  roles/cifmw_cephadm/defaults/main.yml
Labels: approved, lgtm

#1553 [docs] Fix README links to old cookbook path
  roles/reproducer/README.md
  scenarios/reproducers/README.md
Labels: approved, lgtm

#1541 ironic-operatpr - Disable TestNodesVif tempest
  roles/test_operator/files/list_skipped.yml
Labels: approved, lgtm

#1557 [deploy_bmh] Fix labels identation in bmh jinja
  roles/deploy_bmh/template/bmh.yml.j2
Labels: approved, lgtm

#1558 Collect openshift-marketplace related logs and resources in CI
  roles/os_must_gather/defaults/main.yml
Labels: approved, lgtm

#1556 Install cert_manager from release manifest
  roles/cert_manager/defaults/main.yml
  roles/cert_manager/tasks/main.yml
  roles/cert_manager/tasks/olm_manifest.yml
  roles/cert_manager/tasks/release_manifest.yml
  scenarios/centos-9/multinode-ci.yml
Labels: approved, lgtm

#1562 Fix networking on newer CRC
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1563 Use base.yaml irrelevant file list
  zuul.d/podified_multinode.yaml
  zuul.d/project-templates.yaml
Labels: approved, lgtm

#1555 [rhol_crc] Increase default memory
  roles/rhol_crc/vars/main.yml
Labels: approved, lgtm

#1568 Use official way of installing cmtcl
  roles/cert_manager/tasks/validate_certs.yml
Labels: approved, lgtm

#1528 Change to YAML stdout for Ansible
  ansible.cfg
Labels: approved, lgtm

#1572 Consider test_timeout in architecture deploy timeout
  roles/reproducer/tasks/configure_architecture.yml
Labels: approved, lgtm

#1422 Append git version to cifmw galaxy collection
  scripts/setup_molecule
Labels: enhancement, approved, lgtm

#1458 [bop]Build DLRN packages from downstream changes
  docs/dictionary/en-custom.txt
  roles/build_openstack_packages/README.md
  roles/build_openstack_packages/defaults/main.yml
  roles/build_openstack_packages/tasks/append_repos.yml
  roles/build_openstack_packages/tasks/downstream.yml
  roles/build_openstack_packages/tasks/install_dlrn.yml
  roles/build_openstack_packages/tasks/run_dlrn.yml
  roles/build_openstack_packages/templates/projects.ini.j2
  roles/build_openstack_packages/templates/run_dlrn.sh.j2
  roles/pkg_build/vars/main.yml
Labels: approved, lgtm
