Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-12, with the labels that each got.

#2581 Add empty list as default for adoption scenarios without networker nodes
  roles/adoption_osp_deploy/templates/adoption_vars.yaml.j2
Labels: approved, lgtm, Ready For Review

#2574 Override Ceph version
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/bootstrap.yml
  roles/cifmw_cephadm/tasks/install_cephadm.yml
  roles/cifmw_cephadm/tasks/pre.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm, Ready For Review

#2583 Fix create-infra.yml sushy-emulator
  create-infra.yml
Labels: approved, lgtm, Ready For Review

#2586 base_extra_patches variable name was wrong
  roles/ci_gen_kustomize_values/filter_plugins/cifmw_gen_kustomize_values_b64_combine.py
Labels: approved, lgtm, Ready For Review

#2579 [test-operator][tobiko] Change downloaded images path
  roles/test_operator/vars/main.yml
Labels: approved, lgtm, Ready For Review

#2560 Add create xml results file to validations role
  roles/validations/defaults/main.yml
  roles/validations/filter_plugins/cifmw_validations_xml_filter.py
  roles/validations/tasks/main.yml
  roles/validations/tasks/run_validation.yml
Labels: approved, lgtm, Ready For Review

#2582 Set Cinder customServiceConfig globally in DCN DT
  roles/ci_dcn_site/templates/service-values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2423 Add nova multiplecells nodeset templates
  roles/ci_gen_kustomize_values/templates/nova-three-cells/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/nova-three-cells/edpm-nodeset2-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2585 Reprocuder: write ironic_nodes.yaml
  roles/reproducer/defaults/main.yml
  roles/reproducer/tasks/generate_bm_info.yml
Labels: approved, lgtm, Ready For Review

#2605 Add dynamic DCB configuration to Juniper switches
  roles/switch_config/tasks/junos_config.yml
Labels: approved, lgtm, needs-ok-to-test, Ready For Review

#2568 Prepare a codeowners file for github actions
  .github/CODEOWNERS
Labels: approved, lgtm, Ready For Review

#2374 Allow setting order and hooks for test role
  docs/source/usage/01_usage.md
  roles/shiftstack/README.md
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/main.yml
  roles/test_operator/tasks/runners/ansibletest_runner.yml
  roles/test_operator/tasks/runners/horizontest_runner.yml
  roles/test_operator/tasks/runners/tempest_runner.yml
  roles/test_operator/tasks/runners/tobiko_runner.yml
  roles/test_operator/tasks/stages.yml
  roles/test_operator/tasks/tempest-tests.yml
  roles/test_operator/tasks/tobiko-tests.yml
  scenarios/centos-9/ceph_backends.yml
  scenarios/centos-9/hci_ceph_backends.yml
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
  scenarios/reproducers/va-common.yml
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, va-2, Ready For Review

#2597 [DCN] Update network values template
  roles/ci_gen_kustomize_values/templates/dcn/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2603 Add checks for cifmw_devscripts_create_logical_volume is defined
  roles/reproducer/tasks/ocp_layout_assertions.yml
Labels: approved, lgtm, Ready For Review

#2595 [DOCS] Add note about Zuul job reproducer support and testing
  docs/source/reproducers/03-zuul.md
Labels: approved, lgtm, Ready For Review

#2598 Save kuttl JUnitXML result files
  ci/playbooks/kuttl/run-kuttl-tests.yml
Labels: approved, lgtm, Ready For Review

#2602 Adoption - hook post OSP 17.1 OC ironic
  hooks/playbooks/adoption_ironic_post_oc.yml
Labels: approved, lgtm, Ready For Review

#2619 [test_operator][tobiko] Download default customized guest image
  docs/dictionary/en-custom.txt
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/vars/main.yml
Labels: approved, lgtm, Ready For Review

#2608 [ci_gen_kustomize_values] Allow reject vars patches
  roles/ci_gen_kustomize_values/README.md
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
Labels: approved, lgtm, Ready For Review

#2607 Consider that the zuul executor may be an IP
  ci/playbooks/multinode-autohold.yml
Labels: approved, lgtm, Ready For Review

#2541 Add nodeset2 for scenarios using 2 nodesets
  docs/source/baremetal/01_baremetal_hosts_data.md
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov-2nodesets/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov-2nodesets/edpm-nodeset2-values/values.yaml.j2
  roles/deploy_bmh/template/bmh.yml.j2
  scenarios/reproducers/dt-nfv-ovs-dpdk-sriov-2nodesets.yml
Labels: approved, lgtm, Ready For Review

#2572 [shiftstack]Enable the option to run the role isolated
  roles/shiftstack/README.md
  roles/shiftstack/defaults/main.yml
  roles/shiftstack/molecule/default/converge.yml
  roles/shiftstack/tasks/pre_test_shiftstack.yml
  roles/shiftstack/tasks/test_config.yml
Labels: approved, lgtm, Ready For Review

#2549 Support new OpenStack initialization resource for RHOSO install
  roles/edpm_prepare/tasks/main.yml
  roles/kustomize_deploy/defaults/main.yml
  roles/kustomize_deploy/tasks/install_operators.yml
Labels: approved, lgtm, Ready For Review

#2563 Add hook to enable horizon
  hooks/playbooks/control_plane_horizon.yml
  scenarios/centos-9/horizon.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm, Ready For Review

#2623 [autohold playbook] Add missing bracket
  ci/playbooks/multinode-autohold.yml
Labels: approved, lgtm, Ready For Review
