Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-08, with the labels that each got.

#2181 Remove old unused CRC nodesets
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#2147 dump more ceph cluster info during deployment
  roles/cifmw_cephadm/tasks/post.yml
Labels: approved, lgtm, Ready For Review

#2173 manila share type: do not fail if share exists
  hooks/playbooks/manila_create_default_resources.yml
Labels: approved, lgtm, Ready For Review

#2182 [ci_lvmns_storage] Wait for all LVMS nodes to be ready
  roles/ci_lvms_storage/README.md
  roles/ci_lvms_storage/defaults/main.yml
  roles/ci_lvms_storage/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2056 Adds RDO third party check job for whitebox neutron tempest plugin
  zuul.d/edpm_multinode.yaml
  zuul.d/nodeset.yaml
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2188 [nat64_appliance] Check if virtqemud socket exists during the cleanup
  roles/nat64_appliance/tasks/cleanup.yml
Labels: approved, lgtm, Ready For Review

#2192 [ci_lvmns_storage] Wait for all LVMS nodes to be ready
  roles/ci_lvms_storage/README.md
  roles/ci_lvms_storage/defaults/main.yml
  roles/ci_lvms_storage/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2185 nit: Update project guidelines to define approval policy
  docs/source/development/01_guidelines.md
Labels: approved, lgtm, Ready For Review

#1907 Dropping dataplane-operator references
  roles/build_openstack_packages/defaults/main.yml
  roles/edpm_deploy/tasks/main.yml
  roles/edpm_deploy_baremetal/tasks/main.yml
  roles/validations/tasks/edpm/hotfix.yml
  roles/validations/tasks/edpm/hugepages_and_reboot.yml
  roles/validations/tasks/edpm/scaledown.yml
  tests/integration/targets/make/files/get_makefiles_env/expected_variables_values.yml
  tests/integration/targets/make/files/get_makefiles_env/makefiles/Makefile
  zuul.d/base.yaml
  zuul.d/tempest_multinode.yaml
Labels: approved, lgtm, Ready For Review

#2189 Return proper full hash for component repos
  roles/repo_setup/tasks/artifacts.yml
Labels: approved, lgtm, Ready For Review

#2186 Ensure ocp is reachable from ocpbm before deploying
  reproducer.yml
  roles/reproducer/tasks/configure_architecture.yml
Labels: approved, lgtm, Ready For Review

#2191 Add _openstack_final_env to set final env filename
  playbooks/update.yml
  roles/set_openstack_containers/README.md
  roles/set_openstack_containers/defaults/main.yml
  roles/set_openstack_containers/tasks/main.yml
Labels: approved, lgtm, minor update, Ready For Review

#2143 Prepare for FQDN unique names: controller-0 match
  playbooks/06-deploy-architecture.yml
Labels: approved, lgtm, Ready For Review, unique-fqdn

#2187 Change order of if-elif conditionals in set_openstack_containers template
  roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm, minor update, Ready For Review

#2155 Improve error handling of `get CA bundle data task`
  roles/install_openstack_ca/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2196 Use separate test_operator artifacts basedir for update test run
  update-edpm.yml
Labels: approved, lgtm, Ready For Review

#2164 Use inventory_hostname in ceph related roles and play
  ci/playbooks/multinode-customizations.yml
  playbooks/06-deploy-edpm.yml
  playbooks/ceph.yml
  roles/cifmw_cephadm/README.md
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/cephfs.yml
  roles/cifmw_cephadm/tasks/rgw.yml
Labels: approved, lgtm, Ready For Review, unique-fqdn

#2204 nit: Update CodeQL version to 3
  .github/workflows/codeql.yml
Labels: approved, lgtm, Ready For Review

#2175 [reproducer] Call switches config if available
  docs/source/usage/01_usage.md
  playbooks/switches_config.yml
  reproducer.yml
  roles/ci_setup/vars/main.yml
  roles/ci_setup/vars/redhat.yml
  roles/switch_config/tasks/junos_config.yml
Labels: approved, lgtm, Ready For Review

#2206 Ensure we gather devscripts deployment logs
  roles/devscripts/defaults/main.yml
  roles/devscripts/molecule/default/converge.yml
  roles/devscripts/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2210 [switch_config] Fix pip install
  playbooks/switches_config.yml
Labels: approved, lgtm, Ready For Review

#2211 [dev-scripts] Capture make log
  roles/devscripts/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2203 [install_openstack_ca] Refactor main.yml
  roles/install_openstack_ca/README.md
  roles/install_openstack_ca/defaults/main.yml
  roles/install_openstack_ca/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2213 Ensure we get a timeout for node listing
  roles/openshift_adm/README.md
  roles/openshift_adm/defaults/main.yml
  roles/openshift_adm/tasks/_get_nodes.yml
  roles/openshift_adm/tasks/api_cert.yml
  roles/openshift_adm/tasks/main.yml
  roles/openshift_adm/tasks/shutdown.yml
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: approved, lgtm, Ready For Review

#2198 Consolidate conditions triggering re-deploy
  roles/devscripts/molecule/check_cluster_status/tasks/test.yml
  roles/devscripts/tasks/100_pre.yml
  roles/devscripts/tasks/110_check_ocp.yml
  roles/devscripts/tasks/111_verify_cluster.yml
  roles/devscripts/tasks/112_verify_golden_image.yml
  roles/devscripts/tasks/300_post.yml
  roles/devscripts/tasks/cleanup.yml
  roles/devscripts/tasks/main.yml
  roles/reproducer/tasks/ocp_layout.yml
Labels: approved, lgtm, Ready For Review

#2212 [switch_config] Multiple configs per run
  docs/dictionary/en-custom.txt
  roles/switch_config/README.md
  roles/switch_config/defaults/main.yml
  roles/switch_config/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2219 Don't use ansible_domain if empty string
  hooks/playbooks/fetch_compute_facts.yml
  playbooks/nfs.yml
Labels: approved, lgtm, Ready For Review

#2218 Set required vars for update_containers role in reproducer tcib job
  roles/reproducer/templates/content-provider.yml.j2
Labels: approved, lgtm, Ready For Review

#2216 Add telemetry to list_allowed.yml
  roles/test_operator/files/list_allowed.yml
Labels: approved, lgtm, Ready For Review

#2233 Pass {{ job_id }}-params/zuul-params.yml to reproducer play job
  roles/reproducer/templates/play.yml.j2
Labels: approved, lgtm, Ready For Review

#2202 Added periodic whitebox neutron tempest plugin job
  zuul.d/edpm_periodic.yaml
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2226 Allow to chose which network is the default gateway
  docs/dictionary/en-custom.txt
  roles/libvirt_manager/README.md
  roles/libvirt_manager/tasks/create_networks.yml
Labels: approved, lgtm, Ready For Review

#2229 Move from ansible package to ansible-core
  galaxy.yml
  meta/runtime.yml
  requirements.yml
  test-requirements.txt
Labels: approved, lgtm, Ready For Review

#2221 Create a role for uploading results to Report portal
  roles/reportportal/README.md
  roles/reportportal/defaults/main.yml
  roles/reportportal/molecule/default/converge.yml
  roles/reportportal/molecule/default/files/metadata-golden.json
  roles/reportportal/molecule/default/molecule.yml
  roles/reportportal/tasks/main.yaml
  roles/reportportal/templates/metadata.json.j2
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, ok-to-test, Ready For Review

#2237 Update switch role modules
  galaxy.yml
  hooks/playbooks/switch_config.yml
  requirements.yml
  roles/switch_config/tasks/ios_config.yml
  roles/switch_config/tasks/junos_config.yml
Labels: approved, lgtm, va-2, Ready For Review

#2240 Update switch role modules
  playbooks/switches_config.yml
  roles/switch_config/tasks/junos_config.yml
Labels: approved, lgtm, Ready For Review

#2234 Update precommit hooks and add shellcheck
  .pre-commit-config.yaml
Labels: approved, lgtm, Ready For Review

#2253 fix dvr tests regex in whitebox_neutron_tempest_jobs.yaml
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, ok-to-test, Ready For Review

#2252 Added VA HCI trigger experimental job
  ci/templates/projects.yaml
  zuul.d/projects.yaml
  zuul.d/trigger_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2248 Optimize Ceph log collection and optionally dump to file
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/logs.yml
  roles/cifmw_cephadm/tasks/post.yml
Labels: approved, lgtm, Ready For Review

#1794 Prepare crc job for architecture repo
  ci/playbooks/architecture_crc/prepare-architecture-crc.yml
  ci/playbooks/architecture_crc/run-architecture-crc.yml
  ci/playbooks/multinode-customizations.yml
  ci/playbooks/pre-ci-bootstrap.yml
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  playbooks/06-deploy-architecture.yml
  zuul.d/architecture-jobs.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#2251 Remove openstack collection from requirements
  galaxy.yml
  plugins/modules/application_credential.py
  requirements.yml
Labels: approved, lgtm, Ready For Review

#2254 Add CI job URL to the polarion report
  roles/polarion/defaults/main.yml
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2259 Allow to retry adding a host in vbmc
  roles/virtualbmc/tasks/manage_host.yml
Labels: approved, lgtm, Ready For Review

#2245 Switch modules update
  roles/switch_config/tasks/ios_config.yml
  roles/switch_config/tasks/junos_config.yml
Labels: approved, lgtm, Ready For Review

#2265 [pre-commit] Remove `bashate` hook
  .pre-commit-config.yaml
Labels: approved, lgtm, Ready For Review

#2266 Clear ether options for nics
  roles/switch_config/tasks/junos_config.yml
Labels: approved, lgtm, Ready For Review

#2274 Prefer the zuul items from run before the job to reproduce
  roles/reproducer/tasks/push_code.yml
Labels: approved, lgtm, Ready For Review

#2257 Add new role - build_push_container
  docs/dictionary/en-custom.txt
  roles/build_push_container/README.md
  roles/build_push_container/defaults/main.yml
  roles/build_push_container/meta/main.yml
  roles/build_push_container/molecule/default/converge.yml
  roles/build_push_container/molecule/default/files/containerfile
  roles/build_push_container/molecule/default/molecule.yml
  roles/build_push_container/tasks/cleanup.yml
  roles/build_push_container/tasks/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#2261 Use libvirt_manager extra_disks for Ceph OSDs
  docs/dictionary/en-custom.txt
  playbooks/ceph.yml
  roles/cifmw_cephadm/README.md
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm, Ready For Review

#2228 Add a role to run compliance scans against the compute nodes and control plane
  deploy-edpm.yml
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  playbooks/09-compliance.yml
  roles/artifacts/tasks/edpm.yml
  roles/compliance/README.md
  roles/compliance/defaults/main.yml
  roles/compliance/meta/main.yml
  roles/compliance/molecule/default/converge.yml
  roles/compliance/molecule/default/molecule.yml
  roles/compliance/tasks/cleanup.yml
  roles/compliance/tasks/create_scap_report.yml
  roles/compliance/tasks/install.yml
  roles/compliance/tasks/main.yml
  roles/compliance/tasks/run_compute_node_scans.yml
  roles/compliance/tasks/run_operator_scan.yml
  roles/compliance/tasks/run_suite_scan.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review, tide/merge-method-squash

#2283 Use libvirt_manager extra_disks for Ceph OSDs
  docs/dictionary/en-custom.txt
  playbooks/ceph.yml
  roles/cifmw_cephadm/README.md
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm, Ready For Review

#2246 Add a hook that deploys Ceph on BMO nodes
  hooks/playbooks/ceph-bm.yml
  playbooks/ceph.yml
Labels: approved, lgtm, Ready For Review

#2256 Added trigger downstream job github action
  .github/workflows/github-action-trigger-downstream-job.yaml
Labels: approved, lgtm, Ready For Review

#2282 Enable the ovn dbs monitoring test
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review
