Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-10, with the labels that each got.

#2398 Make HCI architecture repo parameterizable
  scenarios/reproducers/dt-nfv-ovs-dpdk-sriov-hci.yml
Labels: approved, lgtm, Ready For Review

#2392 Revert "Pin devscripts repo at working hash"
  roles/devscripts/vars/main.yml
Labels: approved, lgtm, Ready For Review, github-experimental

#2417 Allow passing args to deploy-architecture.sh
  docs/source/usage/01_usage.md
  reproducer.yml
Labels: approved, lgtm, Ready For Review

#2401 Ignore non-vars file in fetch_compute_facts
  hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm, Ready For Review

#2413 Wait until ocp cluster is ready in adoption playbook
  deploy-ocp.yml
Labels: approved, lgtm, Ready For Review

#2402 Improve adoption coverage for openstack-operator
  zuul.d/adoption.yaml
Labels: approved, lgtm, Ready For Review

#2409 Add extra disks and switch dt-pidone to lvms
  scenarios/reproducers/va-pidone.yml
Labels: approved, lgtm, Ready For Review

#2396 [sushy_emulator] Make instance whitelist optional
  roles/sushy_emulator/tasks/collect_details.yml
Labels: approved, lgtm, Ready For Review

#2408 Verify RGW VIP is properly configured
  playbooks/ceph.yml
  roles/cifmw_cephadm/tasks/configure_object.yml
  roles/cifmw_cephadm/tasks/post.yml
  roles/cifmw_cephadm/tasks/rgw.yml
  roles/cifmw_cephadm/templates/ceph_rgw.yml.j2
Labels: approved, lgtm, Ready For Review, github-experimental

#2388 Make `^nodes?(_[0-9]+)?$` keys removal configurable
  roles/ci_gen_kustomize_values/README.md
  roles/ci_gen_kustomize_values/defaults/main.yml
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
Labels: approved, lgtm, Ready For Review

#2400 [ci-boostrap] Add second call to the mapper to ingest interface-info
  ci/playbooks/bootstrap-networking-mapper.yml
  zuul.d/base.yaml
Labels: approved, lgtm, Ready For Review

#2381 Add tempest cleanup opt
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm

#2382 Donot run EDPM/adoption job zuui.d/trigger_jobs.yaml changes
  zuul.d/adoption.yaml
  zuul.d/base.yaml
Labels: approved, lgtm, Ready For Review

#2393 Only consider ocps networks for network-values template
  roles/ci_gen_kustomize_values/templates/bgp/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/common/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/shiftstack/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni01alpha/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni04delta-ipv6/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni05epsilon/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni06zeta/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni07eta/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review, github-experimental

#2412 Enable running the test-operator role multiple times
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/run-test-operator-job.yml
  roles/test_operator/vars/main.yml
Labels: approved, lgtm, Ready For Review

#2424 Wait for InstallPlan to complete when installing the OSP operators
  docs/dictionary/en-custom.txt
  roles/kustomize_deploy/README.md
  roles/kustomize_deploy/defaults/main.yml
  roles/kustomize_deploy/tasks/install_operators.yml
Labels: approved, lgtm, Ready For Review, github-experimental

#2293 Listallowed telemetry tests
  roles/test_operator/files/list_allowed.yml
Labels: approved, lgtm, Ready For Review

#2307 Allow set debug mode for Tempest
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2433 Use extra disks on compute nodes for ceph
  scenarios/reproducers/va-dcn.yml
Labels: approved, lgtm, Ready For Review

#2434 [edpm_deploy_baremetal] Allow passing extra nova-compute config
  roles/edpm_deploy_baremetal/README.md
  roles/edpm_deploy_baremetal/defaults/main.yml
  roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2428 Update DCN scenario parameters
  scenarios/reproducers/va-dcn.yml
Labels: approved, lgtm, needs-ok-to-test, Ready For Review

#2437 Revert "Prepare crc job for architecture repo"
  ci/playbooks/architecture_crc/prepare-architecture-crc.yml
  ci/playbooks/architecture_crc/run-architecture-crc.yml
  ci/playbooks/bootstrap-networking-mapper.yml
  ci/playbooks/multinode-customizations.yml
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  playbooks/06-deploy-architecture.yml
  zuul.d/architecture-jobs.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review, github-experimental

#2440 Re add traffic logging tests to skiplist
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2442 Add correct issue to skipped traffic logging tests
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2371 Add the Ironic baremetal net in a dedicated ci-bootstrap job
  ci/playbooks/bootstrap-networking-mapper.yml
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#2446 Ensure crc dnsmasq server entries are not duplicated
  ci/playbooks/multinode-customizations.yml
Labels: approved, lgtm, Ready For Review

#2443 Enable tempest in edpm baremetal check job
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: approved, lgtm, Ready For Review

#2435 Add trigger job definitions for uni02beta job
  zuul.d/trigger_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2439 Fix sshd range ipv6
  playbooks/06-deploy-architecture.yml
Labels: approved, lgtm, Ready For Review

#2447 Make _arch_repo parametrizable
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
  scenarios/reproducers/dt-osasinfra.yml
  scenarios/reproducers/va-hci-base.yml
  scenarios/reproducers/va-nfv-ovs-dpdk-sriov.yml
  scenarios/reproducers/va-nfv-ovs-sriov.yml
  scenarios/reproducers/va-pidone.yml
Labels: approved, lgtm, Ready For Review

#2386 Add support to deploy sushy in extracted jobs
  docs/source/usage/01_usage.md
  playbooks/02-infra.yml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm, Ready For Review

#2432 libvirt_manager/extra_net_config - nmstate format
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/molecule/ocp_layout/converge.yml
  roles/libvirt_manager/molecule/ocp_layout/vars/net-def.yml
  roles/libvirt_manager/tasks/create_networks.yml
Labels: approved, lgtm, Ready For Review

#2452 Template changes to get uni job in trigger line
  ci/templates/projects.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#2455 [18.0.0-proposed] Make _arch_repo parametrizable
  scenarios/reproducers/bgp-4-racks-3-ocps.yml
  scenarios/reproducers/dt-osasinfra.yml
  scenarios/reproducers/va-hci-base.yml
  scenarios/reproducers/va-nfv-ovs-dpdk-sriov.yml
  scenarios/reproducers/va-nfv-ovs-sriov.yml
  scenarios/reproducers/va-pidone.yml
Labels: approved, lgtm, needs-ok-to-test, Ready For Review

#2397 Pass tcib-extras tcib_package while building containers from source
  roles/build_containers/templates/build_containers.sh.j2
Labels: approved, lgtm, Ready For Review

#2461 Don't rely on all-group.yaml for adoption osp role
  deploy-osp-adoption.yml
Labels: approved, lgtm, Ready For Review

#2448 [test-operator] Expose SELinuxLevel parameter
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2389 Make sure set_openstack_container is less depedent on instal_yamls
  playbooks/update.yml
  roles/set_openstack_containers/defaults/main.yml
  roles/set_openstack_containers/tasks/main.yml
  roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm, minor update, Ready For Review

#2425 DT - BMO deploy with preprovisioningNetworkData
  roles/ci_gen_kustomize_values/templates/bmo01/baremetalhost-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bmo01/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bmo01/nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bmo01/secret-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2460 Reduce the days to stale a PR to 22
  .github/workflows/stale-pr.yml
Labels: approved, lgtm, Ready For Review

#2445 Don't consider non-ocp vms for deploy-ocp
  deploy-ocp.yml
Labels: approved, lgtm, Ready For Review

#2462 Collect ovs logs from the journal
  roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm, Ready For Review

#2457 Add uni02beta jobs triggering - 18.0.0-proposed
  ci/templates/projects.yaml
  zuul.d/projects.yaml
  zuul.d/trigger_jobs.yaml
Labels: approved, lgtm, Ready For Review

#2449 Enable COO in osasinfra DT
  scenarios/reproducers/dt-osasinfra.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#2321 Integrate set_openstack_containers in validated architecture playbook
  docs/source/usage/01_usage.md
  playbooks/06-deploy-architecture.yml
Labels: approved, lgtm, minor update, Ready For Review

#2474 Copy container-prepare file if defined in scenario
  roles/adoption_osp_deploy/tasks/prepare_undercloud.yml
Labels: approved, lgtm, Ready For Review

#2476 [ci_nmstate] Conditionally call ci_nmstate
  playbooks/02-infra.yml
Labels: approved, lgtm, Ready For Review

#2479 [update_containers] Fix typo ceilometerSgcoreImage
  roles/update_containers/templates/update_containers.j2
Labels: approved, lgtm, Ready For Review

#2472 Bootstrap libvirt in adoption infra playbook
  playbooks/adoption/infra.yml
Labels: approved, lgtm, Ready For Review

#2471 Enable RHCS 7 in 17 TripleO deployment
  hooks/playbooks/adoption_deploy_ceph.yml
  roles/adoption_osp_deploy/defaults/main.yml
  roles/adoption_osp_deploy/tasks/prepare_undercloud.yml
Labels: approved, lgtm, Ready For Review

#2430 Do not run control plane testing while openstackclient is updated.
  roles/update/README.md
  roles/update/defaults/main.yml
  roles/update/templates/workload_launch_k8s.sh.j2
Labels: approved, lgtm, minor update, Ready For Review

#1980 [OSASINFRA] Add multi test configs support
  roles/shiftstack/README.md
  roles/shiftstack/defaults/main.yml
  roles/shiftstack/molecule/default/converge.yml
  roles/shiftstack/tasks/deploy_shiftstackclient_pod.yml
  roles/shiftstack/tasks/exec_command_in_pod.yml
  roles/shiftstack/tasks/pre_test_shiftstack.yml
  roles/shiftstack/tasks/test_config.yml
  roles/shiftstack/tasks/test_shiftstack.yml
Labels: approved, lgtm

#2120 [BGP] Add octavia routes to network-values template
  roles/ci_gen_kustomize_values/templates/bgp_dt01/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2469 [polarion] Remove results_merged.xml files
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2458 Introduce ci_dcn_site role
  docs/dictionary/en-custom.txt
  playbooks/dcn.yml
  roles/ci_dcn_site/README.md
  roles/ci_dcn_site/defaults/main.yml
  roles/ci_dcn_site/meta/main.yml
  roles/ci_dcn_site/tasks/az.yml
  roles/ci_dcn_site/tasks/ceph.yml
  roles/ci_dcn_site/tasks/main.yml
  roles/ci_dcn_site/tasks/post-ceph.yml
  roles/ci_dcn_site/tasks/pre-ceph.yml
  roles/ci_dcn_site/tasks/set_network_facts.yml
  roles/ci_dcn_site/templates/deployment/values.yaml.j2
  roles/ci_dcn_site/templates/edpm-pre-ceph/deployment/values.yaml.j2
  roles/ci_dcn_site/templates/edpm-pre-ceph/nodeset/values.yaml.j2
  roles/ci_dcn_site/templates/network-values/values.yaml.j2
  roles/ci_dcn_site/templates/service-values.yaml.j2
  roles/ci_dcn_site/templates/values.yaml.j2
  scenarios/reproducers/dt-dcn.yml
Labels: approved, lgtm, Ready For Review

#2484 Do not mount non-existing controller private key
  roles/test_operator/tasks/tempest-tests.yml
  roles/test_operator/vars/main.yml
Labels: approved, lgtm, Ready For Review

#2465 [OSPCIX-532] Set volume.catalog_type to volumev3
  roles/tempest/vars/main.yml
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2477 [install_yamls] Allow install_yamls env vars patches
  roles/install_yamls/README.md
  roles/install_yamls/molecule/default/converge.yml
  roles/install_yamls/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2492 libvirt_manager extra nets - firewall zone
  roles/libvirt_manager/README.md
  roles/libvirt_manager/molecule/ocp_layout/converge.yml
  roles/libvirt_manager/tasks/create_networks.yml
Labels: approved, lgtm, Ready For Review

#2349 Run ceph update if part of the deployment
  playbooks/update.yml
  roles/cifmw_ceph_spec/defaults/main.yml
  roles/cifmw_ceph_spec/templates/initial_ceph.conf.j2
  roles/cifmw_cephadm/tasks/ceph_upgrade.yml
Labels: approved, lgtm, minor update, Ready For Review

#2498 Add missing molecule jobs for roles
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#2494 Update Molecule config for local use
  .config/molecule/config_podman.yml
Labels: approved, lgtm, Ready For Review

#2493 Remove unused glance backends in ci_dcn_site role
  roles/ci_dcn_site/tasks/main.yml
  roles/ci_dcn_site/tasks/post-ceph.yml
  roles/ci_dcn_site/templates/service-values.yaml.j2
  roles/ci_dcn_site/templates/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2485 Add missing node groups for multicell nodeset
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#2497 [os_net_setup] Add --availability-zone-hint to network creation
  roles/os_net_setup/defaults/main.yml
  roles/os_net_setup/templates/network_command.j2
Labels: approved, lgtm, Ready For Review
