Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-07, with the labels that each got.

#1988 Remove "domain" from subnets
  roles/libvirt_manager/tasks/create_networks.yml
Labels: approved, lgtm, Ready For Review

#1982 Fix variable name so it reaches reproducer-variables
  roles/ci_lvms_storage/README.md
  roles/ci_lvms_storage/defaults/main.yml
  roles/ci_lvms_storage/templates/lvms-cluster.yaml.j2
Labels: approved, lgtm, Ready For Review

#1985 Don't run deployment upon nat64_appliance changes
  zuul.d/base.yaml
Labels: approved, lgtm, Ready For Review

#1994 Correct prefix replacement in network names
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
Labels: approved, lgtm, Ready For Review

#1996 Add storageclass in cifmw_test_operator_tobiko_config
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, ok-to-test, Ready For Review

#1968 Create a new .utility DNS zone
  roles/libvirt_manager/tasks/ocp_layout.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/generate_bm_info.yml
  roles/reproducer/tasks/ocp_layout.yml
  roles/reproducer/tasks/prepare_networking.yml
  roles/sushy_emulator/README.md
  roles/sushy_emulator/defaults/main.yml
  roles/sushy_emulator/molecule/default/converge.yml
  roles/sushy_emulator/molecule/default/vars/input.yml
  roles/sushy_emulator/tasks/collect_details.yml
  roles/sushy_emulator/tasks/create_container.yml
  roles/sushy_emulator/tasks/verify.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1995 [ci_nmstate] Allow users to directly use the unprovisioned tasks
  roles/ci_nmstate/README.md
  roles/ci_nmstate/filter_plugins/ci_nmstate_map_instance_nets.py
  roles/ci_nmstate/tasks/main.yml
  roles/ci_nmstate/tasks/nmstate_k8s_install.yml
  roles/ci_nmstate/tasks/nmstate_unmanaged_provision_node.yml
Labels: approved, lgtm, Ready For Review

#2010 Add is_vlan_transparent in os_net_setup role
  roles/os_net_setup/tasks/subtask_net.yml
Labels: approved, lgtm, needs-ok-to-test, Ready For Review

#2008 Wait until OpenStack operators ready in kustomize_deploy role
  roles/kustomize_deploy/tasks/install_operators.yml
Labels: approved, lgtm, Ready For Review

#2014 Changes to virtualbmc shouldn't trigger a deployment
  zuul.d/base.yaml
Labels: approved, lgtm, Ready For Review

#2013 Disable GSSAPI authentication in vbmc container
  roles/virtualbmc/molecule/default/prepare.yml
  roles/virtualbmc/molecule/default/vars/net-def.yml
  roles/virtualbmc/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#1986 Add a hook to increase quotas for project service
  hooks/playbooks/service-project-more-quota.yml
Labels: approved, lgtm, Ready For Review

#1970 Hook ironic inspect nodes
  hooks/playbooks/ironic_provide_nodes.yml
Labels: approved, lgtm, uni01alpha

#1990 hook - ironic enroll nodes - set port physical_network
  hooks/playbooks/ironic_enroll_nodes.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1903 Add a new extra variable for holding the update's parameters
  ci/playbooks/edpm/update.yml
  roles/update/README.md
Labels: approved, lgtm, minor update, Ready For Review

#2011 validate-architecture - sshd_ranges - ipv6
  ci/playbooks/architecture/validate-architecture.yml
Labels: approved, lgtm, Ready For Review, ipv6

#2002 [reproducer] Clean last mentions of ipv4-only
  roles/reproducer/tasks/configure_computes.yml
  roles/reproducer/tasks/libvirt_layout.yml
  roles/reproducer/tasks/prepare_networking.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1975 Create dummy interfaces with ci_nmstate
  roles/libvirt_manager/tasks/create_networks.yml
Labels: approved, lgtm, Ready For Review, ipv6

#2004 [libvirt_manager] Clean last mentions of ipv4-only
  roles/libvirt_manager/molecule/deploy_layout/prepare.yml
  roles/libvirt_manager/molecule/deploy_layout/vars/input.yml
  roles/libvirt_manager/molecule/spine_leaf/prepare.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/generate_networking_data.yml
  roles/libvirt_manager/tasks/manage_vms.yml
  roles/libvirt_manager/tasks/start_vms.yml
  roles/libvirt_manager/templates/inventory.yml.j2
Labels: approved, lgtm, Ready For Review, ipv6

#2001 Add support for live documentation editing
  Makefile
  docs/source/Makefile
  docs/source/build-docs.sh
Labels: approved, lgtm, Ready For Review

#2007 Fix condition in tcib playbook when change list is empty
  ci/playbooks/tcib/tcib.yml
Labels: approved, lgtm, Ready For Review

#2003 Add optional hardware validations
  roles/reproducer/README.md
  roles/reproducer/tasks/validations.yml
Labels: approved, lgtm, Ready For Review

#2021 Enable some debugging if no DNS records
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
Labels: approved, lgtm

#2022 Use translated network name
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
Labels: bug, approved, lgtm, Ready For Review

#2027 Revert "Use translated network name"
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
Labels: approved, lgtm, Ready For Review

#2024 Small improvement in edpm logs collection
  roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm, Ready For Review

#2023 Hook : ironic - Use a static UUID for baremeal flavor
  hooks/playbooks/ironic_flavor.yml
Labels: approved, lgtm, Ready For Review, uni01alpha

#1914 Add support to net_map plugin for configuring Multus routes
  .gitignore
  Makefile
  plugins/module_utils/net_map/networking_definition.py
  plugins/module_utils/net_map/networking_env_definitions.py
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/net_map/test_networking_definitions_network.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-networks-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack.yml
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-networks-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only.yml
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-networks-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools.yml
Labels: approved, lgtm

#2028 Enable some debugging if no DNS records
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
Labels: approved, lgtm, Ready For Review

#1963 Enable to change OPENSTACK_RELEASE_VERSION to prepare for minor update
  roles/edpm_prepare/tasks/main.yml
  roles/set_openstack_containers/README.md
  roles/set_openstack_containers/defaults/main.yml
  roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm, minor update, Ready For Review

#2037 Sets install_yamls branches based on zuul.branch
  roles/install_yamls/molecule/default/converge.yml
  roles/install_yamls/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2015 Chasing down last import vs include in reproducer role
  roles/reproducer/tasks/crc_layout.yml
Labels: approved, lgtm

#2029 Add retries on task: Configure VMs type {{ vm }}
  roles/libvirt_manager/tasks/manage_vms.yml
Labels: approved, lgtm, Ready For Review, ipv6

#1997 Inject command aliases for faster debugging
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, Ready For Review

#2018 Add tripleo_controllers tripleo_computes for DPA ci zuul nodeset
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review

#2017 [test-operator] Introduce AnsibleTest CR
  docs/dictionary/en-custom.txt
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2039 Change dhcp-host filename pattern
  roles/dnsmasq/tasks/manage_host.yml
Labels: approved, lgtm, Ready For Review

#2033 [libvirt_manager] Do not add dummys to populated bridges
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/tasks/create_networks.yml
  roles/libvirt_manager/tasks/create_networks_dummy_interfaces.yml
Labels: approved, lgtm, Ready For Review

#2038 Ensure libvirt_molecule starts on clean env, each time
  roles/libvirt_manager/molecule/deploy_layout/cleanup.yml
  roles/libvirt_manager/molecule/spine_leaf/cleanup.yml
Labels: approved, lgtm

#2045 Pull ansible-utils from github
  galaxy.yml
  requirements.yml
Labels: approved, lgtm, Ready For Review

#1983 Add again DNS configuration for crc reproducer path
  roles/openshift_setup/tasks/restart_dns.yml
  roles/reproducer/tasks/configure_crc.yml
Labels: approved, lgtm, Ready For Review

#2035 Allow spine&leaf to not have ctlplane
  roles/libvirt_manager/molecule/spine_leaf/converge.yml
  roles/libvirt_manager/molecule/spine_leaf/verify.yml
  roles/libvirt_manager/tasks/generate_networking_data.yml
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
Labels: approved, lgtm, Ready For Review

#2044 [os_must_gather] Improve the way how o-m-g directory name is gathered
  roles/os_must_gather/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2043 Move final OCP wait closed to end of run
  roles/reproducer/tasks/libvirt_layout.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2009 Installing go straight from the source
  CONTRIBUTING.md
  ci/playbooks/pre-doc.yml
Labels: approved, lgtm, Ready For Review

#2032 Try to catch dnsmasq configuration errors
  ci/playbooks/multinode-customizations.yml
Labels: approved, lgtm, Ready For Review

#1918 [polarion] Merge xmls with junitparser
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2020 reproducer - cifmw_ci_nmstate_instance_config - ipv6
  roles/reproducer/tasks/prepare_networking.yml
Labels: approved, lgtm, Ready For Review, ipv6

#2040 Improve testing and documentation for run_hook role
  roles/run_hook/README.md
  roles/run_hook/molecule/default/converge.yml
  roles/run_hook/molecule/default/molecule.yml
  roles/run_hook/molecule/default/prepare.yml
  roles/run_hook/molecule/default/templates/dummy.yml.j2
  roles/run_hook/tasks/playbook.yml
Labels: approved, lgtm, Ready For Review

#2052 Allow to not deploy OpenShift provider
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/libvirt_layout.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2046 fix ansible test role
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/run-test-operator-job.yml
  roles/test_operator/vars/main.yml
Labels: approved, lgtm, va-2, Ready For Review

#2057 Add tempest related projects to branchless project
  roles/build_openstack_packages/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2050 Add additional listen address to nested CRC
  roles/rhol_crc/tasks/main.yml
  zuul.d/edpm.yaml
Labels: approved, lgtm, Ready For Review, 4.15 Migration

#2055 Set default value to DLRNAPI_PASSWORD
  roles/dlrn_promote/tasks/check_for_previous_promotions.yml
  roles/dlrn_promote/tasks/check_reported_jobs.yml
  roles/dlrn_promote/tasks/promote_hash.yml
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm, Ready For Review

#1852 Add steps to run minor version update
  playbooks/update.yml
  roles/repo_setup/tasks/configure.yml
  roles/update/README.md
  roles/update/defaults/main.yml
  roles/update/molecule/default/converge.yml
  roles/update/molecule/default/molecule.yml
  roles/update/molecule/default/prepare.yml
  roles/update/tasks/main.yml
Labels: approved, lgtm, minor update, Ready For Review

#1998 ci_gen_kustomize_values - IPv6
  roles/ci_gen_kustomize_values/defaults/main.yml
  roles/ci_gen_kustomize_values/molecule/default/converge.yml
  roles/ci_gen_kustomize_values/templates/common/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/common/edpm-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/common/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni01alpha/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni07eta/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/vars/main.yml
Labels: approved, lgtm, ipv6

#2054 Change chap algorithms
  roles/devscripts/templates/iscsi.j2
Labels: approved, lgtm, Ready For Review

#1942 [os_net_setup] Disable the use of `openstack-ansible-collection`
  roles/os_net_setup/README.md
  roles/os_net_setup/defaults/main.yml
  roles/os_net_setup/molecule/default/converge.yml
  roles/os_net_setup/molecule/default/molecule.yml
  roles/os_net_setup/molecule/default/prepare.yml
  roles/os_net_setup/tasks/main.yml
  roles/os_net_setup/tasks/subtask_net.yml
  roles/os_net_setup/templates/network_command.j2
  roles/os_net_setup/templates/subnet_command.j2
  roles/os_net_setup/templates/subnet_pool_command.j2
  zuul.d/molecule.yaml
Labels: approved, lgtm

#1865 Introduce cifmw_external_dns role to configure RGW with TLS
  docs/dictionary/en-custom.txt
  roles/cifmw_cephadm/README.md
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/configure_object.yml
  roles/cifmw_cephadm/tasks/pre.yml
  roles/cifmw_cephadm/tasks/rgw.yml
  roles/cifmw_cephadm/templates/ceph_rgw.yml.j2
  roles/cifmw_external_dns/README.md
  roles/cifmw_external_dns/defaults/main.yml
  roles/cifmw_external_dns/meta/main.yml
  roles/cifmw_external_dns/tasks/cert.yml
  roles/cifmw_external_dns/tasks/cleanup.yml
  roles/cifmw_external_dns/tasks/dns.yml
  roles/cifmw_external_dns/tasks/get_dns_forward_index.yml
  roles/cifmw_external_dns/tasks/main.yml
  roles/cifmw_external_dns/tasks/requirements.yml
  roles/cifmw_external_dns/tasks/test_dns.yml
  roles/cifmw_external_dns/templates/cert.yml.j2
  roles/cifmw_external_dns/templates/dns.yml.j2
Labels: approved, lgtm, Ready For Review

#2012 kustomization uni04delta-ipv6
  roles/ci_gen_kustomize_values/templates/uni04delta-ipv6/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review, ipv6

#2068 Improve network assertions in reproducer
  roles/reproducer/molecule/network_validations/vars/scenarios.yml
  roles/reproducer/tasks/network_assertions.yml
Labels: approved, lgtm, Ready For Review

#2064 Call rhos-release command only with rhos_release_args
  roles/reproducer/tasks/configure_computes.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/rhos_release.yml
Labels: approved, lgtm, Ready For Review

#2073 Ensure we don't copy useless venv/tmp
  roles/reproducer/molecule/crc_layout/converge.yml
Labels: approved, lgtm, Ready For Review

#2071 Add Tobiko Network Attachments
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2060 Change iscsid login timeout in computes
  hooks/playbooks/compute-iscsi-config.yml
Labels: approved, lgtm, Ready For Review

#2048 Fix download tool step of the reproducer role.
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2074 Fix parameter passing to install_yamls from update role.
  roles/update/tasks/main.yml
Labels: approved, lgtm, minor update, Ready For Review

#2067 Hook: Set properties on default volume type
  hooks/playbooks/cinder-default-volume-type-props.yml
Labels: approved, lgtm, Ready For Review

#2062 [must-gather] Gather resources in openshift-storage
  roles/os_must_gather/README.md
  roles/os_must_gather/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2076 Remove async from rhos-release command
  roles/reproducer/tasks/libvirt_layout.yml
  roles/reproducer/tasks/rhos_release.yml
Labels: approved, lgtm, Ready For Review

#2079 Add missing generated cifmw_external_dns job
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#2081 Allow changing CR name and print CR before applying
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: approved, lgtm, Ready For Review

#1989 Add repositoryDigestMirrors configuration to openshift_setup
  roles/openshift_setup/README.md
  roles/openshift_setup/defaults/main.yml
  roles/openshift_setup/molecule/default/converge.yml
  roles/openshift_setup/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2042 Correct and add DNS records for *all* networks
  roles/libvirt_manager/molecule/check_dns/cleanup.yml
  roles/libvirt_manager/molecule/check_dns/converge.yml
  roles/libvirt_manager/molecule/check_dns/molecule.yml
  roles/libvirt_manager/molecule/check_dns/prepare.yml
  roles/libvirt_manager/molecule/check_dns/vars/net-def.yml
  roles/libvirt_manager/molecule/check_dns/verify.yml
  roles/libvirt_manager/tasks/create_dns_records.yml
  roles/libvirt_manager/tasks/generate_networking_data.yml
  roles/libvirt_manager/tasks/manage_vms.yml
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
  roles/libvirt_manager/tasks/start_vms.yml
  roles/libvirt_manager/templates/inventory.yml.j2
  roles/reproducer/tasks/configure_controller.yml
  test-requirements.txt
Labels: approved, lgtm

#2083 Fix semversion hash join char
  scripts/setup_molecule
Labels: approved, lgtm, Ready For Review

#2077 [ci_lvms_storage] Fix wait conditions
  roles/ci_lvms_storage/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2085 [os_net_setup] Fix delete commands and restore is_vlan_transparent
  roles/os_net_setup/tasks/main.yml
  roles/os_net_setup/templates/network_command.j2
Labels: approved, lgtm, Ready For Review

#2092 OSPCIX-372 Fix race in ironic tls patch sequence
  hooks/playbooks/ironic_inject_tls.yml
Labels: approved, lgtm, Ready For Review

#2094 Add nodesets for CRC 2.39 (OCP 4.16)
  zuul.d/nodeset.yaml
Labels: approved, lgtm, Ready For Review, 4.16 Migration

#2084 Drop all references to change_message from zuul vars
  ci/playbooks/dump_zuul_data.yml
Labels: approved, lgtm, Ready For Review

#2089 Set LVMS for NFV DPDK SR-IOV VA
  scenarios/reproducers/va-nfv-ovs-dpdk-sriov.yml
Labels: approved, lgtm, Ready For Review

#2061 [test_operator][wntp] Add controller IP config to each tempest step
  roles/test_operator/tasks/tempest-tests.yml
Labels: approved, lgtm, Ready For Review

#2096 Update end to end and edpm* Zuul jobs to CRC 2.39 - OCP 4.16
  zuul.d/edpm.yaml
  zuul.d/edpm_multinode.yaml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm, Ready For Review, 4.16 Migration

#2098 Update podified, tempest and tofu zuul jobs to CRC 2.39 - OCP 4.16
  zuul.d/podified_multinode.yaml
  zuul.d/tempest_multinode.yaml
  zuul.d/tofu.yaml
Labels: approved, lgtm, Ready For Review, 4.16 Migration

#2097 Update Kuttl and Molecule zuul jobs to CRC 2.39 - OCP 4.16
  ci/config/molecule.yaml
  zuul.d/kuttl.yaml
  zuul.d/kuttl_multinode.yaml
  zuul.d/molecule-base.yaml
  zuul.d/molecule.yaml
Labels: approved, lgtm, Ready For Review, 4.16 Migration

#2095 Update adoption and base zuul jobs to CRC 2.39 - OCP 4.16
  zuul.d/adoption.yaml
  zuul.d/base.yaml
Labels: approved, lgtm, Ready For Review, 4.16 Migration

#2090 Exclude some files from /etc while getting the logs
  roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm, Ready For Review

#2106 Display debugging information in case of failure
  roles/networking_mapper/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2105 Add a hook at the very end of the deployment for custom payloads
  deploy-edpm.yml
  playbooks/98-pre-end.yml
Labels: approved, lgtm, Ready For Review

#2016 [test-operator] Add support for HorizonTest CR
  docs/dictionary/en-custom.txt
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/main.yml
  roles/test_operator/vars/main.yml
Labels: approved, lgtm, Ready For Review

#2109 Set dlrnapi.password value
  roles/dlrn_promote/tasks/check_for_previous_promotions.yml
  roles/dlrn_promote/tasks/check_reported_jobs.yml
  roles/dlrn_promote/tasks/promote_hash.yml
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm, Ready For Review

#1875 [networking_mapper] Add hostname to the MAC seed
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/test_files/network-definition-valid-all-tools-no-group-templates-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-partial-map-out.json
Labels: approved, lgtm, Ready For Review

#2069 Setup minimum environment to run update on architecture.
  playbooks/update.yml
  roles/set_openstack_containers/tasks/main.yml
Labels: approved, lgtm, minor update, Ready For Review

#2112 nit: Correct molecule generated content
  ci/templates/molecule.yaml.j2
  zuul.d/molecule.yaml
Labels: approved, lgtm, Ready For Review

#2110 Update the tofu molecule to make it pass
  roles/tofu/molecule/default/converge.yml
  roles/tofu/molecule/default/prepare.yml
  roles/tofu/molecule/files/main.tf
  zuul.d/tofu.yaml
Labels: approved, lgtm, Ready For Review

#2088 Bump openshift version to 4.16.0
  roles/devscripts/vars/main.yml
Labels: approved, lgtm, Ready For Review, 4.16 Migration

#2093 Add cifmw olm subscription channel var
  roles/ci_gen_kustomize_values/templates/common/olm-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2107 Add some more debugging to the network_assertion failures
  roles/reproducer/tasks/network_assertions.yml
Labels: approved, lgtm, Ready For Review

#2108 Add debugging pattern "best practices" to the contributing doc
  CONTRIBUTING.md
Labels: approved, lgtm, Ready For Review

#2111 Fix README of test_operator role
  roles/test_operator/README.md
Labels: approved, lgtm, Ready For Review

#2118 Skip building the horizontest container
  roles/build_containers/defaults/main.yml
  roles/build_containers/molecule/default/converge.yml
Labels: approved, lgtm, Ready For Review

#2116 [test-operator] Expose extraConfigmapsMounts param
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2087 Allow ignoring test failures
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2030 Support DCN layout
  roles/libvirt_manager/molecule/deploy_layout/prepare.yml
  roles/libvirt_manager/molecule/generate_network_data/cleanup.yml
  roles/libvirt_manager/molecule/generate_network_data/converge.yml
  roles/libvirt_manager/molecule/generate_network_data/molecule.yml
  roles/libvirt_manager/molecule/generate_network_data/prepare.yml
  roles/libvirt_manager/molecule/generate_network_data/tasks/test.yml
  roles/libvirt_manager/molecule/generate_network_data/vars/input.yml
  roles/libvirt_manager/molecule/generate_network_data/vars/scenarios.yml
  roles/libvirt_manager/tasks/create_dns_records.yml
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
Labels: approved, lgtm, Ready For Review

#2129 Collect os-must-gather logs from openshift-marketplace namespace
  roles/os_must_gather/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2132 Add the `when` case for import vs include doc
  docs/dictionary/en-custom.txt
  docs/source/development/01_guidelines.md
Labels: approved, lgtm, Ready For Review

#2121 Removed custom patch since the upstream pr has been merged
  roles/devscripts/files/proxy.patch
  roles/devscripts/tasks/135_patch_src.yml
Labels: approved, lgtm, Ready For Review

#2134 Correct ansible-lint issues
  .pre-commit-config.yaml
  meta/runtime.yml
  roles/libvirt_manager/molecule/check_dns/verify.yml
  roles/libvirt_manager/molecule/generate_network_data/tasks/test.yml
Labels: approved, lgtm, Ready For Review

#2131 Unskip building horizontest container
  roles/build_containers/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2133 [devscripts] Added when clause in the `async_status` task
  roles/devscripts/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2136 Add skip subscription manager patch to devscripts role
  roles/devscripts/files/01_subs_check.patch
  roles/devscripts/tasks/135_patch_src.yml
Labels: approved, lgtm, Ready For Review

#2130 [openshift_setup] Metal3 watch all NSs
  roles/openshift_setup/README.md
  roles/openshift_setup/defaults/main.yml
  roles/openshift_setup/tasks/main.yml
  roles/openshift_setup/tasks/metal3_config.yml
  scenarios/reproducers/va-nfv-ovs-dpdk-sriov.yml
  scenarios/reproducers/va-nfv-ovs-sriov.yml
Labels: approved, lgtm, Ready For Review

#2080 Make ceph.yml playbook work with IPv6
  playbooks/ceph.yml
  roles/cifmw_ceph_spec/templates/initial_ceph.conf.j2
Labels: approved, lgtm, Ready For Review, ipv6

#2138 Enable to increase timeout for steps in openstack_update_run target
  roles/update/README.md
  roles/update/defaults/main.yml
  roles/update/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2122 Do not edit sensitive data set in machineconfig
  ci/playbooks/collect-logs.yml
  ci/playbooks/tasks/set_crc_insecure_registry.yml
  roles/registry_deploy/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2139 Revert "Add skip subscription manager patch to devscripts role"
  roles/devscripts/files/01_subs_check.patch
  roles/devscripts/tasks/135_patch_src.yml
Labels: approved, lgtm, Ready For Review

#2142 Correct generated OCP domain
  roles/reproducer/tasks/prepare_networking.yml
Labels: approved, lgtm, Ready For Review, unique-fqdn

#2091 Reparent adoption github-check job for new job naming scheme
  zuul.d/adoption.yaml
  zuul.d/project-templates.yaml
Labels: approved, lgtm, Ready For Review

#2145 Use rdo-jobs mirror-info-fork role to use rdo package mirror
  ci/playbooks/molecule-prepare.yml
  zuul.d/molecule-base.yaml
Labels: approved, lgtm, Ready For Review

#2146 Ensure we're talking with boolean
  playbooks/ceph.yml
  roles/cifmw_cephadm/tasks/cephfs.yml
  roles/cifmw_cephadm/tasks/rgw.yml
Labels: approved, lgtm, ceph, Ready For Review, unique-fqdn

#2144 Increase timeout to 2 hours for cifmw-base-multinode-kuttl
  zuul.d/kuttl_multinode.yaml
Labels: approved, lgtm, Ready For Review

#2141 Use ansible.utils.ipwrap when configuring DNS forward
  roles/cifmw_external_dns/tasks/dns.yml
Labels: approved, lgtm, Ready For Review

#2137 Allow to toggle no_log for debugging purpose
  roles/cifmw_external_dns/tasks/cert.yml
Labels: approved, lgtm, Ready For Review

#2135 Add check for NodeSet status
  roles/validations/defaults/main.yml
  roles/validations/tasks/edpm/hotfix.yml
  roles/validations/tasks/edpm/hugepages_and_reboot.yml
Labels: approved, lgtm, Ready For Review

#2154 Update adoption-standalone-*-provider irrelevant-files list
  zuul.d/adoption.yaml
Labels: approved, lgtm, Ready For Review

#2117 Improve DHCP configuration in dnsmasq
  ci/config/molecule.yaml
  roles/dnsmasq/README.md
  roles/dnsmasq/molecule/default/converge.yml
  roles/dnsmasq/tasks/_check_net_status.yml
  roles/dnsmasq/tasks/manage_host.yml
  roles/libvirt_manager/molecule/generate_network_data/tasks/test.yml
  roles/libvirt_manager/tasks/create_dns_records.yml
  roles/libvirt_manager/tasks/reserve_dnsmasq_ips.yml
  roles/reproducer/tasks/ocp_layout.yml
  zuul.d/molecule.yaml
Labels: approved, lgtm, Ready For Review

#2157 Add missing tags to tasks of importance
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2149 [ci_nmstate] Removed `generateName` property from `OperatorGroup` template
  roles/ci_nmstate/defaults/main.yml
  roles/ci_nmstate/tasks/nmstate_k8s_install.yml
Labels: approved, lgtm, Ready For Review

#2156 Skip provider/edpm jobs on validations role
  zuul.d/base.yaml
Labels: approved, lgtm, Ready For Review

#2158 Expose found versions and location for crc binary
  roles/rhol_crc/tasks/get_versions.yml
  roles/rhol_crc/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2127 Add option to deploy Ceph with encryption enabled
  docs/dictionary/en-custom.txt
  roles/cifmw_ceph_spec/README.md
  roles/cifmw_ceph_spec/defaults/main.yml
  roles/cifmw_ceph_spec/templates/ceph_spec.yml.j2
  roles/cifmw_ceph_spec/templates/initial_ceph.conf.j2
Labels: approved, lgtm, Ready For Review

#2162 Bump all adoption base job timeout to 14400
  zuul.d/adoption.yaml
Labels: approved, lgtm, Ready For Review

#2163 Remove duplicated job
  ci/templates/projects.yaml
  zuul.d/end-to-end.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm, Ready For Review

#2160 [test-operator][horizon] Expose storageClass parameter
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2114 Use dedicated edpm_kernel_hugepages var
  roles/validations/tasks/edpm/hugepages_and_reboot.yml
Labels: approved, lgtm, Ready For Review

#2153 Use latest version of workload_launch for update.
  roles/update/templates/workload_launch.sh.j2
Labels: approved, lgtm, minor update, Ready For Review

#2115 Copy gating repo to /etc/yum.repos.d to install tcib from it
  ci/playbooks/meta_content_provider/meta_content_provider.yml
  roles/repo_setup/tasks/populate_gating_repo.yml
Labels: approved, lgtm, Ready For Review

#2170 Use cifmw_dlrn_report_promote_source to set proper dlrn reporting target
  roles/dlrn_report/README.md
  roles/dlrn_report/defaults/main.yml
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm, Ready For Review

#2165 Remove duplicated dedicated network template
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2166 Switch useless omit to a proper if condition
  roles/ci_gen_kustomize_values/templates/common/network-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2168 [test-operator] Fix volume mounting
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: approved, lgtm, Ready For Review

#2171 [rhol_crc] Removed `crc delete -f` command from the cleanup phase
  roles/rhol_crc/tasks/cleanup.yml
Labels: approved, lgtm, Ready For Review

#2172 Update comment redundant data plane adoption 'old' job names
  zuul.d/adoption.yaml
Labels: approved, lgtm, Ready For Review

#2174 Add FAQ about how to reauthenticate
  docs/dictionary/en-custom.txt
  docs/source/quickstart/99_FAQ.md
Labels: approved, lgtm, Ready For Review

#2177 [test-operator][horizon] Fix Horizon CR name
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2150 Add new cifmw-adoption-base-multinode-networker for adoption CI
  zuul.d/adoption.yaml
Labels: approved, lgtm, Ready For Review

#2183 [hooks] Fixed `edpm_network_config_template` variable in `fetch_compute_facts.yml` playbook
  hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm, Ready For Review
