Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-03, with the labels that each got.

#1206 Precisely target values.yaml file for user kustomization
  roles/kustomize_deploy/tasks/execute_step.yml
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved, lgtm

#1200 Support non-default OCP cluster name
  roles/reproducer/tasks/devscripts_post.yml
Labels: approved, lgtm

#1205 Fix iSCSI variables
  roles/devscripts/tasks/137_custom_install.yml
Labels: approved, lgtm, ok-to-test

#1209 Add katarimanojk as a reviewer
  OWNERS
Labels: approved, lgtm

#1152 Allow zuul reproducer to pull multiple depends-on
  roles/reproducer/tasks/push_code.yml
Labels: approved, lgtm

#1214 Move log_host_url to a proper var
  roles/dlrn_report/README.md
  roles/dlrn_report/defaults/main.yml
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, lgtm

#1208 Reduce ceph resources to support single node jobs
  playbooks/ceph.yml
  roles/cifmw_cephadm/templates/ceph_rgw.yml.j2
Labels: approved, lgtm, ok-to-test

#1220 Make multinode-autohold.yml user other Ansible targets
  ci/playbooks/multinode-autohold.yml
Labels: approved, lgtm

#1216 Add cifmw_ceph_daemons_layout to VA1
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved, lgtm

#1197 Complete the removal of cloud specific labels
  docs/source/cookbooks/zuul-job-nodeset.md
  zuul.d/base.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#1199 Ensure libvirt_manager layout contains correct information
  roles/devscripts/tasks/300_post.yml
  roles/devscripts/tasks/320_prepare_layout.yml
Labels: approved, lgtm

#1231 Try all image slot
  roles/set_openstack_containers/templates/update_env_vars.sh.j2
Labels: approved, lgtm

#1225 Add flag to skip fetching code in the reproducer
  roles/reproducer/README.md
  roles/reproducer/defaults/main.yml
  roles/reproducer/tasks/push_code.yml
Labels: approved, lgtm

#1228 Avoid incorrect association of OpenShift VMs and their overlay disk
  roles/devscripts/tasks/310_prepare_overlay.yml
  roles/devscripts/tasks/320_prepare_layout.yml
  roles/libvirt_manager/tasks/create_vms.yml
Labels: approved, lgtm

#1196 Minor refactor in edpm_prepare and new hook for ceph scenarios
  hooks/playbooks/control_plane_ceph_backends.yml
  hooks/playbooks/control_plane_kustomize_deploy.yml
  roles/edpm_prepare/README.md
  roles/edpm_prepare/defaults/main.yml
  roles/edpm_prepare/tasks/kustomize_and_deploy.yml
  roles/edpm_prepare/tasks/main.yml
  roles/hci_prepare/tasks/phase2.yml
  scenarios/centos-9/hci_ceph_backends.yml
Labels: approved, lgtm

#1244 Retry SSH command execution after the VM is created.
  roles/libvirt_manager/tasks/start_manage_vms.yml
Labels: approved, lgtm

#1198 Remove unused labels from nodesets.yaml
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#1245 [repo_setup] Update generated repos with nodepool mirror repos
  roles/repo_setup/tasks/ci_mirror.yml
  roles/repo_setup/tasks/main.yml
Labels: approved, lgtm

#1246 [repo_setup] Sync generated repos to yum.repos.d directory
  roles/repo_setup/tasks/main.yml
  roles/repo_setup/tasks/sync_repos.yml
Labels: approved, lgtm

#1247 [test-operator] Configure when test-operator asserts results
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/main.yml
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: approved, lgtm

#1215 Copy yum.repos.d directory to logs
  roles/artifacts/tasks/environment.yml
Labels: approved, lgtm

#1249 Sync repos only non yum.repos.d cifmw_repo_setup_output directory
  roles/repo_setup/tasks/sync_repos.yml
Labels: approved, lgtm

#1235 [Tobiko] Introduce Tobiko Workflows
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/main.yml
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: approved, lgtm

#1204 Upgrade how hooks are defined
  docs/source/usage/01_usage.md
  playbooks/02-infra.yml
  playbooks/03-build-packages.yml
  playbooks/04-build-containers.yml
  playbooks/05-build-operators.yml
  playbooks/06-deploy-architecture.yml
  playbooks/06-deploy-edpm.yml
  playbooks/07-admin-setup.yml
  playbooks/08-run-tests.yml
  playbooks/hooks.yml
  playbooks/update.yml
  roles/kustomize_deploy/tasks/execute_step.yml
  roles/run_hook/README.md
  roles/run_hook/molecule/default/converge.yml
  roles/run_hook/molecule/default/molecule.yml
  roles/run_hook/molecule/default/prepare.yml
  roles/run_hook/molecule/default/resources/vars.yml
  roles/run_hook/molecule/default/templates/dummy.yml.j2
  roles/run_hook/tasks/crd.yml
  roles/run_hook/tasks/main.yml
Labels: approved, lgtm

#1254 Keep epel repo dependency in rescue mode for openstack_buid_packages role
  roles/build_openstack_packages/tasks/install_dlrn.yml
  roles/ci_setup/tasks/epel.yml
  zuul.d/tcib.yaml
Labels: approved, lgtm

#1255 Rework include/import usage in reproducer role
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/main.yml
  scenarios/reproducers/3-nodes.yml
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved, lgtm

#1261 [ci_setup] Fix error pertaining to GPG signature keys for EPEL repositories.
  roles/ci_setup/tasks/epel.yml
Labels: approved, lgtm

#1213 Shutdown OpenShift cluster gracefully.
  roles/openshift_adm/README.md
  roles/openshift_adm/defaults/main.yml
  roles/openshift_adm/files/regenerate-certificate.yml
  roles/openshift_adm/meta/main.yml
  roles/openshift_adm/tasks/api_cert.yml
  roles/openshift_adm/tasks/main.yml
  roles/openshift_adm/tasks/shutdown.yml
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: approved, lgtm

#1218 net-mapper: is_trunk_parent, trunk_parent, routers
  plugins/module_utils/net_map/exceptions.py
  plugins/module_utils/net_map/networking_definition.py
  plugins/module_utils/net_map/networking_env_definitions.py
  plugins/module_utils/net_map/networking_mapper.py
  scripts/run_ansible_test
  tests/unit/module_utils/net_map/test_networking_definitions_group_template.py
  tests/unit/module_utils/net_map/test_networking_definitions_instance.py
  tests/unit/module_utils/net_map/test_networking_definitions_network.py
  tests/unit/module_utils/net_map/test_networking_mapper.py
  tests/unit/module_utils/test_files/network-definition-valid-all-tools-no-group-templates-out.json
  tests/unit/module_utils/test_files/network-definition-valid-all-tools-no-group-templates.yml
  tests/unit/module_utils/test_files/network-definition-valid-router-template-out.json
  tests/unit/module_utils/test_files/network-definition-valid-router-template.yml
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools.yml
  tests/unit/module_utils/test_files/networking-definition-valid-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-network-template.yml
  tests/unit/module_utils/test_files/networking-definition-valid-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid.yml
Labels: approved, lgtm

#1263 Copy ansible logs from user's home dir to artifacts log dir
  roles/artifacts/tasks/ansible_logs.yml
  roles/artifacts/tasks/main.yml
Labels: approved, lgtm

#1221 [devscripts] add cert check and graceful shutdown
  roles/devscripts/tasks/110_check_ocp.yml
  roles/devscripts/tasks/111_verify_cluster.yml
  roles/devscripts/tasks/112_verify_golden_image.yml
  roles/devscripts/tasks/310_prepare_overlay.yml
  roles/devscripts/tasks/330_wait_ocp.yml
  roles/devscripts/tasks/cleanup.yml
  roles/reproducer/tasks/devscripts_post.yml
Labels: approved, lgtm

#1243 [libvirt_manager] Add support for setting static address
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/templates/static_ip.j2
Labels: approved, lgtm

#1252 Generate a script for deploy-edpm.yml run
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1248 Adding the capability of customize values.yaml for OLM resources
  roles/ci_gen_kustomize_values/templates/common/olm/values.yaml.j2
  roles/kustomize_deploy/tasks/install_operators.yml
Labels: approved, lgtm

#1268 Use --force argument with ansible-galaxy install
  roles/reproducer/tasks/push_code.yml
  scripts/run_ansible_test
  scripts/setup_molecule
Labels: approved, lgtm

#1272 [openshift_adm] Support customizing the retry count for OpenShiftapi and login
  roles/openshift_adm/README.md
  roles/openshift_adm/defaults/main.yml
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: approved, lgtm

#1270 Rename "validated-architecture-1" to "va-hci"
  roles/kustomize_deploy/README.md
  scenarios/reproducers/va-hci.yml
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved, lgtm

#1212 Add storage_mgmt network to adoption job
  zuul.d/adoption.yaml
Labels: approved, lgtm

#1257 [ci_script] Print log location to allow easy following of it
  plugins/action/ci_script.py
  tests/integration/targets/script/tasks/main.yml
Labels: approved, lgtm

#1269 Allow single hooks to be a list
  roles/run_hook/tasks/main.yml
Labels: approved, lgtm

#1253 [copy-quay] Don't push tag if hash already exists on dest namespace
  roles/copy_container/files/copy-quay/README.rst
  roles/copy_container/files/copy-quay/copy.go
  roles/copy_container/files/copy-quay/go.mod
  roles/copy_container/files/copy-quay/go.sum
  roles/copy_container/files/copy-quay/quayapi.go
  roles/copy_container/files/copy-quay/tag.go
  roles/copy_container/files/copy-quay/utils.go
Labels: approved, lgtm, ok-to-test

#1260 add log collection for systemd services on edpm nodes
  roles/artifacts/tasks/edpm.yml
Labels: approved, lgtm

#1273 Update edpm_deploy_baremetal README
  roles/edpm_deploy_baremetal/README.md
Labels: approved, lgtm

#1275 Increasing the default number attempts to have a successful login and API connectivity check.
  roles/openshift_adm/README.md
  roles/openshift_adm/defaults/main.yml
Labels: approved, lgtm

#1262 Allow users to inject their own custom hooks
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm

#1264 Enable "common" templates in ci_gen_kustomize_values
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
  roles/ci_gen_kustomize_values/templates/common/network-values/values.yaml.j2
Labels: approved, lgtm

#1223 Set cifmw_networking_definition for ci-bootstap staging
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#1279 [ceph] Ensure 1st monitor net facts are updated
  playbooks/ceph.yml
Labels: approved, lgtm

#1267 [Test-operator] Fix detection of failures
  roles/test_operator/tasks/main.yml
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: approved, lgtm

#1276 Add new top-level parameter to skip stage
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: approved, lgtm

#1280 Fix reproducer directory creation
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1119 Configure Ceph Object Store to use external Ceph rgw
  roles/cifmw_cephadm/tasks/configure_object.yml
  roles/cifmw_cephadm/tasks/post.yml
Labels: approved, lgtm, ok-to-test

#1238 Refactor reproducer push code to reuse existing code
  roles/reproducer/README.md
  roles/reproducer/tasks/push_code.yml
Labels: approved, lgtm

#1285 Ensure we install the dependencies soon enough
  docs/source/build-docs.sh
Labels: approved, lgtm

#1277 Correct generated scripts from reproducer role
  roles/reproducer/tasks/configure_architecture.yml
  roles/reproducer/tasks/crc_layout.yml
  roles/reproducer/tasks/devscripts_post.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1286 Ensure we properly detect if we want net prefix
  roles/libvirt_manager/tasks/net_to_vms.yml
Labels: approved, lgtm

#1283 [ceph] Gather network facts for all computes
  playbooks/ceph.yml
Labels: approved, lgtm

#1287 Pass openstack namespace to configure_object oc command
  roles/cifmw_cephadm/README.md
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/configure_object.yml
Labels: approved, lgtm

#1288 Tag sha256 together with current-podified
  roles/copy_container/files/copy-quay/tag.go
Labels: approved, lgtm

#1224 Generate values based on the original content
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
  roles/ci_gen_kustomize_values/templates/hci/edpm-values/values.yaml.j2
Labels: approved, lgtm

#1284 Add new role: virtualbmc
  docs/dictionary/en-custom.txt
  roles/virtualbmc/README.md
  roles/virtualbmc/defaults/main.yml
  roles/virtualbmc/meta/main.yml
  roles/virtualbmc/molecule/default/cleanup.yml
  roles/virtualbmc/molecule/default/converge.yml
  roles/virtualbmc/molecule/default/molecule.yml
  roles/virtualbmc/molecule/default/prepare.yml
  roles/virtualbmc/tasks/cleanup.yml
  roles/virtualbmc/tasks/list_hosts.yml
  roles/virtualbmc/tasks/main.yml
  roles/virtualbmc/tasks/manage_host.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1291 Add default values for ceph playbook in adoption
  playbooks/ceph.yml
Labels: approved, lgtm

#1226 Add more ceph OSDs to support single node jobs
  playbooks/ceph.yml
  roles/cifmw_block_device/tasks/main.yml
  roles/cifmw_ceph_spec/defaults/main.yml
  roles/cifmw_ceph_spec/molecule/default/converge.yml
  roles/cifmw_ceph_spec/molecule/default/tasks/verify_spec.yml
  roles/cifmw_ceph_spec/tasks/main.yml
  roles/cifmw_ceph_spec/templates/ceph_spec.yml.j2
Labels: approved, lgtm

#1292 Ensure we consume the full Zuul inventory
  ci/playbooks/pre-ci-bootstrap.yml
Labels: approved, lgtm

#1274 Deprecate cifmw_reproducer_internal_ca parameter
  roles/install_ca/tasks/main.yml
  roles/reproducer/tasks/configure_computes.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/tasks/rhos_release.yml
Labels: approved, lgtm

#1298 Use test operator for running tempest
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1301 Ensure we keep track of generated content
  roles/ci_gen_kustomize_values/tasks/generate_snippets.yml
  roles/ci_gen_kustomize_values/tasks/generate_values.yml
Labels: approved, lgtm

#1307 Exclude bots PR from checklist workflow
  .github/workflows/require-checklist.yaml
Labels: approved

#1309 [Test-operator] Change default image
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm

#1312 Use a bigger flavor for standalone node in adoption
  zuul.d/nodeset.yaml
Labels: approved, lgtm

#1310 Try ssh command and freshly booting vms
  roles/libvirt_manager/tasks/start_manage_vms.yml
Labels: approved, lgtm

#1311 Donot generate nova migration key if exists
  playbooks/06-deploy-architecture.yml
Labels: approved, lgtm

#1282 Map `nic2` to correct interface via MAC address
  roles/ci_gen_kustomize_values/templates/hci/edpm-values/values.yaml.j2
Labels: approved, lgtm

#1325 increase cifw_edpm_deploy_timeout to 60mins
  roles/edpm_deploy/defaults/main.yml
Labels: approved, lgtm

#1314 Split GlanceAPI in the control plane CR when Ceph is applied
  hooks/playbooks/control_plane_ceph_backends.yml
Labels: approved, lgtm

#1290 Integrate virtualbmc in libvirt_manager
  roles/devscripts/tasks/cleanup.yml
  roles/libvirt_manager/molecule/deploy_layout/converge.yml
  roles/libvirt_manager/tasks/clean_layout.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/main.yml
  roles/reproducer/tasks/main.yml
  roles/virtualbmc/tasks/cleanup.yml
  roles/virtualbmc/tasks/main.yml
Labels: approved, lgtm

#1315 Rebased: [must-gather]Collect SOS reports from EDPM nodes
  roles/os_must_gather/tasks/main.yml
Labels: approved, lgtm

#1308 Add more tags to deploy architecture playbook
  playbooks/02-infra.yml
  playbooks/06-deploy-architecture.yml
Labels: approved, lgtm

#1331 Revert "Try ssh command and freshly booting vms"
  roles/libvirt_manager/tasks/start_manage_vms.yml
Labels: approved, lgtm

#1334 Allow to set a specific port for VBMC daemon
  roles/libvirt_manager/tasks/create_vms.yml
  roles/virtualbmc/README.md
  roles/virtualbmc/defaults/main.yml
  roles/virtualbmc/tasks/cleanup.yml
  roles/virtualbmc/tasks/main.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1343 Perform PV creation/delation through ansible
  roles/ci_local_storage/README.md
  roles/ci_local_storage/defaults/main.yml
  roles/ci_local_storage/molecule/default/converge.yml
  roles/ci_local_storage/molecule/default/prepare.yml
  roles/ci_local_storage/tasks/cleanup.yml
  roles/ci_local_storage/tasks/fetch_names.yml
  roles/ci_local_storage/tasks/main.yml
  roles/ci_local_storage/tasks/worker_node_dirs.yml
  roles/ci_local_storage/templates/storage.yaml.j2
Labels: approved, lgtm

#1349 Disable disable_os_marketplace hook
  hooks/playbooks/README.md
  hooks/playbooks/disable_os_marketplace.yml
  scenarios/centos-9/ci.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
  scenarios/centos-9/ironic.yml
  scenarios/centos-9/podified_common.yml
Labels: approved, lgtm

#1346 Ensure we know all the hosts beforehand
  ci/playbooks/edpm_baremetal_deployment/run.yml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#1351 Ensure MAC addresses are quoted in the generated CI snippet
  roles/ci_gen_kustomize_values/molecule/default/converge.yml
  roles/ci_gen_kustomize_values/molecule/default/files/networking-environment-definition.yml
  roles/ci_gen_kustomize_values/templates/hci/edpm-values/values.yaml.j2
Labels: approved, lgtm

#1354 Avoid repetition, remove useless task in nova_migration key
  playbooks/06-deploy-architecture.yml
Labels: approved, lgtm

#1353 Updating the kuttl jobs to run for the operators that are passing currently
  zuul.d/kuttl.yaml
  zuul.d/kuttl_multinode.yaml
Labels: approved, lgtm

#1335 Add UEFI support for the virtual machines
  docs/source/usage/01_usage.md
  roles/libvirt_manager/templates/domain.xml.j2
  scenarios/reproducers/3-nodes.yml
  scenarios/reproducers/external-ceph.yml
  scenarios/reproducers/va-hci.yml
Labels: approved, lgtm

#1340 Ensure script properly reports failure in reproducer
  roles/reproducer/tasks/configure_architecture.yml
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1177 Enable checkout from openstack_ref flag in install_yamls
  roles/edpm_deploy/tasks/main.yml
  roles/edpm_deploy_baremetal/tasks/main.yml
  roles/edpm_prepare/tasks/main.yml
  roles/install_yamls/README.md
  roles/install_yamls/defaults/main.yml
  roles/install_yamls/molecule/default/converge.yml
  roles/install_yamls/tasks/main.yml
  roles/install_yamls/tasks/zuul_set_operators_repo.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#1338 Use nodeset_networks ansible var
  hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#1142 Integrate tcib in reproducer
  ci/playbooks/tcib/tcib.yml
  roles/reproducer/tasks/ci_data.yml
  roles/reproducer/tasks/ci_job.yml
  roles/reproducer/templates/content-provider.yml.j2
  roles/reproducer/templates/play.yml.j2
Labels: approved, lgtm

#1358 Make sure podman is installed.
  roles/virtualbmc/tasks/main.yml
Labels: approved, lgtm

#1250 [polarion] Include last jump changes
  roles/polarion/README.md
  roles/polarion/defaults/main.yml
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, ok-to-test

#1344 Switch kuttl to ci_local_storage
  ci/playbooks/kuttl/run-kuttl-tests.yml
Labels: approved, lgtm

#1357 Support end to end run for deployed topologies.
  docs/source/usage/01_usage.md
  playbooks/06-deploy-architecture.yml
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#1365 Fix example for cifmw_reproducer_repositories config
  roles/reproducer/README.md
Labels: approved, lgtm, ok-to-test

#1336 Fix cifmw_block_device cleanup
  roles/cifmw_block_device/tasks/cleanup.yml
Labels: approved, lgtm

#1359 Allow to retry "Ensure the nodes are in ready state."
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: approved, lgtm

#1367 Fix a syntax error in reproducer configure_controller.yml
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm
