Repository openstack-k8s-operators/ci-framework, pull requests merged in 2024-01, with the labels that each got.

#989 [networking_mapping] Add the instances full mapping logic
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/net_map/test_networking_mapper.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-full-map-out.json
  tests/unit/module_utils/test_utils/net_map_stub_data.py
Labels: approved, lgtm

#991 [networking_mapping] Basic corner cases/validation UTs
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/net_map/test_networking_mapper.py
Labels: approved, lgtm

#993 [networking_mapping] Fix missing interface name
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-full-map-out.json
Labels: approved, lgtm

#994 Add back BM nodeset update packages in bootstrap
  roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#995 Refactor: Simplify Ansible tasks for directory creation and variable inclusion
  hooks/playbooks/control_plane_ceph_backends.yml
  hooks/playbooks/control_plane_ironic.yml
Labels: lgtm

#996 Add some assertions to validate generated facts
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/start_manage_vms.yml
Labels: approved, lgtm

#1000 Fix used of cifmw_control_plane_ceph_backend_include_vars
  scenarios/centos-9/ceph_backends.yml
Labels: approved, lgtm

#997 Enable better logging for rhol_crc
  roles/rhol_crc/tasks/configuration.yml
  roles/rhol_crc/tasks/main.yml
Labels: approved, lgtm

#1003 Move must-gather folder to a predictable name
  roles/os_must_gather/tasks/main.yml
Labels: approved, lgtm

#1001 Be smarter with existing network names
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/libvirt_manager/tasks/create_networks.yml
  roles/libvirt_manager/tasks/create_vms.yml
  roles/libvirt_manager/vars/main.yml
Labels: approved, lgtm

#1004 Remove unused adoption job
  zuul.d/adoption.yaml
Labels: approved, lgtm

#1007 Correct/update file location for generated content
  roles/libvirt_manager/tasks/deploy_layout.yml
  roles/libvirt_manager/tasks/reserve_ip.yml
  roles/reproducer/molecule/crc_layout/converge.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/templates/play.yml.j2
Labels: approved, lgtm

#1011 [networking_mapping] Fix group nets duplication check and test definition
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/net_map/test_networking_definitions_all.py
  tests/unit/module_utils/net_map/test_networking_mapper.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only.yml
Labels: approved, lgtm

#1010 [networking_mapping] Make hostvars optional for partial maps
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/net_map/test_networking_mapper.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-reduced-map-out.json
  tests/unit/module_utils/test_utils/net_map_stub_data.py
Labels: approved, lgtm

#1009 Explain how to consume multiple hypervisors
  docs/dictionary/en-custom.txt
  docs/source/files/bootstrap-hypervisor.yml
  docs/source/files/bootstrap-vxlan.yml
  docs/source/files/multinode-params.yml
  docs/source/quickstart/02_prepare_env.md
  docs/source/quickstart/03_deploy_infra.md
  docs/source/reproducers/02-layout.md
Labels: approved, lgtm

#924 Add extra skip tests to nova-operator
  roles/tempest/files/list_skipped.yml
Labels: approved, lgtm

#1014 Improve cert manager cleanup playbook
  roles/cert_manager/README.md
  roles/cert_manager/defaults/main.yml
  roles/cert_manager/tasks/cleanup.yml
Labels: approved, lgtm

#1016 Ensure we deploy the ssh configuration on controller-0
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm

#1015 Prepare for removal of duplicated adoption base jobs
  zuul.d/adoption.yaml
Labels: approved, lgtm

#1017 Tweak adoption nodeset with larger crc node
  zuul.d/adoption.yaml
Labels: approved, lgtm

#992 [networking_mapping] Add the Ansible wrapper role
  ci/config/molecule.yaml
  plugins/action/ci_net_map.py
  plugins/module_utils/net_map/exceptions.py
  plugins/module_utils/net_map/networking_mapper.py
  roles/networking_mapper/README.md
  roles/networking_mapper/defaults/main.yml
  roles/networking_mapper/meta/main.yml
  roles/networking_mapper/molecule/default/converge.yml
  roles/networking_mapper/molecule/default/molecule.yml
  roles/networking_mapper/molecule/default/prepare.yml
  roles/networking_mapper/tasks/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1002 Add Molecule job for copy-containers
  roles/copy_container/molecule/default/converge.yml
  roles/copy_container/molecule/default/molecule.yml
  roles/copy_container/molecule/default/prepare.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#950 Support TLS for RGW
  playbooks/ceph.yml
  roles/cifmw_cephadm/README.md
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/rgw.yml
  roles/cifmw_cephadm/templates/ceph_rgw.yml.j2
Labels: approved, lgtm, ok-to-test

#1019 Simplify adoption jobs layout in ci-framework
  zuul.d/adoption.yaml
  zuul.d/project-templates.yaml
Labels: approved, lgtm

#1022 [reproducer] disable static ip for ocpbm
  roles/libvirt_manager/vars/main.yml
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved, lgtm

#983 [devscripts] Enhance cleanup for CI token errors
  roles/devscripts/tasks/cleanup.yml
Labels: approved, lgtm

#1013 Tobiko role
  deploy-edpm.yml
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  playbooks/08-run-tests.yml
  roles/tempest/defaults/main.yml
  roles/tempest/tasks/configure-tempest.yml
  roles/tempest/tasks/create-clouds-file.yml
  roles/tempest/tasks/main.yml
  roles/tobiko/README.md
  roles/tobiko/defaults/main.yml
  roles/tobiko/files/.gitkeep
  roles/tobiko/meta/main.yml
  roles/tobiko/molecule/default/converge.yml
  roles/tobiko/molecule/default/molecule.yml
  roles/tobiko/molecule/default/prepare.yml
  roles/tobiko/tasks/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1026 3 nodes OCP networking definition
  scenarios/reproducers/3-ocp-networking-definition.yml
Labels: approved, lgtm

#1031 Avoid useless computations
  roles/reproducer/tasks/crc_layout.yml
Labels: approved, lgtm

#1029 Ensure exceptions are properly encoded before passing them to Ansible
  plugins/module_utils/encoding/ansible_encoding.py
  plugins/module_utils/net_map/exceptions.py
  plugins/module_utils/net_map/networking_definition.py
  tests/unit/module_utils/net_map/test_networking_definitions_all.py
Labels: approved, lgtm

#1030 Converge "ocps" and "crcs" group names
  roles/libvirt_manager/tasks/start_manage_vms.yml
  roles/libvirt_manager/templates/all-inventory.yml.j2
  roles/libvirt_manager/templates/inventory.yml.j2
  roles/reproducer/templates/play.yml.j2
  scenarios/reproducers/3-ocp-networking-definition.yml
  scenarios/reproducers/networking-definition.yml
Labels: approved, lgtm

#1036 Follow-up and corrections to the networking_mapper
  roles/networking_mapper/molecule/default/converge.yml
  roles/networking_mapper/molecule/default/vars/input.yml
  roles/networking_mapper/molecule/default/vars/internalapi_output.yml
  roles/networking_mapper/tasks/network_config_values.yml
  roles/networking_mapper/templates/network-config-values.j2
Labels: approved, lgtm

#976 TF role
  playbooks/run_tofu.yml
  roles/tofu/README.md
  roles/tofu/defaults/main.yml
  roles/tofu/molecule/default/converge.yml
  roles/tofu/molecule/default/molecule.yml
  roles/tofu/molecule/default/prepare.yml
  roles/tofu/molecule/files/main.tf
  roles/tofu/tasks/main.yml
  roles/tofu/tasks/plan.yml
  roles/tofu/tasks/prepare.yml
  roles/tofu/tasks/remote_prepare.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
  zuul.d/tofu.yaml
Labels: approved, lgtm, ok-to-test

#1032 [networking_mapper] Gather facts only on needed hosts
  roles/networking_mapper/tasks/main.yml
Labels: approved, lgtm

#1038 Remove ci_framework folder
  ci_framework/hooks
  ci_framework/playbooks
  ci_framework/plugins
  ci_framework/roles
Labels: approved, lgtm

#1021 Fixed ansible-playbook command in bootstrap hypervisor section
  docs/source/quickstart/02_prepare_env.md
Labels: approved, lgtm

#1006 Integrate ci_local_storage role in edpm deployment
  playbooks/06-deploy-edpm.yml
  roles/ci_local_storage/molecule/default/converge.yml
  roles/ci_local_storage/tasks/worker_node_dirs.yml
  roles/ci_local_storage/templates/storage.yaml.j2
  scenarios/centos-9/ceph_backends.yml
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#1041 [networking_mapping] Add extra IP fields to the output
  plugins/module_utils/net_map/networking_env_definitions.py
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-partial-reduced-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-partial-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-partial-map-out.json
Labels: approved, lgtm

#1040 Make /etc/yum.repos.d writeable for component repos
  roles/repo_setup/tasks/component_repo.yml
Labels: approved, lgtm

#1043 Use `hostname` instead of `name`
  roles/networking_mapper/templates/network-config-values.j2
Labels: approved, lgtm

#1035 Set use_libvirt false in adoption job
  zuul.d/adoption.yaml
Labels: approved, lgtm

#1046 Correct interface name used in base_iface
  roles/networking_mapper/molecule/default/vars/internalapi_output.yml
  roles/networking_mapper/templates/network-config-values.j2
Labels: approved, lgtm

#1047 [networking_mapping] Fix method rename usage in exception handling
  plugins/action/ci_net_map.py
Labels: approved, lgtm

#1048 [networking_mapping] Fix MTU mapping
  plugins/module_utils/net_map/networking_definition.py
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-dual-stack-full-map-out.json
  tests/unit/module_utils/test_files/networking-definition-valid-all-tools-ipv6-only-full-map-out.json
  tests/unit/module_utils/test_utils/net_map_stub_data.py
Labels: approved, lgtm

#1034 [ci_nmstate] Adopt the Networking Env Definition as input
  roles/ci_nmstate/README.md
  roles/ci_nmstate/defaults/main.yml
  roles/ci_nmstate/filter_plugins/ci_nmstate_map_instance_nets.py
  roles/ci_nmstate/filter_plugins/ci_nmstate_map_instance_nets_dns_filter.py
  roles/ci_nmstate/filter_plugins/ci_nmstate_map_instance_nets_interfaces_filter.py
  roles/ci_nmstate/filter_plugins/ci_nmstate_map_instance_nets_routes_filter.py
  roles/ci_nmstate/molecule/default/converge.yml
  roles/ci_nmstate/tasks/main.yml
  roles/ci_nmstate/tasks/nmstate_k8s_provision_node.yml
  roles/networking_mapper/tasks/load_env_definition.yml
Labels: approved, lgtm

#1050 Fix some ansible_vars to make them generic
  hooks/playbooks/fetch_compute_facts.yml
  roles/libvirt_manager/templates/kustomize_compute.yml.j2
Labels: approved

#1060 Ensure PRs code it's used for dataplane deployments
  roles/edpm_deploy/tasks/main.yml
  roles/edpm_deploy_baremetal/tasks/main.yml
Labels: approved, lgtm

#1053 Fix refspec, url for cloning projects in reproducer
  ansible.cfg
  plugins/filter/reproducer_gerrit_infix.py
  plugins/filter/reproducer_refspec.py
  roles/reproducer/tasks/push_code.yml
  tests/integration/targets/filter_reproducer_gerrit_infix/tasks/main.yml
  tests/integration/targets/filter_reproducer_refspec/tasks/main.yml
Labels: approved, lgtm

#1063 Bump crc resources
  zuul.d/base.yaml
Labels: approved, lgtm

#1068 Fixing black formatting with newer versions
  .pre-commit-config.yaml
  plugins/module_utils/net_map/networking_definition.py
  plugins/module_utils/net_map/networking_mapper.py
  tests/unit/module_utils/net_map/test_networking_mapper.py
  tox.ini
Labels: approved, lgtm

#1039 Add job from new layout with ci-bootstrap on main branch
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
Labels: approved, lgtm

#1005 Add test-operator role
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/files/list_allowed.yml
  roles/test_operator/files/list_skipped.yml
  roles/test_operator/meta/main.yml
  roles/test_operator/molecule/default/converge.yml
  roles/test_operator/molecule/default/molecule.yml
  roles/test_operator/molecule/default/prepare.yml
  roles/test_operator/tasks/cleanup.yml
  roles/test_operator/tasks/main.yml
  roles/test_operator/tasks/tempest-tests.yml
  roles/test_operator/vars/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1061 Add missing doc about the VM password
  docs/source/quickstart/99_FAQ.md
  roles/libvirt_manager/README.md
Labels: approved, lgtm

#653 Replace ci_make invocations with ci_script to reduce maintenance
  plugins/README.md
  plugins/action/ci_script.py
  plugins/modules/generate_make_tasks.py
  roles/devscripts/tasks/03_install.yml
  roles/install_yamls/README.md
  roles/operator_build/tasks/build.yml
  roles/operator_deploy/tasks/main.yml
  roles/os_must_gather/tasks/build_openstack-must-gather_image.yml
  tests/integration/targets/make/tasks/ci_make.yml
  tests/integration/targets/script/tasks/main.yml
  zuul.d/end-to-end.yaml
Labels: approved, lgtm

#1059 Add some flags to enable/disable infra components for VA
  docs/source/usage/01_usage.md
  playbooks/02-infra.yml
  scenarios/centos-9/edpm_ci.yml
Labels: approved, lgtm

#1069 Add dmesg log in post-run
  ci/playbooks/collect-logs.yml
Labels: approved, lgtm

#1062 Use an empty dict as fallback instead of omit
  hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#1070 Remove tox from the framework
  Makefile
  test-requirements.txt
  tox.ini
Labels: approved, lgtm

#1072 Add cert-manager installation to BM jobs
  scenarios/centos-9/edpm_baremetal_deployment_ci.yml
Labels: approved, lgtm

#1076 Fix skipped deployment task after ci_make/ci_scripts switch
  roles/devscripts/tasks/03_install.yml
Labels: approved, lgtm

#1079 Fix ci_scripts args management
  plugins/action/ci_script.py
Labels: approved

#1081 Match black linting for ci_script
  plugins/action/ci_script.py
Labels: approved, lgtm

#1075 [devscripts] Enable ip forwarding at global level
  roles/devscripts/files/forwarding.yaml
  roles/devscripts/molecule/default/converge.yml
  roles/devscripts/tasks/sub_tasks/14_user.yml
  roles/devscripts/vars/main.yml
Labels: approved, lgtm

#1066 Get zuul reproducer back on track
  docs/source/reproducers/03-zuul.md
  roles/reproducer/README.md
  roles/reproducer/defaults/main.yml
  roles/reproducer/files/pre-ci-play.yml
  roles/reproducer/tasks/configure_computes.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/reproducer/tasks/rhos_release.yml
  roles/reproducer/templates/play.yml.j2
Labels: approved, lgtm

#1082 Don't remove bootstrap service from sevice list
  hooks/playbooks/fetch_compute_facts.yml
Labels: approved, lgtm

#1077 Ensure we have install_yamls in prow container
  containerfiles/Containerfile.ci
Labels: approved, lgtm

#1080 Allow to skip the libvirt bootstrap
  docs/source/usage/01_usage.md
  roles/reproducer/tasks/main.yml
Labels: approved, lgtm

#1045 [kustomize_deploy] Introduce `kustomize_deploy` role
  ci/config/molecule.yaml
  docs/source/usage/01_usage.md
  roles/kustomize_deploy/README.md
  roles/kustomize_deploy/defaults/main.yml
  roles/kustomize_deploy/meta/main.yml
  roles/kustomize_deploy/molecule/default/cleanup.yml
  roles/kustomize_deploy/molecule/default/converge.yml
  roles/kustomize_deploy/molecule/default/molecule.yml
  roles/kustomize_deploy/molecule/default/prepare.yml
  roles/kustomize_deploy/molecule/default/resources/values.yml
  roles/kustomize_deploy/molecule/default/verify.yml
  roles/kustomize_deploy/tasks/00_check_requirements.yml
  roles/kustomize_deploy/tasks/01_install_operators.yml
  roles/kustomize_deploy/tasks/02_install_controlplane.yml
  roles/kustomize_deploy/tasks/cleanup.yml
  roles/kustomize_deploy/tasks/main.yml
  zuul.d/molecule.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#1089 Increase default dataplane deployment timeout
  roles/edpm_deploy_baremetal/defaults/main.yml
Labels: approved, lgtm

#1088 Update refspec for gitlab
  plugins/filter/reproducer_refspec.py
  tests/integration/targets/filter_reproducer_refspec/tasks/main.yml
Labels: approved, lgtm

#1086 [devscripts] Enable routing via host
  roles/devscripts/README.md
  roles/devscripts/defaults/main.yml
  roles/devscripts/molecule/default/converge.yml
  roles/devscripts/tasks/sub_tasks/14_user.yml
  roles/devscripts/templates/ovn_config.j2
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved, lgtm

#1052 Addressing comments in #1025
  docs/source/files/multinode-params.yml
  roles/devscripts/tasks/sub_tasks/_521_gather.yml
  roles/libvirt_manager/README.md
  roles/libvirt_manager/defaults/main.yml
  roles/reproducer/README.md
  roles/reproducer/defaults/main.yml
  roles/reproducer/tasks/configure_controller.yml
  roles/rhol_crc/tasks/main.yml
  scenarios/reproducers/3-nodes.yml
  scenarios/reproducers/validated-architecture-1.yml
Labels: approved

#1091 Fix reproducer zuul repo checkout with no change
  roles/reproducer/tasks/push_code.yml
Labels: approved, lgtm

#1092 Fix zuul HCI job that is missing the bootstrap service
  roles/hci_prepare/tasks/phase1.yml
Labels: approved, lgtm
