Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-08, with the labels that each got.

#3180 Add option to update Watcher containers in OpenStackVersion
  docs/dictionary/en-custom.txt
  roles/edpm_prepare/tasks/kustomize_and_deploy.yml
  roles/update_containers/README.md
  roles/update_containers/defaults/main.yml
  roles/update_containers/templates/update_containers.j2
Labels: lgtm, Ready For Review

#3181 Allow start infra VMs early
  create-infra.yml
Labels: Ready For Review

#3168 Fix ansible 2.19 jinja incompatibility
  hooks/playbooks/fetch_compute_facts.yml
  roles/ci_dcn_site/templates/edpm-pre-ceph/nodeset/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#3183 Document test-operator key file parameter
  roles/test_operator/README.md
Labels: Ready For Review

#3164 Add hook for RBD mirror replication between Ceph clusters
  hooks/playbooks/apply_cinder_replication_kustomization.yml
  hooks/playbooks/enable_rbd_mirror_replication.yml
Labels: lgtm, Ready For Review

#3102 update ceph ipv6 when conditions
  playbooks/ceph.yml
Labels: lgtm, Ready For Review

#3182 Fix replacing osp network names
  roles/adoption_osp_deploy/tasks/config_files.yml
Labels: Ready For Review

#3191 Support restarting iscsid running on host
  hooks/playbooks/compute-iscsi-config.yml
Labels: approved, lgtm, Ready For Review

#3202 Add retries to openshift_obs deployment and pod
  roles/openshift_obs/tasks/main.yml
Labels: Ready For Review

#3207 Enable horizon in upstream CI jobs to test Glance CORS configuration
  hooks/playbooks/templates/config_ceph_backends.yaml.j2
Labels: lgtm, Ready For Review

#3223 Fix LVMCluster until clause
  roles/ci_lvms_storage/tasks/main.yml
Labels: lgtm, Ready For Review

#3201 feat: enhance check if local common-requirements.txt exists
  roles/reproducer/tasks/configure_controller.yml
Labels: ok-to-test, Ready For Review

#3154 Move Ceph playbook into hooks
  deploy-edpm.yml
  hooks/playbooks/README.md
  hooks/playbooks/ceph-bm.yml
  hooks/playbooks/ceph.yml
  playbooks/06-deploy-edpm.yml
  playbooks/ceph.yml
  roles/ci_dcn_site/tasks/ceph.yml
  roles/cifmw_cephadm/README.md
  roles/hci_prepare/README.md
  scenarios/centos-9/hci_ceph_backends.yml
  zuul.d/edpm.yaml
  zuul.d/edpm_multinode.yaml
Labels: Ready For Review

#3226 Fix SNR/NHC role CRD availability timing issues
  roles/cifmw_snr_nhc/defaults/main.yml
  roles/cifmw_snr_nhc/tasks/main.yml
Labels: Ready For Review

#3217 Add dz-storage.yml scenario
  roles/ci_gen_kustomize_values/templates/.gitignore
  roles/ci_gen_kustomize_values/templates/dz-storage
  scenarios/reproducers/dz-storage.yml
Labels: Ready For Review

#3197 Add ram to va-pidone workers
  scenarios/reproducers/va-pidone.yml
Labels: Ready For Review

#3196 Run postdeploy tasks one when deploy is enabled
  reproducer.yml
Labels: Ready For Review
