Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-09, with the labels that each got.

#3238 Remove condition for zuul_log_collection to openstack-must-gather
  roles/cifmw_setup/tasks/run_logs.yml
Labels: Ready For Review

#3246 Add logging to a file for os must gather task
  ci/playbooks/e2e-collect-logs.yml
  roles/cifmw_setup/tasks/run_logs.yml
Labels: Ready For Review

#3250 Add two dz-storage post-deployment playbooks
  hooks/playbooks/dz_storage_post_deploy_az.yaml
  hooks/playbooks/dz_storage_pre_test_images.yaml
Labels: Ready For Review

#3260 Do not wipe Ansible facts in post stage
  roles/cifmw_setup/tasks/run_logs.yml
Labels: lgtm, ok-to-test

#3244 Allow to add metadata labels to BMH
  roles/deploy_bmh/template/bmh.yml.j2
Labels: Ready For Review

#3222 Add tempest test run in between services and system update to update role
  roles/update/tasks/update_variant_split.yml
Labels: lgtm, Ready For Review

#3265 openshift_setup: enable registry.connect.redhat.com too
  roles/openshift_setup/tasks/main.yml
Labels: Ready For Review

#3266 Check if hook is properly defined for execution
  roles/run_hook/tasks/main.yml
Labels: Ready For Review

#3256 [edpm_prepare] Add cifmw_edpm_prepare_extra_kustomizations var
  roles/edpm_prepare/README.md
  roles/edpm_prepare/defaults/main.yml
  roles/edpm_prepare/tasks/kustomize_and_deploy.yml
Labels: Ready For Review

#3230 Add tobikoPatch parameter for custom patches
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: Ready For Review

#3280 Set fail-fast to true in upstream zuul project
  ci/templates/projects.yaml
  zuul.d/projects.yaml
Labels: Ready For Review

#3263 update_containers: allow to set full URIs for volume containers
  roles/update_containers/README.md
  roles/update_containers/defaults/main.yml
  roles/update_containers/templates/update_containers.j2
Labels: Ready For Review

#3269 Add cifmw_hci_prepare_extra_services parameter
  roles/hci_prepare/README.md
  roles/hci_prepare/defaults/main.yml
  roles/hci_prepare/tasks/phase2.yml
Labels: Ready For Review

#3247 Dump openstack databases when must-gather is collected
  roles/os_must_gather/defaults/main.yml
  roles/os_must_gather/tasks/main.yml
Labels: lgtm, Ready For Review

#3243 Expose new parameter TimingDataUrl
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: Ready For Review

#3287 Improve getting CRC pods logs
  roles/artifacts/tasks/crc.yml
Labels: Ready For Review

#3229 Un-pin the nat64 CS 9-stream image
  roles/nat64_appliance/tasks/main.yml
Labels: Stale, Ready For Review

#3258 Add read_global_vars.yml in pre-run stage
  zuul.d/base.yaml
  zuul.d/end-to-end.yaml
  zuul.d/kuttl.yaml
  zuul.d/kuttl_multinode.yaml
  zuul.d/tcib.yaml
  zuul.d/test-job.yaml
Labels: Ready For Review

#3285 Add hook_retry parameter for run_hook role
  roles/run_hook/README.md
  roles/run_hook/molecule/default/converge.yml
  roles/run_hook/molecule/default/molecule.yml
  roles/run_hook/molecule/default/prepare.yml
  roles/run_hook/molecule/default/templates/dummy-retry.yml.j2
  roles/run_hook/tasks/playbook.yml
Labels: Ready For Review

#3312 Add parsing external inventory file and add host
  roles/cifmw_helpers/README.md
  roles/cifmw_helpers/tasks/inventory_file.yml
  roles/cifmw_helpers/tasks/parse_inventory.yml
Labels: Ready For Review

#3317 Remove KRB5_TRACE to avoid trace logging output
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: lgtm, Ready For Review

#3321 Add ansible_ssh_args into cifmw_helpers parse inventory
  roles/cifmw_helpers/tasks/parse_inventory.yml
Labels: Ready For Review

#3299 Fix: search openstack-operator-index in all namespaces
  roles/env_op_images/tasks/main.yml
Labels: do-not-merge/contains-merge-commits, Ready For Review

#3311 Add cifmw-crc-edpm-podified-baremetal-bootc job
  roles/edpm_deploy_baremetal/defaults/main.yml
  roles/edpm_deploy_baremetal/tasks/main.yml
  zuul.d/edpm.yaml
  zuul.d/project-templates.yaml
Labels: Ready For Review

#3331 hook: ironic_networks.yml - IPv6 support
  hooks/playbooks/ironic_network.yml
Labels: Ready For Review

#3348 Add all molecule files to the scope of check_zuul_jobs
  zuul.d/pods.yaml
Labels: Ready For Review

#3332 Remove read_global_vars pre-task from jobs
  zuul.d/adoption.yaml
  zuul.d/base.yaml
  zuul.d/edpm_build_images.yaml
  zuul.d/edpm_build_images_content_provider.yaml
  zuul.d/end-to-end.yaml
  zuul.d/kuttl.yaml
  zuul.d/kuttl_multinode.yaml
  zuul.d/molecule-base.yaml
  zuul.d/pods.yaml
  zuul.d/tcib.yaml
  zuul.d/test-job.yaml
Labels: Ready For Review

#3336 Remove deprecated cifmw_tempest_tempestconf_config
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: lgtm, Ready For Review

#3355 Increase the scope of cifmw-pods-zuul-files job
  zuul.d/pods.yaml
Labels: Ready For Review

#3354 Hook to cleanup baremetal network agents
  hooks/playbooks/ironic_network_agent_cleanup.yml
Labels: Ready For Review
