Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-06, with the labels that each got.

#3031 Fix network config in create_cloud_init_iso.yml
  roles/libvirt_manager/tasks/create_cloud_init_iso.yml
Labels: Ready For Review

#2863 dnsmasq: Add locahost addresses to lo
  roles/dnsmasq/tasks/configure.yml
Labels: Ready For Review

#3026 Remove bshephard
  .github/CODEOWNERS
Labels: lgtm, Ready For Review

#3030 Add retries to kinit call
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: Ready For Review

#3024 Multinode EDPM CI job failing for nmstate provider
  hooks/playbooks/fetch_compute_facts.yml
Labels: Ready For Review

#3047 Rename _network_data in create_cloud_init_iso to _network_data_config_drive
  roles/libvirt_manager/tasks/create_cloud_init_iso.yml
Labels: lgtm, Ready For Review

#3049 Temporary override keystone config in job
  zuul.d/tempest_multinode.yaml
Labels: Ready For Review

#3045 Fix pre_tests not running
  deploy-edpm.yml
  roles/cifmw_setup/tasks/run_tests.yml
  update-edpm.yml
Labels: Ready For Review

#3055 Remove printing redhat-release in adoption_osp_deploy
  roles/adoption_osp_deploy/tasks/prepare_overcloud.yml
Labels: Ready For Review

#3018 Enable cleanup for test operator
  clean_openstack_deployment.yaml
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/cleanup-run.yaml
  roles/test_operator/tasks/cleanup.yaml
  roles/test_operator/tasks/collect-logs.yaml
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: Ready For Review

#3057 Sync the src dir with controllers in reproducer inventory
  roles/reproducer/tasks/configure_controller.yml
Labels: lgtm, ok-to-test, Ready For Review

#3034 Use role instead of playbooks - validations.yml
  playbooks/06-deploy-architecture.yml
  playbooks/06-deploy-edpm.yml
  playbooks/validations.yml
Labels: Ready For Review

#3059 Add ansible cache dir to git ignore
  .gitignore
Labels: Ready For Review

#3020 Allow bmh cleanup and move cleanup to role
  clean_openstack_deployment.yaml
  docs/dictionary/en-custom.txt
  roles/cleanup_openstack/README.md
  roles/cleanup_openstack/defaults/main.yaml
  roles/cleanup_openstack/tasks/cleanup_crs.yaml
  roles/cleanup_openstack/tasks/detach_bmh.yaml
  roles/cleanup_openstack/tasks/main.yaml
Labels: Ready For Review

#3060 Fix task and vars names
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/collect-logs.yaml
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: Ready For Review

#3051 Use role instead of playbooks - 03-build-packages.yml
  deploy-edpm.yml
  playbooks/03-build-packages.yml
  roles/cifmw_setup/tasks/build_packages.yml
Labels: Ready For Review

#3064 rsync only if source directory exists
  roles/reproducer/tasks/configure_controller.yml
Labels: Ready For Review

#3070 Let sync workflow work with non-default branches
  .github/workflows/sync_branches_reusable_workflow.yml
Labels: Ready For Review

#3016 fix sushy_emulator: move register out of slurp module block
  roles/sushy_emulator/tasks/collect_details.yml
Labels: ok-to-test

#3069 Increase vm boot wait time
  roles/libvirt_manager/tasks/start_vms.yml
Labels: Ready For Review

#3053 Use role instead of playbooks - 05-build-operators.yml
  deploy-edpm.yml
  playbooks/05-build-operators.yml
  roles/cifmw_setup/tasks/build_operators.yml
Labels: Ready For Review

#3052 Use role instead of playbooks - 04-build-containers.yml
  deploy-edpm.yml
  playbooks/04-build-containers.yml
  roles/cifmw_setup/tasks/build_containers.yml
Labels: Ready For Review

#3048 adoption_osp_deploy: allow to pass private overcloud args
  roles/adoption_osp_deploy/README.md
  roles/adoption_osp_deploy/defaults/main.yml
  roles/adoption_osp_deploy/tasks/deploy_overcloud.yml
Labels: Ready For Review

#3037 Set default values to Resources parameter
  roles/test_operator/defaults/main.yml
Labels: Ready For Review

#3078 Patch samples registry
  roles/openshift_setup/tasks/main.yml
  roles/openshift_setup/tasks/patch_samples_registry.yml
Labels: Ready For Review

#3076 Fix the default value of cifmw_nfs_target
  roles/cifmw_nfs/defaults/main.yml
Labels: lgtm, Ready For Review

#3085 Improve generated JUnit XML from validations framework
  roles/validations/filter_plugins/cifmw_validations_xml_filter.py
Labels: approved, lgtm, Ready For Review

#3002 Use transparent vlan in ci bootstrap
  zuul.d/adoption.yaml
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
  zuul.d/kuttl_multinode.yaml
  zuul.d/podified_multinode.yaml
  zuul.d/tempest_multinode.yaml
Labels: Ready For Review

#3071 Use role instead of playbooks - 06-deploy-edpm.yml
  deploy-edpm.yml
  playbooks/06-deploy-edpm.yml
  playbooks/validations.yml
  roles/cifmw_setup/tasks/deploy_edpm.yml
  roles/cifmw_setup/tasks/hci_deploy.yml
Labels: Ready For Review

#3082 Add empty adoption scenario uni07eta
  scenarios/adoption/uni07eta.yml
Labels: Ready For Review

#3088 Set gather_facts to true for post deployment
  post-deployment.yml
Labels: Ready For Review

#3072 Allow setting up 8 OCP nodes
  roles/devscripts/vars/main.yml
Labels: Ready For Review

#3081 Add cifmw_cleanup_architecture var to enable/disable cleanup
  deploy-edpm-reuse.yaml
Labels: Ready For Review

#3095 Add missing conditional for Update the go.mod file for no pr case
  roles/operator_build/tasks/build.yml
Labels: Ready For Review
