Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-03, with the labels that each got.

#2758 Add Networker hosts to edpm_vms for log collection
  roles/artifacts/tasks/edpm.yml
Labels: Ready For Review

#2775 [neutron-whitebox] Skip test of BZ#2214566/OSPRH-13533 for antelope
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: lgtm, Ready For Review

#2722 Add horizontest params to add possibility to run tests for different themes
  docs/dictionary/en-custom.txt
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: Ready For Review

#2783 Revert "Add job for testing watcher in the master pipeline"
  zuul.d/edpm_periodic.yaml
Labels: lgtm, Ready For Review

#2771 Add wait to prevent race condition
  roles/test_operator/tasks/run-test-operator-job.yml
Labels: lgtm, Ready For Review

#2778 Add federation role to ci-framework
  docs/dictionary/en-custom.txt
  hooks/playbooks/federation-controlplane-config.yml
  hooks/playbooks/federation-post-deploy.yml
  hooks/playbooks/federation-pre-deploy.yml
  roles/federation/README.md
  roles/federation/defaults/main.yml
  roles/federation/tasks/run_keycloak_realm_setup.yml
  roles/federation/tasks/run_keycloak_setup.yml
  roles/federation/tasks/run_openstack_auth_test.yml
  roles/federation/tasks/run_openstack_setup.yml
  roles/federation/tasks/run_osp_cmd.yml
  roles/federation/templates/get-token.sh.j2
  roles/federation/templates/kctestuser1.j2
  roles/federation/templates/rhsso-operator-olm.yaml.j2
  roles/federation/templates/rules.json.j2
  roles/federation/templates/sso.yaml.j2
Labels: Ready For Review

#2786 Guarantee resources on shiftstackclient pod
  roles/shiftstack/templates/shiftstackclient_pod.yml.j2
Labels: lgtm, Ready For Review

#2804 Add content-provider variant for FR2
  zuul.d/base.yaml
Labels: lgtm, Ready For Review

#2810 Revert "Add content-provider variant for FR2"
  zuul.d/base.yaml
Labels: Ready For Review

#2817 Change yq with jq for image filtering
  roles/env_op_images/tasks/main.yml
Labels: Ready For Review

#2812 Add IBM nodesets that will enforce spawning CI on IBM hosts
  zuul.d/nodeset.yaml
Labels: Ready For Review

#2752 [libvirt_manager] Add retry to vm start
  roles/libvirt_manager/tasks/start_one_vm.yml
  roles/libvirt_manager/tasks/start_vms.yml
Labels: approved, Ready For Review

#2811 Use only IBM hosts for some molecule CI jobs
  ci/config/molecule.yaml
  zuul.d/molecule.yaml
Labels: Ready For Review

#2820 Adds GH action to sync branches
  .github/workflows/sync_branches_periodically.yml
  .github/workflows/sync_branches_reusable_workflow.yml
Labels: Ready For Review

#2800 Move baremetal, Kuttle and Tufu jobs to 4.18 nested
  zuul.d/base.yaml
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
  zuul.d/tofu.yaml
Labels: Ready For Review

#2822 Use zuul clonned repos for upstream in build_openstack_packages role
  roles/build_openstack_packages/tasks/parse_and_build_pkgs.yml
  roles/build_openstack_packages/tasks/run_dlrn.yml
Labels: lgtm, Ready For Review

#2823 Adds gh actions to sync branches
  .github/workflows/sync_branches_periodically.yml
  .github/workflows/sync_branches_reusable_workflow.yml
  .github/workflows/sync_branches_with_ext_trigger.yml
Labels: Ready For Review

#2838 Update the trigger job to use cifms's workflow
  .github/workflows/sync_branches_with_ext_trigger.yml
Labels: Ready For Review

#2825 Set owner:group for directories on controller-0
  create-infra.yml
Labels: Ready For Review
