Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-02, with the labels that each got.

#2692 Removes Soniya from owners
  OWNERS
Labels: approved, lgtm, Ready For Review

#2587 Add the steps to reboot the computes after update.
  roles/update/README.md
  roles/update/defaults/main.yml
  roles/update/molecule/default/prepare.yml
  roles/update/tasks/main.yml
  roles/update/tasks/reboot_computes.yml
  roles/update/tasks/reboot_hypervisor.yml
  roles/update/tasks/reboot_hypervisor_sanity_checks.yml
  roles/update/tasks/reboot_hypervisor_using_cr.yml
  roles/update/templates/monitor_servers.sh.j2
  roles/update/templates/monitor_vm_placement.sh.j2
Labels: enhancement, approved, lgtm, Ready For Review

#2653 Fix adoption_vars, only one defaultRoute
  roles/adoption_osp_deploy/README.md
  roles/adoption_osp_deploy/defaults/main.yml
  roles/adoption_osp_deploy/templates/adoption_vars.yaml.j2
Labels: Ready For Review

#2701 Removes Mikolaj from Polarios codeowner
  .github/CODEOWNERS
Labels: Ready For Review

#2703 Remove DS tigger PoC content
  .github/workflows/github-action-trigger-downstream-job-reusable-workflow.yaml
  .github/workflows/trigger-downstream-job.yaml
  ci/templates/projects.yaml
  zuul.d/adoption.yaml
  zuul.d/base.yaml
  zuul.d/projects.yaml
  zuul.d/trigger_jobs.yaml
Labels: approved, Ready For Review

#2591 ci_dcn_site: Add scaling down of a DCN site
  playbooks/dcn.yml
  roles/ci_dcn_site/README.md
  roles/ci_dcn_site/defaults/main.yml
  roles/ci_dcn_site/tasks/deploy_site.yml
  roles/ci_dcn_site/tasks/main.yml
  roles/ci_dcn_site/tasks/scaledown_site.yml
  roles/ci_dcn_site/templates/service-values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2694 [openshift_setup] Add support for overriding dependent operators CatalogSource
  docs/dictionary/en-custom.txt
  docs/source/usage/01_usage.md
  roles/kustomize_deploy/tasks/install_operators.yml
  roles/openshift_setup/defaults/main.yml
  roles/openshift_setup/tasks/patch_dependent_operators_source.yml
Labels: approved, Ready For Review

#2717 Add "tobiko" namespace to be gathered by the openstack-must-gather
  roles/os_must_gather/defaults/main.yml
Labels: lgtm, Ready For Review

#2718 Fix wait condition for OpenStack initialization resource
  roles/kustomize_deploy/tasks/install_operators.yml
Labels: lgtm

#2721 Add Ansible variable cifmw_openshift_setup_apply_marketplace_fix
  roles/openshift_setup/README.md
  roles/openshift_setup/defaults/main.yml
  roles/openshift_setup/tasks/fix_openshift_marketplace.yml
Labels: approved, Ready For Review

#2697 adoption_osp_deploy : br-baremetal ovs_bridge
  roles/adoption_osp_deploy/templates/os_net_config_overcloud.yml.j2
Labels: Ready For Review

#2699 Update build_openstack_packages to support downstream gitlab
  Makefile
  roles/build_openstack_packages/tasks/run_dlrn.yml
  roles/build_openstack_packages/templates/projects.ini.j2
Labels: lgtm, Ready For Review

#2726 Filter out rhos branches when setting openstack_k8s_branch
  roles/install_yamls/tasks/main.yml
Labels: lgtm

#2678 Switch cinder uniquePodNames to true for DCN deployments
  roles/ci_dcn_site/templates/service-values.yaml.j2
Labels: approved, lgtm

#2700 unialpha adopt: provider-physical-network = ironic
  hooks/playbooks/adoption_ironic_post_oc.yml
Labels: Ready For Review

#2691 BGP controlplane Pure L3 Spine&Leaf
  playbooks/bgp-l3-computes-ready.yml
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-common-nodeset-values/common-bgp-edpm-values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-networker-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-r0-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-r0-networker-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-r1-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-r1-networker-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-r2-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/edpm-r2-networker-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/network-values/values.yaml.j2
  roles/reproducer/tasks/configure_computes.yml
  roles/reproducer/tasks/libvirt_layout.yml
Labels: Ready For Review

#2732 Update tempest image via update_containers role
  roles/update_containers/templates/update_containers.j2
Labels: Ready For Review

#2729 Add fqdn to the list of host patterns in ssh config
  roles/libvirt_manager/tasks/manage_vms.yml
Labels: lgtm, Ready For Review

#2730 Add cifmw_bop_versions_url to pass versions.csv url
  roles/build_openstack_packages/README.md
  roles/build_openstack_packages/defaults/main.yml
  roles/build_openstack_packages/templates/projects.ini.j2
Labels: Ready For Review

#2733 [bop]Donot use dlrn --local for downstream
  roles/build_openstack_packages/templates/run_dlrn.sh.j2
Labels: Ready For Review

#2736 [ci_gen_kustomize_values] Remove BGP templates
  .github/CODEOWNERS
  roles/ci_gen_kustomize_values/templates/bgp/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp/network-values/values.yaml.j2
Labels: Ready For Review

#2624 Add scenario unizeta06 adoption
  scenarios/adoption/uni06zeta.yml
Labels: Ready For Review

#2743 Add missing kubeconfig file name to shiftstack test
  roles/shiftstack/tasks/test_config.yml
Labels: lgtm, Ready For Review

#2727 Change the method of installing test-operator
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/cleanup.yml
  roles/test_operator/tasks/main.yml
Labels: Ready For Review

#2738 Update COO sub to stable channel
  roles/openshift_obs/defaults/main.yml
Labels: Ready For Review

#2735 Add hooks before running kuttl from operator target
  ci/playbooks/kuttl/deploy-deps.yaml
  ci/playbooks/kuttl/kuttl-from-operator-run.yaml
  ci/playbooks/kuttl/run-kuttl-from-operator-targets.yaml
  docs/source/usage/01_usage.md
  zuul.d/kuttl_multinode.yaml
Labels: lgtm, Ready For Review

#2739 [kustomize_deploy] Add name field in architecture steps
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: Ready For Review

#2751 OSPCIX-683 - Fix unbound.service startup error
  roles/nat64_appliance/files/elements/nat64-router/static/etc/unbound/unbound.conf
Labels: Ready For Review

#2716 [shiftstack]Switch incluster-kubeconfig to admin context
  roles/shiftstack/tasks/deploy_shiftstackclient_pod.yml
Labels: Ready For Review

#2754 [18.0-fr1] Update converge test controlplane kustomize directory
  roles/ci_gen_kustomize_values/molecule/default/converge.yml
Labels: Ready For Review

#2756 Remove outdated/wrong definition of cifmw_artifacts_gather_logs
  roles/artifacts/README.md
Labels: Ready For Review

#2761 Change Ceph Dashboard port to 8443
  roles/cifmw_cephadm/defaults/main.yml
Labels: lgtm, Ready For Review

#2763 Add CI&Ops as test roles owners
  .github/CODEOWNERS
Labels: lgtm, Ready For Review

#2760 [krb_request] Include json body if given
  plugins/modules/krb_request.py
  roles/krb_request/README.md
  roles/krb_request/tasks/main.yml
Labels: Ready For Review

#2766 [docs] Add zuul retention docs
  docs/dictionary/en-custom.txt
  docs/source/index.rst
  docs/source/zuul/zuul-job-nodeset.md
  docs/source/zuul/zuul-multinode-autoholds.md
Labels: Ready For Review
