Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-04, with the labels that each got.

#2837 Change base molecule nodeset to use just IBM providers
  zuul.d/molecule-base.yaml
  zuul.d/nodeset.yaml
Labels: Ready For Review

#2857 Add retries in connectivity test
  roles/reproducer/tasks/configure_computes.yml
Labels: Ready For Review

#2854 Fix path error in federation role
  roles/federation/tasks/run_keycloak_setup.yml
Labels: ok-to-test, Ready For Review

#2858 Pull dlrn hash md5 while populating component repo
  roles/repo_setup/tasks/artifacts.yml
Labels: Ready For Review

#2860 Adds crc-storage namespace to os mustgather
  roles/os_must_gather/defaults/main.yml
Labels: lgtm, Ready For Review

#2859 Rename nodesets to include crc-cloud in the name
  zuul.d/nodeset.yaml
Labels: Ready For Review

#2835 Change nodeset name and label related to force spawning on IBM
  zuul.d/nodeset.yaml
Labels: Ready For Review

#2819 Switch edpm-multinode github-check jobs to OCP - 4.18
  zuul.d/adoption.yaml
  zuul.d/base.yaml
  zuul.d/edpm_multinode.yaml
  zuul.d/kuttl_multinode.yaml
  zuul.d/podified_multinode.yaml
  zuul.d/tempest_multinode.yaml
Labels: Ready For Review

#2861 Allow setting BM_INSTANCE_MEMORY var
  roles/install_yamls/defaults/main.yml
Labels: Ready For Review

#2865 [kuttl multinode] Disable router with gateways
  zuul.d/kuttl_multinode.yaml
Labels: Ready For Review

#2871 Switch adoption base job to use OCP 4.18
  zuul.d/adoption.yaml
Labels: lgtm, Ready For Review

#2875 Switch to OCP 4.18 for periodic-whitebox-neutron-tempest-plugin CI job
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: lgtm

#2872 Set timezone to UTC in cloud-init user-data
  roles/libvirt_manager/tasks/create_cloud_init_iso.yml
Labels: Ready For Review

#2864 Add bgp-l3-xl dt
  .github/CODEOWNERS
  playbooks/bgp/prepare-bgp-computes.yaml
  playbooks/bgp/prepare-bgp-hypervisor-from-controller.yaml
  playbooks/bgp/prepare-bgp-spines-leaves.yaml
  playbooks/bgp/templates/leaf-frr.conf.j2
  playbooks/bgp/templates/router-frr.conf.j2
  playbooks/bgp/templates/spine-frr.conf.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/edpm-common-nodeset-values/common-bgp-edpm-values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/edpm-r0-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/edpm-r0-networker-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/edpm-r1-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/edpm-r1-networker-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/edpm-r2-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/edpm-r2-networker-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/network-values/values.yaml.j2
  roles/reproducer/tasks/ocp_layout.yml
  scenarios/reproducers/bgp-l3-xl.yml
Labels: Ready For Review

#2877 adoption_osp_deploy: edpm_nodes_networker section
  roles/adoption_osp_deploy/templates/adoption_vars.yaml.j2
Labels: Ready For Review

#2784 [ci_dcn_site] Update repo variables paths
  roles/ci_dcn_site/defaults/main.yml
Labels: Ready For Review

#2847 Adds GH action to run branch sync
  .github/workflows/sync_branches_reusable_workflow.yml
  .github/workflows/sync_branches_with_ext_trigger.yml
Labels: Ready For Review

#2889 [cifmw_external_dns] Check better for the secret
  roles/cifmw_external_dns/tasks/cert.yml
Labels: lgtm, Ready For Review

#2903 [OSPNW-910] Add kustomize template for uni04delta-ipv6-adoption
  roles/ci_gen_kustomize_values/templates/uni04delta-ipv6-adoption/network-values/values.yaml.j2
Labels: Ready For Review

#2833 Dcn compute replace
  playbooks/dcn.yml
  roles/ci_dcn_site/README.md
  roles/ci_dcn_site/tasks/add_node.yml
  roles/ci_dcn_site/tasks/ceph.yml
  roles/ci_dcn_site/tasks/post-ceph.yml
  roles/ci_dcn_site/tasks/remove_node.yml
  roles/ci_dcn_site/tasks/scaledown_site.yml
  roles/ci_dcn_site/tasks/update_conf_new_node.yml
  roles/ci_dcn_site/templates/dataplane_remove_node_deploy.yaml.j2
  roles/ci_dcn_site/templates/deployment/values.yaml.j2
  roles/ci_dcn_site/templates/node_network_env_definitions.yaml.j2
  roles/ci_dcn_site/templates/values.yaml.j2
  roles/cifmw_cephadm/tasks/scale_down_node.yml
Labels: lgtm, Ready For Review

#2828 Start virtqemud service instead of checking for the sock path
  roles/libvirt_manager/tasks/clean_layout.yml
Labels: Ready For Review

#2915 Set `ignore_errors` to true for crawl_n_mask
  roles/artifacts/tasks/main.yml
Labels: Ready For Review

#2910 Increase ControlPersist timeout to 300 seconds
  ansible.cfg
Labels: Ready For Review

#2895 [kustomize_deploy] use recursive=True to combine user kustomize values
  roles/kustomize_deploy/tasks/execute_step.yml
Labels: Ready For Review

#2908 Fix get cri-o stats script
  scripts/get-stats.sh
Labels: Ready For Review

#2909 Removed variant of cifmw-molecule-tofu job
  ci/config/molecule.yaml
  ci/templates/molecule.yaml.j2
  zuul.d/molecule.yaml
  zuul.d/tofu.yaml
Labels: Ready For Review

#2914 Use python from user's environment
  scripts/create_role_molecule.py
Labels: Ready For Review

#2878 use ceph ingress service vars
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/templates/ceph_rgw.yml.j2
Labels: lgtm, Ready For Review

#2686 [reproducers][nfv] Add Networker node to deployment
  roles/ci_gen_kustomize_values/tasks/edpm_compute_nodeset_values.yml
  roles/ci_gen_kustomize_values/tasks/edpm_networker_nodeset_values.yml
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov-networker/edpm-common-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov-networker/edpm-compute-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/ovs-dpdk-sriov-networker/edpm-networker-nodeset-values/values.yaml.j2
  scenarios/reproducers/dt-nfv-ovs-dpdk-sriov-networker.yml
Labels: Ready For Review

#2893 Change hardcoded eth0 value in multinode-customizations play
  ci/playbooks/multinode-customizations.yml
Labels: Ready For Review

#2912 Add insecure registries to DT/VA style deployments
  roles/openshift_setup/tasks/main.yml
Labels: Ready For Review

#2876 Remove rgw default zone and realm
  roles/cifmw_cephadm/templates/ceph_rgw.yml.j2
Labels: Ready For Review

#2887 Create bmh compute replace validator
  roles/validations/defaults/main.yml
  roles/validations/tasks/edpm/bmh_compute_replace.yml
Labels: lgtm, Ready For Review

#2923 Do not print oc completion
  roles/ci_setup/tasks/packages.yml
Labels: Ready For Review

#2928 cd_dcn_site: Set the correct hostname
  roles/ci_dcn_site/tasks/az.yml
  roles/ci_dcn_site/templates/edpm-pre-ceph/nodeset/values.yaml.j2
Labels: lgtm
