Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-07, with the labels that each got.

#3066 Use role instead of playbooks - 06-deploy-architecture.yml
  deploy-edpm.yml
  playbooks/06-deploy-architecture.yml
  playbooks/validations.yml
  roles/ci_lvms_storage/README.md
  roles/cifmw_setup/defaults/main.yml
  roles/cifmw_setup/tasks/deploy_architecture.yml
Labels: Ready For Review

#3111 Trigger documentation Github action job when "recheck" provided
  .github/workflows/documentation.yml
Labels: Ready For Review

#3103 Allow setting container name prefix
  roles/update_containers/README.md
  roles/update_containers/defaults/main.yml
  roles/update_containers/templates/update_containers.j2
Labels: Ready For Review

#3098 Improve warning comment in playbooks
  playbooks/01-bootstrap.yml
  playbooks/02-infra.yml
  playbooks/03-build-packages.yml
  playbooks/04-build-containers.yml
  playbooks/05-build-operators.yml
  playbooks/06-deploy-architecture.yml
  playbooks/06-deploy-edpm.yml
  playbooks/07-admin-setup.yml
  playbooks/08-run-tests.yml
  playbooks/09-compliance.yml
  playbooks/nfs.yml
  playbooks/validations.yml
Labels: Ready For Review

#3109 Ignore ansible lint in few tasks
  roles/ci_dcn_site/tasks/ceph.yml
  roles/libvirt_manager/tasks/create_cloud_init_iso.yml
Labels: lgtm, Ready For Review

#3105 Update: fix broken registry login
  roles/update/tasks/create_local_openstackclient.yml
Labels: Ready For Review

#3044 Add playbook to configure Proteccio access for Barbican
  docs/dictionary/en-custom.txt
  hooks/playbooks/barbican-enable-proteccio.yml
Labels: lgtm, Ready For Review

#3089 Improve crawl_n_mask script
  ci/playbooks/collect-logs.yml
  plugins/modules/crawl_n_mask.py
  tests/unit/modules/test_crawl_n_mask.py
Labels: Ready For Review

#3115 update: fix naming convention.
  roles/update/tasks/create_local_openstackclient.yml
Labels: Ready For Review

#3121 Set ovn-egress-iface=true for br-ex physical NIC
  hooks/playbooks/fetch_compute_facts.yml
Labels: Ready For Review

#3114 Update shiftstack reviewers
  .github/CODEOWNERS
Labels: Ready For Review

#3142 Fix terminology: use "architecture-based" instead of "VA"
  deploy-edpm.yml
  docs/source/usage/01_usage.md
  playbooks/06-deploy-architecture.yml
  roles/ci_gen_kustomize_values/README.md
  roles/kustomize_deploy/README.md
  roles/kustomize_deploy/tasks/check_requirements.yml
  roles/reproducer/tasks/main.yml
  roles/reproducer/tasks/reuse_main.yaml
Labels: Ready For Review

#3140 [debug] Print the rhos-release URL
  roles/repo_setup/tasks/rhos_release.yml
Labels: approved, lgtm, Ready For Review

#3133 Use FQCN during the use of a module
  plugins/README.md
  plugins/action/ci_kustomize.py
  plugins/action/ci_script.py
  plugins/action/discover_latest_image.py
  plugins/modules/generate_make_tasks.py
  roles/artifacts/tasks/crc.yml
  roles/artifacts/tasks/main.yml
  roles/discover_latest_image/tasks/main.yml
  roles/edpm_prepare/tasks/kustomize_and_deploy.yml
  roles/install_yamls/README.md
  roles/operator_build/tasks/build.yml
  roles/operator_deploy/tasks/main.yml
  roles/os_must_gather/tasks/build_openstack-must-gather_image.yml
  tests/integration/targets/kustomize/tasks/run_test_case.yml
  tests/integration/targets/make/tasks/ci_make.yml
  tests/integration/targets/script/tasks/main.yml
Labels: lgtm, Ready For Review

#3144 [bop] Donot parse changes for cifmw_bop_skipped_projects
  roles/build_openstack_packages/defaults/main.yml
  roles/build_openstack_packages/tasks/parse_and_build_pkgs.yml
Labels: Ready For Review

#3145 Symlink cifmw collection adjacent to ci playbooks
  ci/playbooks/collections/ansible_collections/cifmw/general/galaxy.yml
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/README.md
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/action/ci_kustomize.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/action/ci_make.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/action/ci_net_map.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/action/ci_script.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/action/discover_latest_image.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/filter/reproducer_gerrit_infix.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/filter/reproducer_refspec.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/filter/to_nice_yaml_all.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/module_utils/__init__.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/module_utils/encoding
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/module_utils/net_map
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/approve_csr.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/bridge_vlan.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/cephx_key.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/crawl_n_mask.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/generate_make_tasks.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/get_makefiles_env.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/krb_request.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/pem_read.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/tempest_list_allowed.py
  ci/playbooks/collections/ansible_collections/cifmw/general/plugins/modules/tempest_list_skipped.py
Labels: Ready For Review

#3120 Update: Don't fail if the monitoring process is not up anymore.
  playbooks/update.yml
Labels: Ready For Review

#3167 Avoid switching OpenShift project in hook
  hooks/playbooks/cinder_multiattach_volume_type.yml
Labels: lgtm, Ready For Review

#3112 Replace deprecated 'cifmw_test_operator_concurrency'
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  zuul.d/whitebox_neutron_tempest_jobs.yaml
Labels: lgtm, Ready For Review

#3153 Add KRB5_TRACE variable for trace logging output
  roles/dlrn_report/tasks/dlrn_report_results.yml
Labels: approved, Ready For Review
