Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-05, with the labels that each got.

#2924 Change callback plugin to default; format callback result to yaml
  ansible.cfg
Labels: lgtm, Ready For Review

#2943 Updated dictionary
  docs/dictionary/en-custom.txt
Labels: lgtm, Ready For Review

#2944 Removed rdo-jobs requirement from molecule
  zuul.d/molecule-base.yaml
Labels: Ready For Review

#2930 Change the way how the hooks playbook is executed
  ci/playbooks/kuttl/e2e-kuttl.yml
  deploy-edpm.yml
  playbooks/02-infra.yml
  playbooks/03-build-packages.yml
  playbooks/04-build-containers.yml
  playbooks/05-build-operators.yml
  playbooks/06-deploy-architecture.yml
  playbooks/06-deploy-edpm.yml
  playbooks/07-admin-setup.yml
  playbooks/08-run-tests.yml
  playbooks/98-pre-end.yml
  playbooks/hooks.yml
  playbooks/update.yml
Labels: Ready For Review

#2866 Use correct ansible module to print variable vlaue
  roles/dlrn_promote/tasks/check_for_previous_promotions.yml
Labels: Stale

#2931 Increase CEPH_TIMEOUT for component tests
  scenarios/centos-9/ceph_backends.yml
  scenarios/centos-9/ci.yml
Labels: Ready For Review

#2824 Add reporting for playbook testing
  roles/validations/tasks/security/invoke_tlse_playbooks.yml
Labels: Stale, Ready For Review

#2950 Add epoxy release mapping in build_openstack_packages role
  roles/build_openstack_packages/defaults/main.yml
Labels: Ready For Review

#2952 Simplify files to track by Zuul
  ci/config/molecule.yaml
  ci/templates/molecule.yaml.j2
  ci/templates/noop-molecule.yaml.j2
  zuul.d/adoption.yaml
  zuul.d/architecture-jobs.yaml
  zuul.d/content_provider.yaml
  zuul.d/edpm.yaml
  zuul.d/end-to-end.yaml
  zuul.d/molecule.yaml
  zuul.d/tcib.yaml
Labels: Ready For Review

#2939 Retry OCP CSR approval
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: Ready For Review

#2951 Update Ansible requirements to latest version
  requirements.yml
  zuul.d/base.yaml
  zuul.d/kuttl_multinode.yaml
Labels: Ready For Review

#2938 Set jinja2_native in Ansible to preserve variable types during template operations
  ansible.cfg
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/stages.yml
Labels: Ready For Review

#2927 Add conditional for use CentOS nodepool mirror
  roles/build_containers/templates/build_containers.sh.j2
  roles/repo_setup/tasks/ci_mirror.yml
Labels: lgtm, Ready For Review

#2965 Fix setting fact for cifmw_test_operator_concurrency
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/stages.yml
Labels: Ready For Review

#2970 dnsmasq: Fix start_v[4|6] is None
  roles/config_drive/tasks/main.yml
  roles/dnsmasq/templates/network.conf.j2
  roles/libvirt_manager/tasks/generate_networking_data.yml
Labels: Ready For Review

#2947 The workflow needs -f flag to rebase and push on a branch
  .github/workflows/sync_branches_reusable_workflow.yml
Labels: Ready For Review

#2960 Add for each worker journalctl kubelet logs
  ci/playbooks/collect-logs.yml
  ci/playbooks/e2e-collect-logs.yml
Labels: Ready For Review

#2906 Update CRDs when changing test-operator version
  roles/test_operator/README.md
  roles/test_operator/tasks/main.yml
Labels: Ready For Review

#2897 Add tobiko_cleanup in cifmw
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
  roles/test_operator/tasks/runners/tobiko_runner.yml
Labels: Ready For Review

#2919 Reuse OCP cluster
  clean_openstack_deployment.yaml
  deploy-edpm-reuse.yaml
  roles/kustomize_deploy/tasks/cleanup.yml
  roles/reproducer/tasks/configure_cleanup.yaml
  roles/reproducer/tasks/reuse_main.yaml
Labels: lgtm, Ready For Review

#2978 Add become for log delete
  clean_openstack_deployment.yaml
Labels: Ready For Review

#2976 Allow skiping edpm log gathering
  roles/artifacts/README.md
  roles/artifacts/tasks/main.yml
Labels: Ready For Review

#2975 Force dump admin password as a string
  roles/test_operator/defaults/main.yml
Labels: Ready For Review

#2993 Add variable to turn off artifact masking
  roles/artifacts/README.md
  roles/artifacts/defaults/main.yml
  roles/artifacts/tasks/main.yml
Labels: Ready For Review

#2992 Use modules for enabling rhel subscription
  roles/adoption_osp_deploy/tasks/login_registries.yml
  roles/adoption_osp_deploy/tasks/prepare_overcloud.yml
  roles/adoption_osp_deploy/tasks/prepare_undercloud.yml
Labels: Ready For Review

#2967 Drop PyYAML package for bindep
  bindep.txt
Labels: Ready For Review

#2995 Use sync module instead of rsync command
  roles/reproducer/tasks/push_code.yml
Labels: Ready For Review

#2979 Reboot controller-0 to avoid running deployments
  deploy-edpm-reuse.yaml
Labels: Ready For Review

#2998 ci_dcn_site: Set cross_az_attach at nova-api
  roles/ci_dcn_site/templates/service-values.yaml.j2
Labels: lgtm, Ready For Review

#2913 Add scenario unidelta_ipv6 adoption
  scenarios/adoption/uni04delta-ipv6.yml
Labels: Ready For Review

#2977 Use role instead of playbooks - 02-infra.yml
  ci/playbooks/kuttl/deploy-deps.yaml
  deploy-edpm.yml
  playbooks/01-bootstrap.yml
  playbooks/02-infra.yml
  roles/cifmw_setup/tasks/host_virtualization.yml
  roles/cifmw_setup/tasks/infra.yml
Labels: Ready For Review

#3005 Revert "Add reporting for playbook testing"
  roles/validations/tasks/security/invoke_tlse_playbooks.yml
Labels: lgtm

#2991 Add a containers tag role
  roles/build_containers/README.md
  roles/build_containers/defaults/main.yml
  roles/build_containers/tasks/main.yml
  roles/build_containers/tasks/tag.yml
Labels: lgtm, Ready For Review

#2935 Fix continuous control plane testing during update
  roles/update/tasks/collect_openstackclient_config.yml
  roles/update/tasks/create_local_openstackclient.yml
  roles/update/tasks/main.yml
  roles/update/templates/workload_launch_k8s.sh.j2
Labels: Ready For Review

#3011 Fix ansible.posix requirements
  requirements.yml
Labels: Ready For Review

#3008 Added cs10 nodeset needed for meta content provider
  zuul.d/nodeset.yaml
Labels: Ready For Review

#3004 Add empty adoption scenario uni02beta
  scenarios/adoption/uni02beta.yml
Labels: Ready For Review

#3012 Add nodesets for 3xl crc nodes with 2 compute nodes
  zuul.d/nodeset.yaml
Labels: lgtm, Ready For Review

#3021 Increase wait_timeout for removing storage
  roles/ci_local_storage/tasks/cleanup.yml
Labels: lgtm
