Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-01, with the labels that each got.

#2620 Add the hypervisors to the inventory
  roles/libvirt_manager/templates/all-inventory.yml.j2
  roles/libvirt_manager/templates/inventory.yml.j2
  roles/reproducer/tasks/configure_controller.yml
Labels: approved, lgtm, Ready For Review

#2584 Switch antelope branch to unmaintained/2023.1
  roles/build_openstack_packages/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2633 Add retry to cephadm install
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/install_cephadm.yml
Labels: approved, lgtm

#2636 [polarion] Quote the custom_fields parameter to be shell safe
  roles/polarion/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2628 KUTTL: don't bail out immediately, save the test reports
  ci/playbooks/kuttl/run-kuttl-tests.yml
Labels: approved, lgtm, Ready For Review

#2617 [Test-operator] Set resource limits
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2626 Add hypervisor param to shiftstack playbook execution
  roles/shiftstack/README.md
  roles/shiftstack/defaults/main.yml
  roles/shiftstack/tasks/test_config.yml
Labels: approved, lgtm, Ready For Review

#2631 [OSPRH-12761] Adjust post-deploy image collection for OpenStack init controller pod
  roles/env_op_images/tasks/main.yml
Labels: approved, lgtm, Ready For Review

#2622 Refines codeowners file to add ownership of template files
  .github/CODEOWNERS
Labels: approved, lgtm, Ready For Review

#2629 Adoption ironic hook - IPA var/lib/ironic/httpboot
  hooks/playbooks/adoption_ironic_post_oc.yml
Labels: approved, lgtm, Ready For Review

#2618 Add configuration variables for control plane testing during update.
  roles/update/README.md
  roles/update/defaults/main.yml
  roles/update/tasks/main.yml
  roles/update/templates/control_plane_test_stop.sh.j2
Labels: approved, lgtm, Feature, Ready For Review

#2632 [repo_setup] Download rhos-release using kerberos
  docs/dictionary/en-custom.txt
  plugins/modules/url_request.py
  roles/repo_setup/README.md
  roles/repo_setup/defaults/main.yml
  roles/repo_setup/tasks/rhos_release.yml
  tests/sanity/ignore.txt
Labels: approved, lgtm, Ready For Review

#2627 Add possibility to run HorizonTest in debug mode
  roles/test_operator/README.md
  roles/test_operator/defaults/main.yml
Labels: approved, lgtm, Ready For Review

#2643 Ensure EPEL is reinstalled
  roles/ci_setup/tasks/epel.yml
Labels: approved, lgtm, Ready For Review

#2646 Adds cifmw squad to codeowners
  .github/CODEOWNERS
  OWNERS
Labels: approved, lgtm, Ready For Review

#2647 [repo_setup] Use a role scoped copy of url_request
  roles/repo_setup/library/url_request.py
  roles/repo_setup/tasks/rhos_release.yml
Labels: Ready For Review

#2655 Remove auto draft GH action
  .github/workflows/auto-draft.yml
Labels: approved, lgtm, Ready For Review

#2654 [url_request] Use gssapi lib by default
  plugins/modules/url_request.py
Labels: approved, lgtm, Ready For Review

#2661 Unset resources section in workflows
  roles/test_operator/tasks/tempest-tests.yml
Labels: approved, lgtm, Ready For Review

#2640 Add retry to the cephadm installation
  roles/cifmw_cephadm/defaults/main.yml
  roles/cifmw_cephadm/tasks/pre.yml
Labels: approved, lgtm, Ready For Review

#2666 [18.0-fr1] Add RHOSO kubeconfigfile to shiftstackclient pod
  roles/shiftstack/README.md
  roles/shiftstack/defaults/main.yml
  roles/shiftstack/tasks/cleanup.yml
  roles/shiftstack/tasks/deploy_shiftstackclient_pod.yml
  roles/shiftstack/templates/shiftstackclient_incluster_kubeconfig_secret.yml.j2
  roles/shiftstack/templates/shiftstackclient_pod.yml.j2
Labels: approved, lgtm, Ready For Review

#2674 [test_operator] Avoid overwriting previous changes in tempest workflows
  roles/test_operator/tasks/tempest-tests.yml
Labels: approved, lgtm, Ready For Review

#2658 Use make openstack_init in kuttl test playbook
  ci/playbooks/kuttl/deploy-deps.yaml
Labels: approved, lgtm, Ready For Review

#2545 Update uni05 nodesets to allow for new cell
  roles/ci_gen_kustomize_values/templates/uni05epsilon/edpm-nodeset-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni05epsilon/edpm-nodeset2-values/values.yaml.j2
Labels: approved, lgtm, Ready For Review

#2675 Fix after_kuttl commands so that the output is not truncated
  ci/playbooks/kuttl/run-kuttl-tests.yml
Labels: approved, lgtm, Ready For Review

#2680 Adds gh action to check for DNM labels
  .github/workflows/check-dnm-label.yml
Labels: approved, Ready For Review

#2672 Add call to 'make bindata' in operator-build for meta operator
  roles/operator_build/tasks/build.yml
Labels: approved, lgtm, Ready For Review

#2693 [edpm_image_builder] Fix virt-customize run after #2673
  roles/edpm_build_images/tasks/add_cert.yml
Labels: approved

#2648 Add pre adoption resources delete hook
  hooks/playbooks/delete_all_pre_adoption_resources.yaml
Labels: Ready For Review

#2677 Fix release_minor value in project.ini
  roles/build_openstack_packages/templates/projects.ini.j2
Labels: approved, lgtm, Ready For Review

#2676 Lower the priority of component repo when gating repo is used
  roles/repo_setup/tasks/populate_gating_repo.yml
Labels: approved, lgtm, Ready For Review
