Repository openstack-k8s-operators/ci-framework, pull requests merged in 2025-10, with the labels that each got.

#3357 Fix output of must-gather log
  roles/os_must_gather/tasks/main.yml
Labels: lgtm, Ready For Review

#3344 feat(artifacts): Replace hardcoded zuul path with configurable variable
  roles/artifacts/tasks/edpm.yml
Labels: Ready For Review

#3056 Make worker-Nodes take preference in nncp ci_kustomize
  roles/ci_dcn_site/templates/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp-l3-xl/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bgp_dt01/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/bmo01/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/common/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/dcn/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/multi-namespace/network-values2/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/osasinfra-ipv6/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/shiftstack/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni01alpha-adoption/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni01alpha/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni04delta-ipv6-adoption/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni04delta-ipv6/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni05epsilon/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni06zeta/network-values/values.yaml.j2
  roles/ci_gen_kustomize_values/templates/uni07eta/network-values/values.yaml.j2
Labels: lgtm, needs-ok-to-test, Ready For Review

#3365 Add pidone network-values template
  roles/ci_gen_kustomize_values/templates/pidone/network-values/values.yaml.j2
Labels: lgtm, Ready For Review

#3345 Make a symlink of os_must_gather dir to static name dir
  roles/os_must_gather/defaults/main.yml
  roles/os_must_gather/tasks/main.yml
Labels: lgtm

#3326 Fix openshift_adm role context when kubeconfig has multiple clusters
  roles/openshift_adm/README.md
  roles/openshift_adm/defaults/main.yml
  roles/openshift_adm/tasks/_get_api_server.yml
  roles/openshift_adm/tasks/_get_nodes.yml
  roles/openshift_adm/tasks/api_cert.yml
  roles/openshift_adm/tasks/main.yml
  roles/openshift_adm/tasks/shutdown.yml
  roles/openshift_adm/tasks/wait_for_cluster.yml
Labels: Ready For Review

#3364 Add parse ansible argument string to variables
  roles/cifmw_helpers/README.md
  roles/cifmw_helpers/tasks/parse_ansible_args_string.yml
Labels: Ready For Review
